export const neuroscienceLessonDetails: Record<string, string[]> = {
  A01: [
    'Dendrites and the soma collect many small inputs, while the axon initial segment is often where a spike begins.',
    'Axon terminals convert an electrical spike into a synaptic signal by releasing transmitter onto a target cell.',
    'Neuronal shape supports function: pyramidal cells, interneurons, sensory neurons, and motor neurons solve different circuit problems.',
    'A single neuron is both a biological cell and an information-processing unit, so its structure matters for computation.',
  ],
  A02: [
    'The resting voltage depends on ion gradients, selective membrane permeability, and large negatively charged molecules inside the cell.',
    'K+ leak channels make the resting membrane closer to the potassium equilibrium potential than to the sodium equilibrium potential.',
    'The Na+/K+ pump maintains gradients over time by using ATP to move Na+ out and K+ in.',
    'A stable resting potential gives neurons a baseline from which small synaptic inputs can be measured.',
  ],
  A03: [
    'An ion current depends on how many channels are open and on the driving force between membrane voltage and the ion reversal potential.',
    'Opening Na+ channels usually depolarizes the membrane, while opening K+ or many Cl- channels usually makes firing less likely.',
    'Voltage-gated, ligand-gated, and leak channels each contribute different time scales to neural signaling.',
    'Conductance-based models are useful because they connect equations directly to channel opening and ion flow.',
  ],
  A04: [
    'A spike starts when depolarization opens enough voltage-gated Na+ channels to trigger positive feedback.',
    'Repolarization follows because Na+ channels inactivate and voltage-gated K+ channels help bring the membrane back down.',
    'The refractory period limits the maximum firing rate and helps action potentials travel in one direction along the axon.',
    'Spike timing can carry information, but the amplitude of a normal action potential is mostly all-or-none.',
  ],
  A05: [
    'At most chemical synapses, a presynaptic action potential opens voltage-gated Ca2+ channels near vesicle release sites.',
    'Ca2+ entry makes synaptic vesicles fuse with the presynaptic membrane, releasing transmitter into the cleft.',
    'Postsynaptic receptors translate transmitter binding into ion flow or intracellular signaling.',
    'Synaptic delay is short but real, which matters when circuits rely on precise timing.',
  ],
  A06: [
    'Excitation and inhibition describe the postsynaptic effect, not a permanent label for a transmitter in every circuit.',
    'Glutamatergic synapses often create EPSPs by allowing positive charge to enter the postsynaptic cell.',
    'GABAergic and glycinergic synapses often create IPSPs or shunting inhibition that lowers the impact of excitation.',
    'Balanced excitation and inhibition lets circuits stay responsive without becoming unstable.',
  ],
  A07: [
    'A transmitter is defined by synthesis in the neuron, release from terminals, receptor action, and a mechanism for removal or breakdown.',
    'Glutamate is the main fast excitatory transmitter in much of the brain, while GABA is the main fast inhibitory transmitter.',
    'Acetylcholine, dopamine, serotonin, norepinephrine, and neuropeptides often tune circuit state rather than simply turning neurons on or off.',
    'The same transmitter can have different effects depending on receptor type and target cell.',
    'Co-release means one neuron can release more than one transmitter, often combining a fast small molecule with a slower modulator or peptide.',
  ],
  A41: [
    'Small clear synaptic vesicles usually contain classical transmitters such as glutamate, GABA, or acetylcholine.',
    'Vesicle filling depends on transporter proteins that use ion gradients across the vesicle membrane.',
    'Docking and priming prepare vesicles at active zones so calcium can trigger fusion quickly when a spike arrives.',
    'Endocytosis retrieves vesicle membrane after fusion, allowing terminals to recycle vesicles during ongoing activity.',
    'Release probability and the size of the readily releasable vesicle pool strongly shape synaptic strength.',
  ],
  A42: [
    'The older one-neuron-one-transmitter rule is too simple: many neurons can release multiple chemical messengers.',
    'Fast transmitters usually act within milliseconds, while peptides and many modulators can act over seconds or longer.',
    'Co-release can depend on firing pattern because bursts and sustained activity often recruit release mechanisms differently from single spikes.',
    'The postsynaptic effect depends on which receptors are present, so the same released chemical mix can affect targets differently.',
    'For modelling, co-release is a reminder that a synapse may carry fast signalling, slow modulation, and state-dependent plasticity together.',
  ],
  A08: [
    'Ionotropic receptors are receptor-channels, so they can change membrane conductance quickly.',
    'Metabotropic receptors use intracellular signaling cascades, so they can change excitability, plasticity, or transmitter release for longer periods.',
    'Neuromodulators often change the gain of a circuit, making the same input produce a different output depending on brain state.',
    'A receptor tells the cell how to interpret a transmitter, which is why receptor subtype matters.',
  ],
  A09: [
    'Astrocytes regulate extracellular ions, help recycle transmitters, and support synaptic metabolism.',
    'Oligodendrocytes in the central nervous system and Schwann cells in the peripheral nervous system produce myelin.',
    'Microglia survey neural tissue, respond to injury, and help shape synapses during development and disease.',
    'Glia are active partners in signaling, maintenance, repair, and circuit refinement.',
  ],
  A10: [
    'A receptive field describes the part of the sensory world that changes a neuron\'s activity.',
    'Sensory neurons often prefer specific features, such as location, contrast, sound frequency, touch direction, or movement.',
    'Receptive fields are shaped by both feedforward inputs and local circuit interactions.',
    'Population activity is important because perception usually depends on patterns across many tuned neurons.',
  ],
  A11: [
    'Motor control uses loops between cortex, spinal cord, brainstem, basal ganglia, and cerebellum.',
    'Upper motor neurons help plan and command movement, while lower motor neurons directly activate muscle fibers.',
    'Sensory feedback continuously updates movement so commands can be corrected while they unfold.',
    'Movement is not just output; it is a closed loop between prediction, action, and feedback.',
  ],
  A12: [
    'Neocortex is arranged in layers with different input and output patterns.',
    'Layer 4 receives strong sensory thalamic input in many primary sensory areas.',
    'Layers 2 and 3 support local and cortico-cortical communication, while layers 5 and 6 send major outputs to subcortical and thalamic targets.',
    'Cortical columns and layers are useful maps, but real cortex is also shaped by cell type, long-range input, and brain state.',
  ],
  A13: [
    'The thalamus is not a passive relay; it can gate, synchronize, and reshape signals before they reach cortex.',
    'Many thalamic nuclei form reciprocal loops with specific cortical regions.',
    'Thalamic firing mode changes with state, for example between burst-like activity and more tonic relay.',
    'Attention, sleep, and sensory processing all depend on thalamo-cortical interactions.',
  ],
  A14: [
    'The basal ganglia help select actions by comparing competing cortical plans through loops with cortex and thalamus.',
    'Direct and indirect pathways are a useful simplified model for promoting or suppressing actions.',
    'Dopamine changes the balance of these pathways and carries information related to reward prediction and action value.',
    'Basal ganglia disorders show why action selection, motivation, and movement control are tightly linked.',
  ],
  A15: [
    'The cerebellum compares intended movement with sensory feedback and helps reduce error over repeated attempts.',
    'Purkinje cells are the main output neurons of the cerebellar cortex and inhibit deep cerebellar nuclei.',
    'Climbing fiber input can act like a strong teaching signal when an action produces an error.',
    'Cerebellar learning is important for timing, coordination, adaptation, and some cognitive predictions.',
  ],
  A16: [
    'The hippocampal formation links items, places, and temporal context into episodic memories.',
    'Place cells, grid cells, and head-direction signals provide a spatial framework for memory.',
    'Hippocampal circuits support pattern separation, which keeps similar experiences from being confused.',
    'Replay during rest and sleep may help stabilize memories and train cortical networks.',
  ],
  A17: [
    'The amygdala helps assign emotional and motivational significance to sensory events.',
    'Fear learning links a cue to an aversive outcome through changes in synaptic strength.',
    'Amygdala outputs influence autonomic responses, attention, memory, and defensive behavior.',
    'Emotion is distributed across circuits, so the amygdala is important but not the whole story.',
  ],
  A18: [
    'Attention increases the impact of selected information and often reduces the influence of competing signals.',
    'Prefrontal and parietal networks help maintain task goals and bias sensory processing.',
    'Executive control includes working memory, inhibition, switching, and monitoring performance.',
    'Attention is implemented by circuits, not by a single spotlight location in the brain.',
  ],
  A19: [
    'Brain rhythms reflect coordinated changes in population activity, not tiny neurons taking turns like a clock.',
    'Sleep stages have distinct electrical signatures, including slow waves, spindles, and REM-associated activity.',
    'Oscillations can help coordinate communication between distant regions by aligning excitability windows.',
    'Sleep supports learning through memory reactivation, synaptic regulation, and metabolic recovery.',
  ],
  A20: [
    'Electrophysiology measures electrical activity with high temporal precision, often down to spikes and milliseconds.',
    'Calcium imaging follows activity-related calcium signals across many cells, but the signal is slower than a spike.',
    'fMRI measures blood oxygenation changes, so it is indirect and has much slower timing than neural firing.',
    'Optogenetics and chemogenetics can perturb selected cell types, making causal tests possible when designed carefully.',
  ],
  A21: [
    'Many excitatory synapses onto cortical pyramidal neurons sit on dendritic spines.',
    'A spine can partly isolate biochemical signals, letting one synapse change without changing every nearby synapse.',
    'Spine size often relates to synaptic strength, though the relationship is not perfectly one-to-one.',
    'Spines are dynamic structures that can grow, shrink, appear, or disappear with experience and disease.',
  ],
  A22: [
    'Myelin increases conduction speed by insulating axon segments and reducing current leak.',
    'Nodes of Ranvier concentrate voltage-gated Na+ channels, so spikes regenerate from node to node.',
    'Saltatory conduction is faster and more energy efficient than continuous regeneration along an unmyelinated axon.',
    'Myelination changes across development and can be disrupted in neurological disease.',
  ],
  A23: [
    'Long axons need active transport because diffusion alone is too slow over large distances.',
    'Kinesin motors usually move cargo away from the soma, while dynein motors move cargo back toward the soma.',
    'Transported cargo includes vesicles, mitochondria, proteins, RNA, and damaged material for recycling.',
    'Transport failure can stress synapses and is an important theme in several neurodegenerative disorders.',
  ],
  A24: [
    'Synaptic plasticity changes the strength or timing of communication between neurons.',
    'Long-term potentiation often involves NMDA receptor activation, Ca2+ entry, and increased AMPA receptor function.',
    'Long-term depression can weaken synapses through receptor removal or other signaling changes.',
    'Plasticity is input-specific but also constrained by circuit stability and neuromodulatory context.',
  ],
  A25: [
    'Homeostatic plasticity keeps average activity within a workable range over hours to days.',
    'A circuit can adjust synaptic strengths, membrane excitability, inhibition, or transmitter release probability.',
    'Homeostasis prevents runaway excitation and prevents useful signals from fading into silence.',
    'Learning and homeostasis cooperate: one changes selected connections, the other protects the operating range.',
  ],
  A26: [
    'The brain uses a large share of the body\'s energy because ion gradients must be restored after signaling.',
    'Spikes, synaptic transmission, transmitter recycling, and membrane pumps all consume ATP.',
    'Astrocytes and blood vessels help match local energy supply to local neural activity.',
    'Energy limits influence coding strategies because every spike and synaptic event has a metabolic cost.',
  ],
  A27: [
    'The blood-brain barrier is formed mainly by specialized endothelial cells with tight junctions.',
    'Astrocyte endfeet and pericytes help regulate the barrier and the local vascular environment.',
    'The barrier protects neural tissue but also makes drug delivery to the brain difficult.',
    'Barrier disruption can change inflammation, ion balance, and neural excitability.',
  ],
  A28: [
    'Brain development includes cell birth, migration, axon guidance, synapse formation, pruning, and myelination.',
    'Molecular gradients guide early wiring, while spontaneous and sensory-driven activity refine later connections.',
    'Overproduction followed by selection is common: circuits make many connections and then keep the useful ones.',
    'Development is not finished at birth; experience keeps shaping circuits for years.',
  ],
  A29: [
    'A critical period is a developmental window when experience has an especially strong and lasting effect.',
    'Inhibitory circuit maturation helps open and regulate several critical periods.',
    'Closing a critical period can involve structural stabilization, such as extracellular matrix changes around neurons.',
    'Critical periods show that timing matters: the same input can have different effects at different ages.',
  ],
  A30: [
    'A connectome describes wiring, but wiring alone does not determine activity without cell types, weights, and dynamics.',
    'Common motifs include feedforward chains, feedback loops, recurrent excitation, and inhibitory control.',
    'Structural connectivity constrains possible communication, while functional connectivity describes correlated activity.',
    'Network measures can reveal hubs and modules, but biological interpretation still needs anatomy and physiology.',
  ],
  A31: [
    'Resting-state networks are patterns of correlated activity observed when a person is not performing a specific task.',
    'The default mode, attention, sensory, and control networks are common large-scale examples.',
    'Resting-state fMRI correlations are indirect and slow, so they should not be treated as direct spike communication.',
    'These networks can change with development, disease, attention, sleep, and arousal.',
  ],
  A32: [
    'Brain state changes the responsiveness of circuits through arousal systems, neuromodulators, and ongoing rhythms.',
    'Norepinephrine, acetylcholine, dopamine, serotonin, and histamine help tune vigilance, learning, and action readiness.',
    'The same stimulus can evoke different neural responses when the animal is alert, drowsy, stressed, or engaged.',
    'State is a hidden variable that good experiments and models try to measure or control.',
  ],
  A33: [
    'Nociceptors detect potentially damaging mechanical, thermal, or chemical events.',
    'Pain signals enter the spinal cord, pass through local gating circuits, and ascend toward brainstem, thalamic, and cortical regions.',
    'Descending pathways can amplify or suppress pain depending on context, expectation, and threat.',
    'Pain is a perception built by the nervous system, not a direct meter of tissue damage.',
  ],
  A34: [
    'Interoception tracks internal variables such as heartbeat, breathing, temperature, hunger, nausea, and visceral discomfort.',
    'Signals from the body reach brainstem nuclei, thalamus, insula, cingulate cortex, and hypothalamus.',
    'Interoceptive signals help shape emotion because the brain interprets body state when evaluating context.',
    'Computationally, interoception is about estimating hidden body states from noisy internal signals.',
  ],
  A35: [
    'The autonomic nervous system regulates organs through sympathetic, parasympathetic, and enteric pathways.',
    'Sympathetic activity prepares the body for challenge, while parasympathetic activity supports recovery, digestion, and energy conservation.',
    'The vagus nerve is a major parasympathetic route linking brainstem circuits with heart, lungs, and gut.',
    'Autonomic control is continuous and feedback-based, not simply an on/off switch.',
  ],
  A36: [
    'The HPA axis links hypothalamus, pituitary, and adrenal gland to coordinate hormonal stress responses.',
    'Cortisol helps mobilize energy and changes immune, memory, and arousal systems.',
    'Negative feedback normally reduces HPA activation once the challenge has passed.',
    'Chronic stress can alter synapses, sleep, attention, mood, and learning.',
  ],
  A37: [
    'Neuroinflammation involves microglia, astrocytes, cytokines, blood vessels, and sometimes peripheral immune cells.',
    'Inflammation can protect tissue after injury, but persistent inflammatory signaling can harm synapses and neurons.',
    'Microglia can remove debris and also participate in synaptic pruning.',
    'Repair depends on timing, cell type, and context, so inflammation is not simply helpful or harmful.',
  ],
  A38: [
    'Neurodegenerative disorders often target specific cell types and circuits before damage becomes widespread.',
    'Protein aggregation, mitochondrial stress, inflammation, transport failure, and synapse loss are recurring mechanisms.',
    'Symptoms reflect circuit failure, which is why cell loss in different regions causes different clinical patterns.',
    'Early synaptic dysfunction can appear before large-scale neuron loss.',
  ],
  A39: [
    'Psychiatric disorders are best understood as distributed circuit and developmental problems, not as single-location lesions.',
    'Mood, motivation, threat learning, attention, and social behavior depend on interacting cortical, limbic, striatal, and brainstem systems.',
    'Genes and environment can shift circuit development, plasticity, stress responses, and neuromodulation.',
    'Circuit models can guide hypotheses, but individual symptoms still vary across people.',
  ],
  A40: [
    'A neuroscience claim should be matched to the method: recording, imaging, lesion, perturbation, anatomy, behavior, or model.',
    'Correlation shows association, while causal claims need stronger designs such as perturbation, lesion evidence, or controlled intervention.',
    'Every method trades off spatial resolution, temporal resolution, invasiveness, coverage, and interpretability.',
    'Good reading asks what was measured, what was inferred, what alternative explanations remain, and whether the effect replicates.',
  ],
};
