import { Lesson } from './types';

/**
 * Track C — Computational Neuroscience and Modern Concepts. 30 lessons.
 * Progressively unlocked by prerequisites within the track and basic Track B
 * progress.
 */
export const trackCLessons: Lesson[] = [
  {
    id: 'C01',
    trackId: 'compneuro',
    moduleId: 'C-neuron-models',
    order: 1,
    title: 'Leaky integrate-and-fire neuron',
    subtitle: 'The simplest spiking neuron model',
    estimatedMinutes: 6,
    difficulty: 'beginner',
    prerequisites: ['B15'],
    explanation:
      'A leaky integrate-and-fire neuron integrates its inputs through a leaky membrane and emits a spike whenever the voltage crosses a threshold. After a spike, the voltage is reset. It captures the essential \u201ccharge up, fire, reset\u201d rhythm of a real neuron with just one equation.',
    notation: '\u03c4 dV/dt = \u2212(V \u2212 V_rest) + I(t);  if V \u2265 V_th \u2192 spike, V \u2190 V_reset',
    keyTerms: ['leak', 'threshold', 'reset', 'input current'],
    example:
      'Given a constant input current, an LIF neuron fires regularly at a rate determined by how quickly its voltage reaches threshold.',
    intuition: 'Charge a leaky bucket. Every time it overflows, you mark a spike and start again.',
    whyItMatters:
      'It is the workhorse of theoretical neuroscience because it is both analytically tractable and biologically meaningful.',
    questions: [
      {
        prompt: 'Why is the model called "leaky"?',
        options: [
          'Because the membrane leaks spikes',
          'Because without input, V returns to rest',
          'Because neurotransmitter leaks out',
          'Because the threshold decays',
        ],
        answerIndex: 1,
        explanation: 'The leak term pulls V back toward rest in the absence of input.',
      },
      {
        prompt: 'What happens when V crosses the threshold V_th?',
        options: [
          'A spike is recorded and V is reset',
          'V stays at V_th forever',
          'The neuron dies',
          'The time constant changes',
        ],
        answerIndex: 0,
        explanation: 'The model emits a spike and resets V to V_reset.',
      },
      {
        prompt: 'Given larger constant input, the LIF firing rate...',
        options: ['Decreases', 'Stays the same', 'Increases', 'Becomes random'],
        answerIndex: 2,
        explanation: 'More input drives faster integration and more frequent threshold crossings.',
      },
    ],
    xpReward: 26,
    coinReward: 10,
    masteryThreshold: 0.8,
  },
  {
    id: 'C02',
    trackId: 'compneuro',
    moduleId: 'C-neuron-models',
    order: 2,
    title: 'Membrane time constant and capacitance',
    subtitle: 'What controls how fast a neuron reacts',
    estimatedMinutes: 5,
    difficulty: 'beginner',
    prerequisites: ['C01'],
    explanation:
      'The membrane time constant \u03c4 = R*C depends on the membrane resistance R and capacitance C. It sets how quickly voltage responds to a change in input. A short \u03c4 means fast reactions; a long \u03c4 smooths inputs over time.',
    notation: '\u03c4 = R \u00d7 C',
    keyTerms: ['time constant', 'capacitance', 'resistance', 'integration window'],
    example:
      'Cortical neurons typically have time constants around 10\u201330 ms, which roughly matches how long they effectively integrate incoming spikes.',
    intuition: 'Big \u03c4 = patient neuron. Small \u03c4 = fast, twitchy neuron.',
    whyItMatters:
      'Integration windows shape which temporal patterns a neuron is sensitive to.',
    questions: [
      {
        prompt: 'If the membrane resistance increases while capacitance stays the same, \u03c4...',
        options: ['Decreases', 'Stays the same', 'Increases', 'Becomes negative'],
        answerIndex: 2,
        explanation: 'Since \u03c4 = R*C, larger R means larger \u03c4.',
      },
      {
        prompt: 'A neuron with a very short \u03c4 is best at...',
        options: [
          'Integrating inputs over long windows',
          'Reacting quickly to fast changes',
          'Ignoring all input',
          'Spiking only once in its lifetime',
        ],
        answerIndex: 1,
        explanation: 'Small time constants favour fast reactions over integration.',
      },
      {
        prompt: 'A large \u03c4 effectively...',
        options: [
          'Smooths and integrates inputs over a longer window',
          'Produces instantaneous responses',
          'Removes the need for a threshold',
          'Increases the reset voltage',
        ],
        answerIndex: 0,
        explanation: 'Bigger \u03c4 means slower decay, so inputs accumulate for longer.',
      },
    ],
    xpReward: 22,
    coinReward: 8,
    masteryThreshold: 0.8,
  },
  {
    id: 'C03',
    trackId: 'compneuro',
    moduleId: 'C-neuron-models',
    order: 3,
    title: 'Threshold, reset, and refractoriness',
    subtitle: 'The three knobs that shape spike trains',
    estimatedMinutes: 5,
    difficulty: 'beginner',
    prerequisites: ['C02'],
    explanation:
      'The threshold V_th sets how easily a neuron fires. The reset V_reset determines where the voltage lands after a spike. A refractory period prevents back-to-back spikes for a short time. Together they cap the maximum firing rate.',
    notation: 'V_th, V_reset, \u0394t_ref',
    keyTerms: ['threshold', 'reset', 'refractory period'],
    example:
      'A refractory period of 2 ms limits a neuron to roughly 500 spikes per second even under very strong input.',
    intuition: 'Thresholds and refractoriness keep the neuron honest \u2014 it cannot shout forever.',
    whyItMatters:
      'These parameters set how faithfully a neuron can represent high-frequency inputs.',
    questions: [
      {
        prompt: 'Lowering V_th makes the neuron...',
        options: ['Harder to fire', 'Easier to fire', 'Unchanged', 'Silent forever'],
        answerIndex: 1,
        explanation: 'With a lower threshold, smaller depolarisations cause spikes.',
      },
      {
        prompt: 'A 2 ms absolute refractory period limits firing to roughly...',
        options: ['5 Hz', '50 Hz', '500 Hz', 'Unlimited'],
        answerIndex: 2,
        explanation: '1 / 0.002 s = 500 Hz.',
      },
      {
        prompt: 'After a spike, the voltage...',
        options: [
          'Is set to V_reset, typically below threshold',
          'Remains at V_th',
          'Jumps to a random value',
          'Depends on the next input only',
        ],
        answerIndex: 0,
        explanation: 'By convention, a spike triggers a reset to V_reset.',
      },
    ],
    xpReward: 22,
    coinReward: 8,
    masteryThreshold: 0.8,
  },
  {
    id: 'C04',
    trackId: 'compneuro',
    moduleId: 'C-rate',
    order: 4,
    title: 'Firing rate models',
    subtitle: 'Replacing spikes with smooth rates',
    estimatedMinutes: 5,
    difficulty: 'beginner',
    prerequisites: ['C01', 'B13'],
    explanation:
      'Instead of tracking every spike, firing rate models represent a neuron by its average firing rate r. A common equation is \u03c4 dr/dt = \u2212r + f(input), where f is a nonlinearity like a sigmoid or rectifier.',
    notation: '\u03c4 dr/dt = \u2212r + f(u)',
    keyTerms: ['firing rate', 'transfer function', 'nonlinearity'],
    example:
      'Simple recurrent rate models use this form to describe how populations of neurons evolve over timescales of tens of milliseconds.',
    intuition: 'Zoom out. Instead of individual spikes, we track the smooth rate at which they arrive.',
    whyItMatters:
      'Rate models are more tractable than spiking models and still capture population-level behaviour.',
    questions: [
      {
        prompt: 'In \u03c4 dr/dt = \u2212r + f(u), the steady state is...',
        options: ['r = 0', 'r = f(u)', 'r = u', 'r = \u03c4'],
        answerIndex: 1,
        explanation: 'Setting dr/dt = 0 gives r = f(u).',
      },
      {
        prompt: 'A rectifier nonlinearity f(u) = max(0, u) ensures that...',
        options: [
          'Rates can be negative',
          'Rates are always zero',
          'Rates stay non-negative',
          'Rates scale quadratically',
        ],
        answerIndex: 2,
        explanation: 'max(0, u) clamps output at zero, matching the non-negative nature of firing rates.',
      },
      {
        prompt: 'Firing rate models are appropriate when...',
        options: [
          'Precise spike timing is required',
          'Population-level averages are enough',
          'Ion channel kinetics are the focus',
          'There is only one neuron under study',
        ],
        answerIndex: 1,
        explanation: 'Rate models focus on smooth averages rather than individual spikes.',
      },
    ],
    xpReward: 22,
    coinReward: 8,
    masteryThreshold: 0.8,
  },
  {
    id: 'C05',
    trackId: 'compneuro',
    moduleId: 'C-rate',
    order: 5,
    title: 'Recurrent networks',
    subtitle: 'When neurons talk back',
    estimatedMinutes: 6,
    difficulty: 'intermediate',
    prerequisites: ['C04', 'B12'],
    explanation:
      'Recurrent networks include feedback connections, so the activity of the network feeds into itself. The state evolves according to \u03c4 dr/dt = \u2212r + f(W r + x), where W is the recurrent weight matrix and x is external input.',
    notation: '\u03c4 dr/dt = \u2212r + f(W r + x)',
    keyTerms: ['recurrent', 'feedback', 'attractor', 'stability'],
    example:
      'Cortical microcircuits are strongly recurrent and can sustain activity after a brief input, as in working memory tasks.',
    intuition: 'Feedback lets the network remember, amplify, and filter.',
    whyItMatters:
      'Most interesting dynamics \u2014 memory, decisions, prediction \u2014 rely on recurrence.',
    questions: [
      {
        prompt: 'What distinguishes a recurrent network from a pure feedforward one?',
        options: [
          'It has more neurons',
          'It has feedback connections',
          'It lacks inputs',
          'It is always linear',
        ],
        answerIndex: 1,
        explanation: 'Recurrent networks feed their own activity back in via W r.',
      },
      {
        prompt: 'Recurrent dynamics can create...',
        options: [
          'Working memory traces',
          'Attractor states',
          'Selective amplification',
          'All of the above',
        ],
        answerIndex: 3,
        explanation: 'Recurrence enables all of these behaviours depending on W.',
      },
      {
        prompt: 'In \u03c4 dr/dt = \u2212r + f(W r + x), the matrix W represents...',
        options: [
          'Only external inputs',
          'Internal recurrent weights',
          'Single-neuron capacitance',
          'Spike thresholds',
        ],
        answerIndex: 1,
        explanation: 'W encodes how internal units influence each other.',
      },
    ],
    xpReward: 26,
    coinReward: 10,
    masteryThreshold: 0.8,
  },
  {
    id: 'C06',
    trackId: 'compneuro',
    moduleId: 'C-rate',
    order: 6,
    title: 'Excitation-inhibition balance',
    subtitle: 'Stability from a delicate tension',
    estimatedMinutes: 5,
    difficulty: 'intermediate',
    prerequisites: ['C05'],
    explanation:
      'In cortex, excitation and inhibition are roughly balanced, producing irregular firing patterns and allowing fast responses. Too much excitation makes activity explode; too much inhibition silences the network.',
    keyTerms: ['E/I balance', 'irregular firing', 'stability'],
    example:
      'Balanced recurrent networks reproduce the highly irregular, Poisson-like spiking seen in real cortical neurons.',
    intuition: 'A neuron in balance is always one nudge away from firing \u2014 fast, sensitive, and never runaway.',
    whyItMatters:
      'Balance explains why cortex can respond quickly while still being stable.',
    questions: [
      {
        prompt: 'E/I balance helps networks...',
        options: [
          'Blow up into runaway activity',
          'Stay silent forever',
          'Respond quickly and remain stable',
          'Discard all external inputs',
        ],
        answerIndex: 2,
        explanation: 'Balance supports quick, informative, and stable dynamics.',
      },
      {
        prompt: 'A classic signature of balanced cortical activity is...',
        options: [
          'Highly regular spiking',
          'Irregular Poisson-like spiking',
          'Silent neurons only',
          'Synchronous bursts always',
        ],
        answerIndex: 1,
        explanation: 'Irregular, Poisson-like firing is a hallmark of balance.',
      },
      {
        prompt: 'If inhibition becomes too weak, the network may...',
        options: [
          'Fire too rapidly and become runaway',
          'Stop firing entirely',
          'Gain new neurons',
          'Lose its connections',
        ],
        answerIndex: 0,
        explanation: 'Without enough braking, excitation self-amplifies.',
      },
    ],
    xpReward: 24,
    coinReward: 9,
    masteryThreshold: 0.8,
  },
  {
    id: 'C07',
    trackId: 'compneuro',
    moduleId: 'C-coding',
    order: 7,
    title: 'Tuning curves',
    subtitle: 'How a neuron prefers a stimulus',
    estimatedMinutes: 5,
    difficulty: 'beginner',
    prerequisites: ['A10', 'B13'],
    explanation:
      'A tuning curve plots a neuron\u2019s mean firing rate as a function of a stimulus feature. Many neurons have a peak at a preferred value and decrease for values away from it, so the curve looks like a hill.',
    notation: 'r(\u03b8) = firing rate as a function of feature \u03b8',
    keyTerms: ['tuning curve', 'preferred stimulus', 'bandwidth'],
    example:
      'V1 neurons have bell-shaped orientation tuning curves centred on their preferred orientation.',
    intuition: 'A tuning curve is a neuron\u2019s favourite flavour, plotted.',
    whyItMatters:
      'Tuning curves are the bridge between stimuli and single-cell codes.',
    questions: [
      {
        prompt: 'A tuning curve plots...',
        options: [
          'Firing rate vs stimulus feature',
          'Voltage vs time',
          'Weight vs neuron index',
          'Random noise',
        ],
        answerIndex: 0,
        explanation: 'It shows how rate depends on a stimulus feature.',
      },
      {
        prompt: 'A peaked (hill-shaped) tuning curve indicates...',
        options: [
          'A preferred stimulus value',
          'Complete lack of selectivity',
          'Only negative responses',
          'Spike precision alone',
        ],
        answerIndex: 0,
        explanation: 'The peak indicates the stimulus value that drives the neuron most.',
      },
      {
        prompt: 'The width (bandwidth) of a tuning curve tells you...',
        options: [
          'How many neurons exist',
          'How selective or broad the neuron is',
          'The time constant',
          'The reset voltage',
        ],
        answerIndex: 1,
        explanation: 'A narrow curve means sharp selectivity; a broad one means coarse tuning.',
      },
    ],
    xpReward: 22,
    coinReward: 8,
    masteryThreshold: 0.8,
  },
  {
    id: 'C08',
    trackId: 'compneuro',
    moduleId: 'C-coding',
    order: 8,
    title: 'Population coding',
    subtitle: 'A team of neurons is smarter than one',
    estimatedMinutes: 5,
    difficulty: 'intermediate',
    prerequisites: ['C07'],
    explanation:
      'Population coding combines the activity of many neurons with different tuning preferences to represent a stimulus more accurately than any single cell could. Because each neuron adds a noisy vote, averaging across the population reduces noise.',
    keyTerms: ['population code', 'tuning', 'noise averaging'],
    example:
      'In motor cortex, population vectors computed from many neurons can accurately predict the direction of an upcoming arm movement.',
    intuition: 'One noisy neuron is a guess. A population is an informed vote.',
    whyItMatters:
      'Modern experimental neuroscience almost always thinks in population-coding terms.',
    questions: [
      {
        prompt: 'Why is a population code more informative than a single neuron?',
        options: [
          'Neurons never have noise',
          'Averaging many noisy tuning curves reduces uncertainty',
          'Populations are always linear',
          'Single neurons cannot respond at all',
        ],
        answerIndex: 1,
        explanation: 'Combining many tuning curves averages out noise and sharpens estimates.',
      },
      {
        prompt: 'The "population vector" approach sums up...',
        options: [
          'Only the firing rate of one neuron',
          'Weighted contributions of many tuned neurons',
          'Membrane time constants',
          'Ion channel densities',
        ],
        answerIndex: 1,
        explanation: 'It is a weighted sum of preferred directions or features across neurons.',
      },
      {
        prompt: 'Population coding shines when...',
        options: [
          'Noise is present and we want robust estimates',
          'Only one stimulus exists',
          'Neurons are silent',
          'Weights are random and unused',
        ],
        answerIndex: 0,
        explanation: 'It is especially valuable under noise.',
      },
    ],
    xpReward: 24,
    coinReward: 9,
    masteryThreshold: 0.8,
  },
  {
    id: 'C09',
    trackId: 'compneuro',
    moduleId: 'C-coding',
    order: 9,
    title: 'Neural decoding',
    subtitle: 'Reading out what neurons are saying',
    estimatedMinutes: 6,
    difficulty: 'intermediate',
    prerequisites: ['C08'],
    explanation:
      'Neural decoding is the task of reconstructing a stimulus or behaviour from neural activity. A decoder takes spikes or rates as input and returns an estimate. It can be as simple as a weighted sum or as complex as a trained neural network.',
    notation: '\u015d = D(r)',
    keyTerms: ['decoder', 'estimate', 'linear readout'],
    example:
      'A linear decoder trained on 500 motor cortex neurons can predict hand velocity in real time for brain\u2013computer interface applications.',
    intuition: 'A decoder is an ear that learns to interpret a chorus of neurons.',
    whyItMatters:
      'Decoding bridges neural activity to behaviour and to practical tools like BCIs.',
    questions: [
      {
        prompt: 'A decoder takes as input...',
        options: ['A stimulus', 'Neural activity', 'Only weights', 'Only time'],
        answerIndex: 1,
        explanation: 'It maps neural activity to an estimate of the variable of interest.',
      },
      {
        prompt: 'A linear decoder computes...',
        options: [
          'A weighted sum of neural responses',
          'A convolution of spikes with itself',
          'A matrix inverse at each spike',
          'Only binary outputs',
        ],
        answerIndex: 0,
        explanation: 'Linear decoders are simple weighted combinations of neural features.',
      },
      {
        prompt: 'Decoding is most useful for...',
        options: [
          'Quantifying how much information activity carries about a variable',
          'Removing noise by guessing',
          'Replacing measured spikes',
          'Generating new stimuli randomly',
        ],
        answerIndex: 0,
        explanation: 'Good decoders set a concrete bound on what information is present.',
      },
    ],
    xpReward: 26,
    coinReward: 10,
    masteryThreshold: 0.8,
  },
  {
    id: 'C10',
    trackId: 'compneuro',
    moduleId: 'C-bayes',
    order: 10,
    title: 'Bayesian inference intuition',
    subtitle: 'Combining prior belief with new evidence',
    estimatedMinutes: 5,
    difficulty: 'intermediate',
    prerequisites: ['B18'],
    explanation:
      'Bayesian inference combines a prior belief with new evidence to form a posterior belief. In symbols: posterior is proportional to likelihood times prior. The brain often behaves as if it combines noisy sensory evidence with prior expectations in roughly this way.',
    notation: 'P(x | data) \u221d P(data | x) \u00d7 P(x)',
    keyTerms: ['prior', 'likelihood', 'posterior'],
    example:
      'When a light source is dim, the brain relies more on prior assumptions and less on the weak visual input \u2014 a Bayesian-flavoured computation.',
    intuition: 'Mix what you expected with what you saw. Trust each in proportion to its reliability.',
    whyItMatters:
      'Many perception and decision models are grounded in Bayesian reasoning.',
    questions: [
      {
        prompt: 'The posterior P(x | data) is proportional to...',
        options: [
          'P(data | x) \u00d7 P(x)',
          'P(data) only',
          'P(x) only',
          'Nothing in particular',
        ],
        answerIndex: 0,
        explanation: 'This is the core form of Bayes\u2019 rule.',
      },
      {
        prompt: 'A strong prior means that...',
        options: [
          'The posterior depends heavily on it',
          'It has no effect',
          'The likelihood is ignored',
          'Data are all noise',
        ],
        answerIndex: 0,
        explanation: 'Strong priors pull the posterior toward their expectations.',
      },
      {
        prompt: 'With very noisy evidence, a Bayesian observer leans...',
        options: [
          'On the likelihood only',
          'On the prior more heavily',
          'On neither',
          'On an unrelated variable',
        ],
        answerIndex: 1,
        explanation: 'Unreliable evidence gives more weight to the prior.',
      },
    ],
    xpReward: 26,
    coinReward: 10,
    masteryThreshold: 0.8,
  },
  {
    id: 'C11',
    trackId: 'compneuro',
    moduleId: 'C-stats',
    order: 11,
    title: 'Correlation and covariance in neural activity',
    subtitle: 'How pairs of neurons move together',
    estimatedMinutes: 5,
    difficulty: 'intermediate',
    prerequisites: ['B18'],
    explanation:
      'Covariance measures how two variables vary together. Correlation is a normalised version in [\u22121, 1]. For pairs of neurons, these metrics capture whether they tend to co-fire or fire independently.',
    notation: 'cov(X, Y) = E[(X \u2212 \u03bc_X)(Y \u2212 \u03bc_Y)]',
    keyTerms: ['covariance', 'correlation', 'co-variability'],
    example:
      'Nearby cortical neurons tuned to similar features often show positive noise correlations, subtly linking their trial-to-trial variability.',
    intuition: 'Correlation is a normalised handshake between two signals.',
    whyItMatters:
      'Pairwise statistics are the simplest honest window into how neurons relate to each other.',
    questions: [
      {
        prompt: 'Correlation values lie in the range...',
        options: ['[0, 1]', '[\u22121, 1]', '[0, \u221e)', '(\u2212\u221e, \u221e)'],
        answerIndex: 1,
        explanation: 'By construction, correlation is normalised to lie between \u22121 and 1.',
      },
      {
        prompt: 'Two independent neurons typically have correlation...',
        options: ['0', '1', '\u22121', '0.5'],
        answerIndex: 0,
        explanation: 'Independent variables have zero correlation.',
      },
      {
        prompt: 'Covariance differs from correlation because...',
        options: [
          'It has no units',
          'It is not normalised',
          'It is always positive',
          'It is always between 0 and 1',
        ],
        answerIndex: 1,
        explanation: 'Covariance depends on the scale of the variables; correlation does not.',
      },
    ],
    xpReward: 24,
    coinReward: 9,
    masteryThreshold: 0.8,
  },
  {
    id: 'C12',
    trackId: 'compneuro',
    moduleId: 'C-stats',
    order: 12,
    title: 'Noise correlations',
    subtitle: 'Trial-to-trial shared wobbles',
    estimatedMinutes: 5,
    difficulty: 'intermediate',
    prerequisites: ['C11'],
    explanation:
      'Noise correlations are the correlations in neural activity across trials when the same stimulus is repeated. They can help or hurt decoding depending on whether the shared variability lines up with the information dimension.',
    keyTerms: ['noise correlation', 'signal correlation', 'information'],
    example:
      'A small positive noise correlation between similarly tuned neurons often reduces the information gain from adding more neurons.',
    intuition: 'If noise is shared, averaging neurons helps less.',
    whyItMatters:
      'Noise correlations determine how population size scales into decoding quality.',
    questions: [
      {
        prompt: 'Noise correlations are measured across...',
        options: [
          'Different stimuli in one trial',
          'Repeated trials of the same stimulus',
          'Different brain regions only',
          'Recordings of a single spike',
        ],
        answerIndex: 1,
        explanation: 'They describe shared variability when the stimulus is fixed.',
      },
      {
        prompt: 'Positive noise correlations between similarly tuned neurons typically...',
        options: [
          'Always increase information',
          'Can reduce the information gained from more neurons',
          'Are identical to signal correlations',
          'Are irrelevant to decoding',
        ],
        answerIndex: 1,
        explanation: 'Shared fluctuations cannot be averaged out, limiting information gains.',
      },
      {
        prompt: 'A zero noise correlation across neurons means...',
        options: [
          'They share all their variability',
          'Their trial-to-trial noise is independent',
          'They are always silent',
          'They have the same tuning',
        ],
        answerIndex: 1,
        explanation: 'Zero correlation means independent trial-to-trial variability.',
      },
    ],
    xpReward: 24,
    coinReward: 9,
    masteryThreshold: 0.8,
  },
  {
    id: 'C13',
    trackId: 'compneuro',
    moduleId: 'C-processes',
    order: 13,
    title: 'Markov processes and state transitions',
    subtitle: 'Memoryless jumps through states',
    estimatedMinutes: 5,
    difficulty: 'intermediate',
    prerequisites: ['B17', 'B18'],
    explanation:
      'A Markov process has the property that the future depends only on the present state, not on the full history. Transition probabilities between states describe how the system evolves. Many neural models (and ion channel kinetics) are treated this way.',
    notation: 'P(x_{t+1} | x_t, x_{t-1}, \u2026) = P(x_{t+1} | x_t)',
    keyTerms: ['Markov', 'transition matrix', 'memorylessness'],
    example:
      'Single ion channel states (closed, open, inactivated) and their transitions are often modelled as a Markov process.',
    intuition: 'If I know where you are right now, the past does not help me predict the next step.',
    whyItMatters:
      'Markov assumptions simplify many models and often fit neural data surprisingly well.',
    questions: [
      {
        prompt: 'The Markov property says that the future depends on...',
        options: [
          'All past states in detail',
          'Only the present state',
          'Only the distant past',
          'A random weight',
        ],
        answerIndex: 1,
        explanation: 'In a Markov process, the present state is a sufficient summary.',
      },
      {
        prompt: 'An ion channel with three states (closed, open, inactivated) can be modelled as...',
        options: [
          'A Markov chain with transition probabilities between states',
          'A deterministic cycle only',
          'A continuous waveform',
          'A vector of rates',
        ],
        answerIndex: 0,
        explanation: 'This is a classic biological application of Markov models.',
      },
      {
        prompt: 'A transition matrix of a Markov chain has rows that...',
        options: [
          'Sum to 1',
          'Sum to 0',
          'Are always identical',
          'Have negative entries',
        ],
        answerIndex: 0,
        explanation: 'Each row is a probability distribution over next states.',
      },
    ],
    xpReward: 24,
    coinReward: 9,
    masteryThreshold: 0.8,
  },
  {
    id: 'C14',
    trackId: 'compneuro',
    moduleId: 'C-processes',
    order: 14,
    title: 'Stochastic spike trains',
    subtitle: 'Spikes as random events over time',
    estimatedMinutes: 5,
    difficulty: 'intermediate',
    prerequisites: ['B19', 'C01'],
    explanation:
      'A spike train can be modelled as a stochastic point process. If spikes are independent with an instantaneous rate \u03bb(t), this is called an inhomogeneous Poisson process. The likelihood of a spike in a tiny window \u0394t is approximately \u03bb(t)\u0394t.',
    notation: 'P(spike in [t, t+\u0394t]) \u2248 \u03bb(t)\u0394t',
    keyTerms: ['point process', 'Poisson', 'rate function'],
    example:
      'Many early retinal models describe ganglion cell firing as a Poisson process with rate driven by a linear filter of the stimulus.',
    intuition: 'Imagine a faucet whose drip rate varies over time. Each drip is a spike.',
    whyItMatters:
      'Stochastic spike models form the backbone of likelihood-based statistical methods in neural data.',
    questions: [
      {
        prompt: 'In an inhomogeneous Poisson process, the instantaneous rate is...',
        options: [
          'Constant over time',
          'A function of time',
          'Always zero',
          'A binary variable',
        ],
        answerIndex: 1,
        explanation: 'Inhomogeneous means the rate varies with time.',
      },
      {
        prompt: 'If \u03bb(t) is large, spikes are...',
        options: [
          'More likely per unit time',
          'Less likely per unit time',
          'Completely suppressed',
          'Always periodic',
        ],
        answerIndex: 0,
        explanation: 'Higher rate means higher probability per small time bin.',
      },
      {
        prompt: 'A Poisson spike model assumes that spikes are...',
        options: [
          'Perfectly periodic',
          'Independent given the rate',
          'Always identical',
          'Self-reinforcing',
        ],
        answerIndex: 1,
        explanation: 'Given the rate, spike events are independent.',
      },
    ],
    xpReward: 24,
    coinReward: 9,
    masteryThreshold: 0.8,
  },
  {
    id: 'C15',
    trackId: 'compneuro',
    moduleId: 'C-plasticity',
    order: 15,
    title: 'Hebbian plasticity',
    subtitle: 'Neurons that fire together, wire together',
    estimatedMinutes: 5,
    difficulty: 'beginner',
    prerequisites: ['A05', 'B11'],
    explanation:
      'Hebbian plasticity increases the strength of a synapse when presynaptic and postsynaptic activity coincide. The classic rule is \u0394w \u221d pre \u00d7 post. While simple, it captures the basic idea behind many learning rules.',
    notation: '\u0394w_{ij} \u221d r_i^post \u00d7 r_j^pre',
    keyTerms: ['Hebbian', 'correlation-based learning', 'synaptic plasticity'],
    example:
      'In simple rate-based models, Hebbian learning can form receptive fields that match the statistics of the input.',
    intuition: 'Synapses that successfully predict activity grow stronger.',
    whyItMatters:
      'Hebbian ideas are the foundation of many biologically inspired learning rules.',
    questions: [
      {
        prompt: 'A classic Hebbian update is...',
        options: [
          '\u0394w \u221d pre \u2212 post',
          '\u0394w \u221d pre \u00d7 post',
          '\u0394w \u221d pre / post',
          '\u0394w = constant',
        ],
        answerIndex: 1,
        explanation: 'It is multiplicative in pre and post activity.',
      },
      {
        prompt: 'Pure Hebbian learning can be unstable because...',
        options: [
          'It never changes weights',
          'It lets weights grow without bound',
          'It always decreases weights',
          'It ignores input',
        ],
        answerIndex: 1,
        explanation: 'Without normalisation, positive correlations keep increasing the weight.',
      },
      {
        prompt: 'Hebbian rules are called "correlation-based" because they update on...',
        options: [
          'The absolute value of the weight',
          'The product of pre and post activity, related to correlation',
          'The random noise in the network',
          'Only the post activity',
        ],
        answerIndex: 1,
        explanation: 'They effectively respond to correlations between pre and post.',
      },
    ],
    xpReward: 22,
    coinReward: 8,
    masteryThreshold: 0.8,
  },
  {
    id: 'C16',
    trackId: 'compneuro',
    moduleId: 'C-plasticity',
    order: 16,
    title: 'Spike-timing-dependent plasticity',
    subtitle: 'Order and timing matter',
    estimatedMinutes: 5,
    difficulty: 'intermediate',
    prerequisites: ['C15'],
    explanation:
      'STDP modifies a synapse based on the precise timing of pre- and postsynaptic spikes. If the presynaptic spike precedes the postsynaptic one within a short window, the synapse tends to strengthen. The reverse order tends to weaken it.',
    keyTerms: ['STDP', 'LTP', 'LTD', 'timing window'],
    example:
      'In hippocampal slices, pairing a presynaptic spike shortly before a postsynaptic one reliably induces long-term potentiation, while the opposite order induces depression.',
    intuition: 'Causes before effects are rewarded. Effects before causes are penalised.',
    whyItMatters:
      'STDP is one of the most experimentally grounded plasticity rules and shapes many biological learning models.',
    questions: [
      {
        prompt: 'STDP depends on...',
        options: [
          'The average firing rate only',
          'The precise relative timing of pre and post spikes',
          'Synaptic colour',
          'The reversal potential of Na+',
        ],
        answerIndex: 1,
        explanation: 'Relative spike timing is the key variable.',
      },
      {
        prompt: 'In classical STDP, pre-before-post pairings typically cause...',
        options: ['LTD', 'No change', 'LTP', 'Spontaneous silence'],
        answerIndex: 2,
        explanation: 'Pre-leads-post causes potentiation within the window.',
      },
      {
        prompt: 'Post-before-pre pairings typically cause...',
        options: ['LTP', 'LTD', 'Synapse removal', 'Receptor explosion'],
        answerIndex: 1,
        explanation: 'Reverse order tends to induce synaptic depression.',
      },
    ],
    xpReward: 24,
    coinReward: 9,
    masteryThreshold: 0.8,
  },
  {
    id: 'C17',
    trackId: 'compneuro',
    moduleId: 'C-plasticity',
    order: 17,
    title: 'Homeostatic plasticity',
    subtitle: 'Keeping activity in a healthy range',
    estimatedMinutes: 4,
    difficulty: 'intermediate',
    prerequisites: ['C15'],
    explanation:
      'Homeostatic plasticity mechanisms adjust synaptic strengths or intrinsic excitability to keep a neuron\u2019s average firing near a target. This prevents pure Hebbian learning from driving activity to zero or to runaway firing.',
    keyTerms: ['homeostasis', 'synaptic scaling', 'target rate'],
    example:
      'When cultured neurons are silenced with a drug, their synapses scale up over hours to compensate and restore average firing.',
    intuition: 'Neurons have a set point and fight to stay near it.',
    whyItMatters:
      'Biologically realistic learning rules combine Hebbian updates with homeostatic stabilisation.',
    questions: [
      {
        prompt: 'Homeostatic plasticity acts to...',
        options: [
          'Amplify runaway activity',
          'Maintain a stable average firing rate',
          'Eliminate all spikes',
          'Randomise weights',
        ],
        answerIndex: 1,
        explanation: 'It pushes activity back toward a target level.',
      },
      {
        prompt: 'If a neuron is chronically silenced, synaptic scaling typically...',
        options: [
          'Decreases synaptic strength',
          'Increases synaptic strength to compensate',
          'Does nothing',
          'Eliminates all synapses',
        ],
        answerIndex: 1,
        explanation: 'Scaling up inputs restores activity toward the target.',
      },
      {
        prompt: 'Combining Hebbian and homeostatic rules helps learning be...',
        options: [
          'Purely unstable',
          'Stable while still able to change',
          'Faster but unreliable',
          'Independent of inputs',
        ],
        answerIndex: 1,
        explanation: 'Homeostasis stabilises what Hebbian dynamics would otherwise blow up.',
      },
    ],
    xpReward: 22,
    coinReward: 8,
    masteryThreshold: 0.8,
  },
  {
    id: 'C18',
    trackId: 'compneuro',
    moduleId: 'C-attractors',
    order: 18,
    title: 'Attractor networks',
    subtitle: 'States that pull nearby activity in',
    estimatedMinutes: 6,
    difficulty: 'intermediate',
    prerequisites: ['C05'],
    explanation:
      'An attractor is a state a dynamical system settles into. Neural attractor networks have special states shaped by the weight matrix so that similar initial activity patterns converge to the nearest attractor.',
    keyTerms: ['attractor', 'basin of attraction', 'fixed point'],
    example:
      'Attractor models are used to explain working memory \u2014 a short stimulus pushes the network into a persistent state it holds after the stimulus ends.',
    intuition: 'Attractors are the grooves the dynamics settle into.',
    whyItMatters:
      'Many cognitive functions \u2014 memory, decisions, categorisation \u2014 are modelled as attractor dynamics.',
    questions: [
      {
        prompt: 'A basin of attraction is the set of initial states that...',
        options: [
          'Diverge to infinity',
          'Settle into a given attractor',
          'Have no dynamics',
          'Are exact attractors themselves',
        ],
        answerIndex: 1,
        explanation: 'It is the region whose trajectories end up at that attractor.',
      },
      {
        prompt: 'Working memory is often modelled as...',
        options: [
          'A linear feedforward network',
          'A network settling into a persistent attractor state',
          'Purely noisy dynamics',
          'A single spike train',
        ],
        answerIndex: 1,
        explanation: 'Attractor dynamics can sustain activity after the input ends.',
      },
      {
        prompt: 'Multiple attractors allow a network to...',
        options: [
          'Forget everything',
          'Store multiple discrete memories',
          'Collapse onto one state',
          'Become purely random',
        ],
        answerIndex: 1,
        explanation: 'Each attractor can represent a distinct stable memory.',
      },
    ],
    xpReward: 26,
    coinReward: 10,
    masteryThreshold: 0.8,
  },
  {
    id: 'C19',
    trackId: 'compneuro',
    moduleId: 'C-attractors',
    order: 19,
    title: 'Hopfield networks',
    subtitle: 'A classic memory-as-attractors model',
    estimatedMinutes: 6,
    difficulty: 'intermediate',
    prerequisites: ['C18'],
    explanation:
      'A Hopfield network is a recurrent network with symmetric weights and binary units. It stores patterns as attractors. Given a corrupted version of a stored pattern, the dynamics converge to the closest stored one \u2014 a form of content-addressable memory.',
    keyTerms: ['Hopfield', 'energy', 'associative memory'],
    example:
      'Presented with a noisy version of a learned pattern, a Hopfield network settles onto the clean stored pattern.',
    intuition: 'The network "completes" partial memories by rolling downhill in an energy landscape.',
    whyItMatters:
      'It is a foundational model of associative memory and inspired many modern energy-based models.',
    questions: [
      {
        prompt: 'Hopfield networks are typically described as...',
        options: [
          'Feedforward networks',
          'Recurrent networks with symmetric weights',
          'Spiking networks with random weights',
          'Single neurons',
        ],
        answerIndex: 1,
        explanation: 'They are symmetric recurrent networks.',
      },
      {
        prompt: 'Hopfield dynamics can be interpreted as...',
        options: [
          'Descending an energy landscape',
          'Maximising random walks',
          'Resetting all neurons to zero',
          'Randomising weights',
        ],
        answerIndex: 0,
        explanation: 'The dynamics minimise an energy function.',
      },
      {
        prompt: 'Content-addressable memory means...',
        options: [
          'You retrieve a memory by its index only',
          'You retrieve a memory by providing part of the content',
          'You cannot retrieve anything',
          'You retrieve only one fixed memory',
        ],
        answerIndex: 1,
        explanation: 'Partial cues can bring back the full pattern.',
      },
    ],
    xpReward: 26,
    coinReward: 10,
    masteryThreshold: 0.8,
  },
  {
    id: 'C20',
    trackId: 'compneuro',
    moduleId: 'C-attractors',
    order: 20,
    title: 'Continuous attractors and ring models',
    subtitle: 'A line or ring of stable states',
    estimatedMinutes: 6,
    difficulty: 'intermediate',
    prerequisites: ['C19'],
    explanation:
      'A continuous attractor network has a family of stable states arranged along a continuous manifold, such as a ring. Small nudges move the activity along the ring rather than away from it. Classic models of head direction and spatial orientation use this structure.',
    keyTerms: ['ring model', 'manifold', 'head direction'],
    example:
      'Head direction cells in mammals are thought to form a ring attractor: their bump of activity slides around the ring as the animal turns.',
    intuition: 'Instead of point attractors, imagine a valley that forms a closed loop.',
    whyItMatters:
      'Continuous attractors show how networks can represent continuous variables through stable activity patterns.',
    questions: [
      {
        prompt: 'A ring attractor has stable states arranged along...',
        options: [
          'A single point',
          'A circle',
          'A three-dimensional cube',
          'Nothing',
        ],
        answerIndex: 1,
        explanation: 'The manifold of stable states is a ring.',
      },
      {
        prompt: 'Head direction cells are often modelled as...',
        options: [
          'Point attractors',
          'A continuous ring attractor',
          'Purely linear filters',
          'Binary memory units',
        ],
        answerIndex: 1,
        explanation: 'Their bump-like activity around a ring matches ring attractor dynamics.',
      },
      {
        prompt: 'Continuous attractors can represent...',
        options: [
          'Only discrete labels',
          'Continuous variables like angles or positions',
          'Only static images',
          'Only binary decisions',
        ],
        answerIndex: 1,
        explanation: 'They are well suited to continuously varying quantities.',
      },
    ],
    xpReward: 26,
    coinReward: 10,
    masteryThreshold: 0.8,
  },
  {
    id: 'C21',
    trackId: 'compneuro',
    moduleId: 'C-rhythms',
    order: 21,
    title: 'Oscillations and synchrony',
    subtitle: 'Rhythms that organise computation',
    estimatedMinutes: 5,
    difficulty: 'intermediate',
    prerequisites: ['A19'],
    explanation:
      'Neural oscillations are rhythmic fluctuations of population activity. They can synchronise distant neurons, organise information flow, and mark different brain states. Different frequency bands (delta, theta, alpha, beta, gamma) are associated with different functions.',
    keyTerms: ['oscillation', 'phase', 'synchrony', 'frequency band'],
    example:
      'Theta rhythms in hippocampus help organise place cell firing in time and are linked to memory encoding.',
    intuition: 'Rhythms are like metronomes that make different parts of the orchestra play in time.',
    whyItMatters:
      'Oscillations bridge cellular activity and large-scale brain signals like LFPs and EEG.',
    questions: [
      {
        prompt: 'Neural synchrony refers to...',
        options: [
          'Coordinated firing across neurons',
          'Random firing only',
          'Complete silence',
          'Identical membrane potentials forever',
        ],
        answerIndex: 0,
        explanation: 'Synchrony means activity is temporally coordinated.',
      },
      {
        prompt: 'Theta rhythms in the hippocampus are linked to...',
        options: [
          'Deep unconsciousness',
          'Memory encoding and navigation',
          'Static images only',
          'Muscle force alone',
        ],
        answerIndex: 1,
        explanation: 'Theta oscillations are closely tied to memory and exploration.',
      },
      {
        prompt: 'Phase tells you...',
        options: [
          'The absolute amplitude of an oscillation',
          'The position within a cycle of the oscillation',
          'Whether the wave exists',
          'The average rate',
        ],
        answerIndex: 1,
        explanation: 'Phase is the timing position within an oscillation cycle.',
      },
    ],
    xpReward: 24,
    coinReward: 9,
    masteryThreshold: 0.8,
  },
  {
    id: 'C22',
    trackId: 'compneuro',
    moduleId: 'C-rhythms',
    order: 22,
    title: 'Fourier intuition and power spectra',
    subtitle: 'Any wiggle is a sum of sines',
    estimatedMinutes: 6,
    difficulty: 'intermediate',
    prerequisites: ['C21'],
    explanation:
      'Any reasonable time signal can be decomposed into a sum of sine waves with different frequencies and amplitudes. The power spectrum shows how much energy sits in each frequency. In neural data, spectra reveal dominant rhythms and noise structure.',
    keyTerms: ['Fourier transform', 'frequency', 'power spectrum'],
    example:
      'An LFP recording during waking behaviour often shows strong gamma-band power, while deep sleep is dominated by slow oscillations.',
    intuition: 'The Fourier transform is a prism that splits a signal into its colours.',
    whyItMatters:
      'Spectral analysis is standard in EEG, LFP, and calcium signal processing.',
    questions: [
      {
        prompt: 'The power spectrum of a signal shows...',
        options: [
          'Energy as a function of frequency',
          'Frequency as a function of voltage',
          'Spikes as a function of time',
          'Colour of the signal',
        ],
        answerIndex: 0,
        explanation: 'It describes how power is distributed across frequency.',
      },
      {
        prompt: 'Fourier analysis tells us that most signals can be written as...',
        options: [
          'A product of sines',
          'A sum of sines with different frequencies',
          'A random number',
          'A single impulse',
        ],
        answerIndex: 1,
        explanation: 'A signal decomposes into a sum of sinusoids.',
      },
      {
        prompt: 'Strong power at a specific frequency indicates...',
        options: [
          'Noise only',
          'A dominant rhythmic component at that frequency',
          'A DC offset',
          'No rhythm',
        ],
        answerIndex: 1,
        explanation: 'A peak in the spectrum reveals a rhythmic component.',
      },
    ],
    xpReward: 26,
    coinReward: 10,
    masteryThreshold: 0.8,
  },
  {
    id: 'C23',
    trackId: 'compneuro',
    moduleId: 'C-filters',
    order: 23,
    title: 'Filtering and convolution',
    subtitle: 'Smoothing and sharpening signals',
    estimatedMinutes: 6,
    difficulty: 'intermediate',
    prerequisites: ['C22'],
    explanation:
      'Convolution slides a filter (a short signal) across a longer one and computes local weighted sums. Low-pass filters smooth; high-pass filters emphasise fast changes; a linear receptive field acts like a filter applied to the stimulus.',
    notation: '(y = x * h),  y[n] = \u03a3_k x[k] h[n-k]',
    keyTerms: ['convolution', 'filter', 'kernel'],
    example:
      'Retinal ganglion cells approximate convolving the visual stimulus with a centre-surround filter before applying a nonlinearity.',
    intuition: 'A filter is a recipe for "how to look" at each moment of the signal.',
    whyItMatters:
      'Convolution underlies linear receptive fields, spike-triggered averages, and convolutional neural networks.',
    questions: [
      {
        prompt: 'Low-pass filtering a signal...',
        options: [
          'Removes slow components',
          'Smooths out fast fluctuations',
          'Inverts the signal',
          'Cancels the DC component',
        ],
        answerIndex: 1,
        explanation: 'Low-pass keeps slow components and removes fast ones.',
      },
      {
        prompt: 'Convolving a stimulus with a neuron\u2019s linear receptive field gives...',
        options: [
          'A prediction of its linear response over time',
          'A random noise signal',
          'The ion channel density',
          'A single scalar',
        ],
        answerIndex: 0,
        explanation: 'It is the first stage of many linear\u2013nonlinear models.',
      },
      {
        prompt: 'In y = x * h, h is called the...',
        options: ['Signal', 'Filter or kernel', 'Threshold', 'Time constant'],
        answerIndex: 1,
        explanation: 'h is the filter kernel being convolved against x.',
      },
    ],
    xpReward: 26,
    coinReward: 10,
    masteryThreshold: 0.8,
  },
  {
    id: 'C24',
    trackId: 'compneuro',
    moduleId: 'C-glms',
    order: 24,
    title: 'Generalized linear models for spikes',
    subtitle: 'A practical bridge to real neural data',
    estimatedMinutes: 6,
    difficulty: 'advanced',
    prerequisites: ['C14', 'C23'],
    explanation:
      'A generalized linear model for spikes combines a linear filter on the stimulus with an exponential nonlinearity and a Poisson spike process. It yields a tractable likelihood you can fit to real neural data to estimate stimulus sensitivity and history effects.',
    notation: 'log \u03bb(t) = k \u00b7 x(t) + history + bias',
    keyTerms: ['GLM', 'linear filter', 'Poisson likelihood'],
    example:
      'GLMs are widely used to characterise retinal ganglion cells and other visual neurons from recorded data.',
    intuition: 'Take a weighted sum of recent inputs, exponentiate, and use it as a spike rate.',
    whyItMatters:
      'GLMs are the workhorse statistical tool for modelling real neural firing.',
    questions: [
      {
        prompt: 'In a GLM for spikes, the nonlinearity is typically...',
        options: ['Linear', 'Exponential', 'Constant', 'Absent'],
        answerIndex: 1,
        explanation: 'The log-link (exponential inverse) keeps rates positive and likelihood tractable.',
      },
      {
        prompt: 'The spike emission process in a classic GLM is...',
        options: ['Deterministic', 'Poisson', 'Bernoulli only for single bins', 'Gaussian'],
        answerIndex: 1,
        explanation: 'Spikes are modelled as a (possibly conditional) Poisson process.',
      },
      {
        prompt: 'GLMs allow you to include history dependence via...',
        options: [
          'A spike-history filter',
          'A change in the optic nerve',
          'A new set of neurons',
          'A different neurotransmitter',
        ],
        answerIndex: 0,
        explanation: 'History filters capture refractory and burst effects.',
      },
    ],
    xpReward: 28,
    coinReward: 11,
    masteryThreshold: 0.8,
  },
  {
    id: 'C25',
    trackId: 'compneuro',
    moduleId: 'C-dimred',
    order: 25,
    title: 'PCA and dimensionality reduction',
    subtitle: 'Finding the directions that matter',
    estimatedMinutes: 6,
    difficulty: 'intermediate',
    prerequisites: ['B12', 'C11'],
    explanation:
      'Principal component analysis finds directions of maximum variance in high-dimensional data. The first few components often capture most of the structure. For neural data, PCA can reveal low-dimensional patterns that many neurons share.',
    keyTerms: ['PCA', 'variance', 'latent dimension'],
    example:
      'In motor cortex, the activity of thousands of neurons during a reach often lives in a low-dimensional subspace revealed by PCA.',
    intuition: 'Many neurons often move together. PCA finds the directions they move along.',
    whyItMatters:
      'Dimensionality reduction is the starting point of most modern analyses of population data.',
    questions: [
      {
        prompt: 'The first principal component is the direction of...',
        options: [
          'Minimum variance',
          'Maximum variance',
          'Highest mean',
          'Lowest mean',
        ],
        answerIndex: 1,
        explanation: 'PCA maximises variance along the first component.',
      },
      {
        prompt: 'PCA is most useful when data...',
        options: [
          'Has no structure',
          'Has a low-dimensional structure embedded in a high-dimensional space',
          'Is binary only',
          'Has only one sample',
        ],
        answerIndex: 1,
        explanation: 'It uncovers the dominant low-dimensional subspace.',
      },
      {
        prompt: 'Applying PCA to N-neuron recordings often reveals...',
        options: [
          'That activity is essentially N-dimensional',
          'That a few components capture most of the variance',
          'That spikes disappear',
          'That neurons are unrelated',
        ],
        answerIndex: 1,
        explanation: 'Low-dimensional structure is common in population data.',
      },
    ],
    xpReward: 26,
    coinReward: 10,
    masteryThreshold: 0.8,
  },
  {
    id: 'C26',
    trackId: 'compneuro',
    moduleId: 'C-dimred',
    order: 26,
    title: 'Neural manifolds and latent dynamics',
    subtitle: 'Population activity lives on a surface',
    estimatedMinutes: 6,
    difficulty: 'advanced',
    prerequisites: ['C25'],
    explanation:
      'Recordings from many neurons often reveal that activity stays close to a low-dimensional surface, or manifold, inside the full firing-rate space. Dynamics along this manifold can be described by a small number of latent variables.',
    keyTerms: ['neural manifold', 'latent dynamics', 'subspace'],
    example:
      'During reaching, motor cortex population activity traces smooth curves in a handful of dimensions that correspond to movement preparation and execution.',
    intuition: 'The brain uses a high-dimensional substrate to move along a surprisingly low-dimensional path.',
    whyItMatters:
      'Manifold ideas are central to modern theoretical and experimental views of population coding.',
    questions: [
      {
        prompt: 'A neural manifold is...',
        options: [
          'A single point in firing-rate space',
          'A low-dimensional surface where population activity tends to live',
          'The skull',
          'A synaptic weight matrix',
        ],
        answerIndex: 1,
        explanation: 'It is a low-dimensional surface inside the high-dimensional space of firing rates.',
      },
      {
        prompt: 'Latent dynamics describe...',
        options: [
          'Hidden low-dimensional variables driving population activity',
          'A list of neurons that were recorded',
          'Static receptive fields',
          'A single spike',
        ],
        answerIndex: 0,
        explanation: 'They are the few variables whose evolution explains most of the activity.',
      },
      {
        prompt: 'Manifold analyses often follow...',
        options: [
          'No dimensionality reduction',
          'Some form of dimensionality reduction like PCA',
          'Only ion channel kinetics',
          'Only single-cell ephys',
        ],
        answerIndex: 1,
        explanation: 'They usually build on dimensionality reduction methods.',
      },
    ],
    xpReward: 28,
    coinReward: 11,
    masteryThreshold: 0.8,
  },
  {
    id: 'C27',
    trackId: 'compneuro',
    moduleId: 'C-rl',
    order: 27,
    title: 'Reinforcement learning and dopamine prediction error',
    subtitle: 'Learning from better-than-expected outcomes',
    estimatedMinutes: 6,
    difficulty: 'intermediate',
    prerequisites: ['A07'],
    explanation:
      'Temporal-difference reinforcement learning updates a value estimate using the error between expected and actual reward. Dopamine neurons in the midbrain carry a signal closely resembling this prediction error, firing more when reward is better than expected and less when it is worse.',
    notation: '\u03b4 = r + \u03b3 V(s\u2032) \u2212 V(s)',
    keyTerms: ['TD learning', 'prediction error', 'dopamine', 'value'],
    example:
      'A thirsty rat learning which lever yields juice shows dopamine bursts initially at reward, then gradually shifting earlier to the cue predicting it.',
    intuition: 'Dopamine is the "surprise of getting something better" signal.',
    whyItMatters:
      'RL bridges neuroscience and machine learning with a shared formal framework.',
    questions: [
      {
        prompt: 'The TD error \u03b4 is positive when...',
        options: [
          'Reward was worse than expected',
          'Reward was as expected',
          'Reward was better than expected',
          'No reward existed',
        ],
        answerIndex: 2,
        explanation: 'A positive \u03b4 reflects a positive surprise.',
      },
      {
        prompt: 'Dopamine neurons in the midbrain are thought to carry a signal similar to...',
        options: [
          'Value alone',
          'Reward prediction error',
          'Random noise',
          'Absolute reward magnitude only',
        ],
        answerIndex: 1,
        explanation: 'Their phasic firing closely matches reward prediction errors.',
      },
      {
        prompt: 'Over training, dopamine responses often shift...',
        options: [
          'From reward delivery to the cue predicting it',
          'From cue to nothing',
          'From stimulus to unrelated events',
          'They do not shift',
        ],
        answerIndex: 0,
        explanation: 'As cues become predictive, dopamine responses move to them.',
      },
    ],
    xpReward: 28,
    coinReward: 11,
    masteryThreshold: 0.8,
  },
  {
    id: 'C28',
    trackId: 'compneuro',
    moduleId: 'C-predictive',
    order: 28,
    title: 'Predictive coding',
    subtitle: 'The brain as a prediction machine',
    estimatedMinutes: 6,
    difficulty: 'advanced',
    prerequisites: ['C10'],
    explanation:
      'Predictive coding proposes that the brain continuously generates predictions about sensory input and only propagates the errors \u2014 the differences between prediction and input \u2014 up to higher areas. Feedback connections carry predictions; feedforward connections carry prediction errors.',
    keyTerms: ['prediction', 'error unit', 'feedback', 'hierarchy'],
    example:
      'In models of visual cortex, higher areas predict what lower areas should see; the lower areas pass up only what is surprising.',
    intuition: 'The brain sees what it expects, and notices what it did not.',
    whyItMatters:
      'Predictive coding is a leading theoretical framework for cortical function.',
    questions: [
      {
        prompt: 'In predictive coding, feedforward signals primarily carry...',
        options: [
          'Full stimuli',
          'Prediction errors',
          'Random noise',
          'Motor commands',
        ],
        answerIndex: 1,
        explanation: 'Errors, not raw signals, travel up the hierarchy.',
      },
      {
        prompt: 'Feedback connections in predictive coding carry...',
        options: [
          'Predictions from higher areas',
          'Only muscle commands',
          'Nothing useful',
          'Fresh sensory input only',
        ],
        answerIndex: 0,
        explanation: 'Higher areas project predictions back down the hierarchy.',
      },
      {
        prompt: 'Predictive coding fits well with brains that...',
        options: [
          'Have purely feedforward wiring',
          'Combine feedforward and feedback pathways in a hierarchy',
          'Lack recurrent dynamics',
          'Ignore context',
        ],
        answerIndex: 1,
        explanation: 'It relies on strong feedback connections in a hierarchical network.',
      },
    ],
    xpReward: 28,
    coinReward: 11,
    masteryThreshold: 0.8,
  },
  {
    id: 'C29',
    trackId: 'compneuro',
    moduleId: 'C-efficient',
    order: 29,
    title: 'Efficient coding and normalization',
    subtitle: 'Getting the most out of limited spikes',
    estimatedMinutes: 6,
    difficulty: 'advanced',
    prerequisites: ['C08', 'C22'],
    explanation:
      'Efficient coding theories propose that neural responses are shaped to represent natural signals using as few spikes as possible. Divisive normalization is a canonical operation where each neuron\u2019s response is divided by the summed activity of a local pool, decorrelating responses and improving efficiency.',
    keyTerms: ['efficient coding', 'divisive normalization', 'decorrelation'],
    example:
      'Normalization models account for how V1 neurons suppress their responses when multiple stimuli appear in their receptive field.',
    intuition: 'Dividing by the neighbourhood makes each neuron say something new, not something shared.',
    whyItMatters:
      'Normalization is a canonical cortical computation appearing across many modalities.',
    questions: [
      {
        prompt: 'Efficient coding suggests that neural responses are shaped to...',
        options: [
          'Waste energy',
          'Represent natural signals with few spikes',
          'Ignore all stimuli',
          'Maximise correlations between neurons',
        ],
        answerIndex: 1,
        explanation: 'It predicts that the brain is tuned to the statistics of natural signals.',
      },
      {
        prompt: 'Divisive normalization divides a neuron\u2019s response by...',
        options: [
          'Its own firing rate only',
          'The pooled activity of nearby neurons',
          'The pressure of CSF',
          'A fixed constant set at birth',
        ],
        answerIndex: 1,
        explanation: 'The denominator is usually a sum over a local population.',
      },
      {
        prompt: 'Normalization tends to make responses...',
        options: [
          'More correlated',
          'More decorrelated',
          'Purely random',
          'Exactly zero',
        ],
        answerIndex: 1,
        explanation: 'Sharing a common denominator tends to decorrelate responses.',
      },
    ],
    xpReward: 28,
    coinReward: 11,
    masteryThreshold: 0.8,
  },
  {
    id: 'C30',
    trackId: 'compneuro',
    moduleId: 'C-bci',
    order: 30,
    title: 'Brain-computer interfaces and neural decoding systems',
    subtitle: 'From spikes to actions in the real world',
    estimatedMinutes: 6,
    difficulty: 'advanced',
    prerequisites: ['C09', 'C25'],
    explanation:
      'A brain-computer interface reads neural activity and converts it into commands for external devices. Modern BCIs record from hundreds of neurons, decode intended movement or speech, and feed that output to prosthetics, cursors, or spellers in real time.',
    keyTerms: ['BCI', 'decoder', 'prosthetic', 'closed loop'],
    example:
      'A person with paralysis can move a robotic arm using motor cortex signals decoded by a real-time linear model.',
    intuition: 'A good BCI is a very fast, very targeted decoder with a closed feedback loop.',
    whyItMatters:
      'BCIs turn the theoretical study of neural codes into tools that can transform lives.',
    questions: [
      {
        prompt: 'A brain-computer interface converts...',
        options: [
          'External commands into neural spikes only',
          'Neural activity into commands for external devices',
          'Muscles into wires',
          'Colours into numbers only',
        ],
        answerIndex: 1,
        explanation: 'The essential job of a BCI is to read neural signals and produce outputs.',
      },
      {
        prompt: 'A "closed-loop" BCI means that...',
        options: [
          'The user gets real-time feedback and can adapt',
          'There is no feedback at all',
          'Everything is pre-recorded',
          'Only stimulation is possible',
        ],
        answerIndex: 0,
        explanation: 'Closed loops allow learning and adaptation on both sides.',
      },
      {
        prompt: 'Reliable BCIs tend to combine...',
        options: [
          'No math',
          'Signal processing, decoding, and careful interface design',
          'Only electrodes',
          'Only electrical stimulation',
        ],
        answerIndex: 1,
        explanation: 'A working BCI requires the full pipeline, not one trick.',
      },
    ],
    xpReward: 30,
    coinReward: 12,
    masteryThreshold: 0.8,
  },
];
