import { Lesson } from './types';

/**
 * Track E — AI for Neuroscience. 30 lessons on how modern AI is used to
 * record, decode, model, and treat the brain. Progressively unlocked by
 * prerequisites within the track plus a foothold in AI Basics and
 * Neuroscience Basics.
 */
export const trackELessons: Lesson[] = [
  {
    id: 'E01',
    trackId: 'aineuro',
    moduleId: 'E-intro',
    order: 1,
    title: 'Why AI for the brain?',
    subtitle: 'A natural meeting of two fields',
    estimatedMinutes: 5,
    difficulty: 'beginner',
    prerequisites: [],
    explanation:
      'Modern neuroscience produces enormous, high-dimensional data — images, spike trains, behaviour videos — that are too rich for hand-crafted analysis alone. AI provides scalable tools to find patterns, decode signals, and generate hypotheses about the brain.',
    keyTerms: ['NeuroAI', 'big data', 'pattern discovery', 'decoding'],
    example:
      'A single two-photon imaging session can yield hundreds of GB of data; ML pipelines extract neuron traces and behaviour-relevant signals at scale.',
    intuition: 'Brains are noisy and high-dimensional; AI is built for that.',
    whyItMatters:
      'The fields are converging: AI gives neuroscience tools, and neuroscience inspires AI architectures.',
    questions: [
      {
        prompt: 'A key reason to use AI in neuroscience is that data sets are...',
        options: ['Tiny and trivial', 'Large and high-dimensional', 'Always perfectly labelled', 'Noise-free'],
        answerIndex: 1,
        explanation: 'AI shines on big, noisy, high-dimensional data.',
      },
      {
        prompt: 'NeuroAI as a field studies...',
        options: [
          'Only AI on tabular data',
          'The two-way exchange between AI and neuroscience',
          'Only LLMs',
          'Only fMRI',
        ],
        answerIndex: 1,
        explanation: 'NeuroAI sits at the bridge between the two fields.',
      },
      {
        prompt: 'Hand-crafted analysis usually fails on modern brain data because...',
        options: [
          'It is too detailed',
          'It cannot scale to hundreds of GB and thousands of neurons',
          'It always overfits',
          'It is illegal',
        ],
        answerIndex: 1,
        explanation: 'Volume and dimensionality outpace manual analysis.',
      },
    ],
    xpReward: 16,
    coinReward: 6,
    masteryThreshold: 0.8,
  },
  {
    id: 'E02',
    trackId: 'aineuro',
    moduleId: 'E-intro',
    order: 2,
    title: 'Common neuroscience datasets',
    subtitle: 'What the brain looks like as data',
    estimatedMinutes: 5,
    difficulty: 'beginner',
    prerequisites: ['E01'],
    explanation:
      'Neuroscience data comes in many flavours: extracellular spikes from probes, calcium-imaging movies, fMRI volumes, EEG/MEG traces, behaviour videos, and connectomics. Each type imposes different statistical and modelling needs.',
    keyTerms: ['spikes', 'calcium imaging', 'fMRI', 'EEG'],
    example:
      'Neuropixels probes can record from thousands of neurons simultaneously, producing terabyte-scale recordings.',
    intuition: 'The data shape (time, space, modality) decides which AI tools fit.',
    whyItMatters:
      'Choosing the right model and pipeline starts from understanding the data type.',
    questions: [
      {
        prompt: 'Calcium imaging produces...',
        options: ['Discrete spikes directly', 'Slow fluorescence movies that proxy spiking', 'Only fMRI volumes', 'Audio'],
        answerIndex: 1,
        explanation: 'Calcium signals are slow optical proxies for neural activity.',
      },
      {
        prompt: 'fMRI measures...',
        options: ['Single spikes', 'Blood-oxygen-level-dependent signal across the brain', 'EEG', 'Behaviour'],
        answerIndex: 1,
        explanation: 'BOLD signals reflect haemodynamics correlated with neural activity.',
      },
      {
        prompt: 'A practical reason data type matters is that it...',
        options: [
          'Picks the colour of the plot',
          'Determines preprocessing, modelling, and interpretation',
          'Has no effect',
          'Decides funding',
        ],
        answerIndex: 1,
        explanation: 'Spikes vs voxels need different pipelines.',
      },
    ],
    xpReward: 18,
    coinReward: 6,
    masteryThreshold: 0.8,
  },
  {
    id: 'E03',
    trackId: 'aineuro',
    moduleId: 'E-electro',
    order: 3,
    title: 'Spike sorting with machine learning',
    subtitle: 'From raw voltage to single neurons',
    estimatedMinutes: 5,
    difficulty: 'beginner',
    prerequisites: ['E02'],
    explanation:
      'Extracellular recordings pick up voltages from many nearby neurons. Spike sorting separates these into spike trains for individual cells, using clustering, template matching, and increasingly deep models that handle drift and dense probe geometry.',
    keyTerms: ['spike sorting', 'clustering', 'drift', 'Neuropixels'],
    example:
      'Modern tools like Kilosort use GPU-accelerated template matching across hundreds of channels to sort thousands of units.',
    intuition: 'Listen to a crowd and reconstruct each speaker’s voice.',
    whyItMatters:
      'Reliable single-unit data is the foundation for almost every downstream analysis.',
    questions: [
      {
        prompt: 'Spike sorting separates a signal from many neurons into...',
        options: [
          'A single average waveform',
          'Per-neuron spike trains',
          'Random noise',
          'Only LFP',
        ],
        answerIndex: 1,
        explanation: 'Sorting recovers individual units.',
      },
      {
        prompt: 'A challenge that modern sorters address is...',
        options: ['Probe drift over time', 'Lack of any signal', 'Always trivial recordings', 'Only one channel'],
        answerIndex: 0,
        explanation: 'Tissue movement makes waveforms drift across channels.',
      },
      {
        prompt: 'Template matching assumes that each neuron has a...',
        options: ['Random shape', 'Reasonably stable waveform across spikes', 'No waveform', 'Identical waveform to every other'],
        answerIndex: 1,
        explanation: 'Stable templates allow matching against incoming voltage traces.',
      },
    ],
    xpReward: 20,
    coinReward: 7,
    masteryThreshold: 0.8,
  },
  {
    id: 'E04',
    trackId: 'aineuro',
    moduleId: 'E-imaging',
    order: 4,
    title: 'Two-photon imaging and segmentation',
    subtitle: 'Finding neurons in fluorescence movies',
    estimatedMinutes: 5,
    difficulty: 'beginner',
    prerequisites: ['E02'],
    explanation:
      'Two-photon calcium imaging records fluorescence movies of many neurons. AI pipelines correct motion, segment regions of interest, and extract per-cell traces. Convolutional networks and U-Net-style architectures dominate the segmentation step.',
    keyTerms: ['two-photon', 'ROI', 'segmentation', 'U-Net'],
    example:
      'Suite2p and CellPose-style tools rely on learned segmentations to extract thousands of neurons per session.',
    intuition: 'Find every glowing dot, draw its outline, and track it through time.',
    whyItMatters:
      'Without good cell segmentation, downstream science is built on bad signals.',
    questions: [
      {
        prompt: 'Segmentation in calcium imaging finds...',
        options: ['Words in a text', 'Cell boundaries in fluorescence movies', 'Only motion vectors', 'Audio peaks'],
        answerIndex: 1,
        explanation: 'It outlines cells so their traces can be extracted.',
      },
      {
        prompt: 'A common architecture for biomedical segmentation is...',
        options: ['LSTM', 'U-Net', 'Random forest only', 'KNN'],
        answerIndex: 1,
        explanation: 'U-Net’s encoder-decoder with skip connections is a standard.',
      },
      {
        prompt: 'Motion correction is needed because...',
        options: [
          'Brains move during recording',
          'There is no motion ever',
          'Probes always stay still',
          'Calcium does not exist',
        ],
        answerIndex: 0,
        explanation: 'Motion shifts where each cell appears in the frame.',
      },
    ],
    xpReward: 20,
    coinReward: 7,
    masteryThreshold: 0.8,
  },
  {
    id: 'E05',
    trackId: 'aineuro',
    moduleId: 'E-imaging',
    order: 5,
    title: 'Connectomics with computer vision',
    subtitle: 'Tracing wires in electron microscopy',
    estimatedMinutes: 5,
    difficulty: 'intermediate',
    prerequisites: ['E04'],
    explanation:
      'Connectomics aims to reconstruct neural wiring from huge electron microscopy volumes. Deep convolutional models segment cell membranes, label processes, and detect synapses across petabyte-scale datasets that no human team could trace by hand.',
    keyTerms: ['connectome', 'electron microscopy', '3D segmentation', 'synapse detection'],
    example:
      'The Drosophila brain connectome was reconstructed using ML segmentation across enormous EM stacks.',
    intuition: 'Every wire of the brain, drawn by a network.',
    whyItMatters:
      'Connectomes turn anatomy into circuits we can simulate, analyse, and compare across species.',
    questions: [
      {
        prompt: 'Connectomics relies heavily on...',
        options: ['No machine learning', 'Deep models for 3D segmentation', 'Manual tracing only', 'Random labelling'],
        answerIndex: 1,
        explanation: 'EM volumes are too large for purely manual tracing.',
      },
      {
        prompt: 'A core ML task in connectomics is...',
        options: ['Audio classification', 'Cell membrane and process segmentation', 'Stock prediction', 'Sentiment analysis'],
        answerIndex: 1,
        explanation: 'Segmenting membranes is what defines neurons in EM.',
      },
      {
        prompt: 'A connectome is most directly useful for...',
        options: [
          'Mapping the wiring diagram of a circuit',
          'Measuring blood flow',
          'Sequencing DNA',
          'Imaging skin',
        ],
        answerIndex: 0,
        explanation: 'It is a wiring diagram of neurons and synapses.',
      },
    ],
    xpReward: 22,
    coinReward: 8,
    masteryThreshold: 0.8,
  },
  {
    id: 'E06',
    trackId: 'aineuro',
    moduleId: 'E-imaging',
    order: 6,
    title: 'Deep learning for fMRI',
    subtitle: 'Voxels in, predictions out',
    estimatedMinutes: 5,
    difficulty: 'intermediate',
    prerequisites: ['E02'],
    explanation:
      'Deep learning is used on fMRI for tasks like decoding stimulus categories from BOLD activity, predicting clinical labels, and discovering brain networks. Models must handle small subject counts and variable anatomy across people.',
    keyTerms: ['BOLD', 'voxel', 'decoding', 'fMRI'],
    example:
      'Reconstructions of seen images from fMRI activity now use diffusion-based decoders aligned to learned visual features.',
    intuition: 'fMRI is small-data, big-voxel — favour pretrained features and careful evaluation.',
    whyItMatters:
      'fMRI is one of the main windows into human cognition and clinical brain function.',
    questions: [
      {
        prompt: 'A typical challenge with fMRI for ML is...',
        options: [
          'Too many subjects per study',
          'Few subjects and noisy, high-dimensional voxels',
          'Perfect labels',
          'No preprocessing',
        ],
        answerIndex: 1,
        explanation: 'Subject counts are usually small relative to voxel counts.',
      },
      {
        prompt: 'BOLD-based decoding aims to...',
        options: [
          'Predict mental states or stimuli from voxel activity',
          'Generate audio from EEG',
          'Train spike sorters',
          'Replace fMRI hardware',
        ],
        answerIndex: 0,
        explanation: 'Decoding maps brain activity back to mental content.',
      },
      {
        prompt: 'Diffusion-based image reconstruction from fMRI typically requires...',
        options: [
          'Only one fMRI volume',
          'Aligning brain features to a pretrained generative model',
          'Random networks',
          'No training',
        ],
        answerIndex: 1,
        explanation: 'These pipelines bridge brain features and generative priors.',
      },
    ],
    xpReward: 22,
    coinReward: 8,
    masteryThreshold: 0.8,
  },
  {
    id: 'E07',
    trackId: 'aineuro',
    moduleId: 'E-decoding',
    order: 7,
    title: 'Neural decoding fundamentals',
    subtitle: 'From brain to behaviour',
    estimatedMinutes: 5,
    difficulty: 'beginner',
    prerequisites: ['E03'],
    explanation:
      'A neural decoder is a model that predicts external variables — stimuli, intentions, behaviour — from neural activity. Linear decoders are the workhorse baselines; deep decoders can capture non-linear structure when enough data is available.',
    notation: 'ŷ_t = f(spike counts in window)',
    keyTerms: ['decoder', 'linear', 'non-linear', 'behaviour'],
    example:
      'A linear filter on motor cortex spikes is enough to predict cursor velocity in many BCI experiments.',
    intuition: 'A decoder is a translator from neural language to the outside world.',
    whyItMatters:
      'Decoding is the heart of brain-computer interfaces and a powerful analysis tool for systems neuroscience.',
    questions: [
      {
        prompt: 'A neural decoder maps...',
        options: ['Behaviour to spikes', 'Spikes to behaviour or stimuli', 'Random labels to data', 'EEG to MRI only'],
        answerIndex: 1,
        explanation: 'Decoding goes from neural activity to external variables.',
      },
      {
        prompt: 'Linear decoders are popular because they...',
        options: [
          'Are always optimal',
          'Are simple, fast, interpretable, and strong baselines',
          'Use no data',
          'Have no parameters',
        ],
        answerIndex: 1,
        explanation: 'They are robust and interpretable in low-data regimes.',
      },
      {
        prompt: 'Deep decoders tend to win when...',
        options: ['Data is tiny', 'Data is large and the relationship is non-linear', 'There is no relationship', 'Linear is exact'],
        answerIndex: 1,
        explanation: 'Capacity helps mainly with enough data and real non-linearity.',
      },
    ],
    xpReward: 20,
    coinReward: 7,
    masteryThreshold: 0.8,
  },
  {
    id: 'E08',
    trackId: 'aineuro',
    moduleId: 'E-decoding',
    order: 8,
    title: 'Decoding intended movement',
    subtitle: 'Reading motor cortex in real time',
    estimatedMinutes: 6,
    difficulty: 'intermediate',
    prerequisites: ['E07'],
    explanation:
      'Motor BCIs decode intended velocities or trajectories from motor cortex activity. Modern systems use Kalman filters, neural networks, or transformer-based decoders, with continuous recalibration to handle drift in neural signals.',
    keyTerms: ['motor cortex', 'Kalman filter', 'recalibration', 'velocity decoder'],
    example:
      'Paralysed patients have controlled robotic arms and computer cursors via motor-cortex decoders running in real time.',
    intuition: 'Imagine moving; the decoder turns the imagined motion into a command.',
    whyItMatters:
      'Motor decoding is the most clinically advanced application of NeuroAI.',
    questions: [
      {
        prompt: 'A Kalman filter is useful for motor decoding because it...',
        options: [
          'Models temporal dynamics and noise of velocity',
          'Replaces the brain entirely',
          'Has no parameters',
          'Cannot be tuned',
        ],
        answerIndex: 0,
        explanation: 'It tracks state under noisy linear dynamics.',
      },
      {
        prompt: 'Recalibration is needed because...',
        options: [
          'Neural signals drift and electrodes shift over time',
          'Models are perfect forever',
          'Hardware never changes',
          'Patients do not learn',
        ],
        answerIndex: 0,
        explanation: 'Without recalibration, decoders degrade.',
      },
      {
        prompt: 'In motor BCIs, the decoded output is typically...',
        options: ['A categorical word only', 'A continuous velocity, position, or trajectory', 'A facial expression label', 'A still image'],
        answerIndex: 1,
        explanation: 'Continuous control is the standard.',
      },
    ],
    xpReward: 24,
    coinReward: 9,
    masteryThreshold: 0.8,
  },
  {
    id: 'E09',
    trackId: 'aineuro',
    moduleId: 'E-decoding',
    order: 9,
    title: 'Speech decoding from cortex',
    subtitle: 'Giving voice back through neural signals',
    estimatedMinutes: 6,
    difficulty: 'intermediate',
    prerequisites: ['E08'],
    explanation:
      'Recent BCIs decode attempted speech from cortical recordings using deep sequence models that map neural activity to phonemes, words, or text. Some systems can produce dozens of words per minute with high accuracy.',
    keyTerms: ['speech BCI', 'phoneme decoder', 'sequence model', 'language model'],
    example:
      'A 2023 demonstration used neural networks plus a language model to decode attempted speech in patients with paralysis.',
    intuition: 'Read the motor plan for speech, not the sound itself.',
    whyItMatters:
      'Speech decoding is one of the highest-impact applications of NeuroAI for clinical care.',
    questions: [
      {
        prompt: 'Modern speech BCIs typically combine a neural decoder with a...',
        options: [
          'Random word generator',
          'Language model that constrains plausible word sequences',
          'Spike sorter only',
          'No prior at all',
        ],
        answerIndex: 1,
        explanation: 'Language priors dramatically improve accuracy.',
      },
      {
        prompt: 'These systems mainly read activity from...',
        options: ['Auditory hair cells', 'Speech motor and sensorimotor cortex', 'Spinal cord only', 'Liver'],
        answerIndex: 1,
        explanation: 'Speech-related cortex carries usable signals.',
      },
      {
        prompt: 'A typical decoder maps neural activity to...',
        options: ['Only emojis', 'Phonemes, words, or text', 'Pure colour', 'Heart rate'],
        answerIndex: 1,
        explanation: 'The output space is linguistic.',
      },
    ],
    xpReward: 24,
    coinReward: 9,
    masteryThreshold: 0.8,
  },
  {
    id: 'E10',
    trackId: 'aineuro',
    moduleId: 'E-decoding',
    order: 10,
    title: 'Decoding sensory stimuli',
    subtitle: 'From cortex back to world',
    estimatedMinutes: 5,
    difficulty: 'intermediate',
    prerequisites: ['E07'],
    explanation:
      'Sensory decoders predict what a subject is seeing, hearing, or feeling from cortical activity. Linear regressions on V1 firing rates can already reconstruct simple stimuli; deep decoders extend to more abstract content with enough data.',
    keyTerms: ['sensory decoding', 'V1', 'reconstruction', 'population code'],
    example:
      'Image reconstruction from V1 spikes was demonstrated decades ago for simple gratings; modern variants use deep priors for natural images.',
    intuition: 'The cortex has the picture; the decoder draws it.',
    whyItMatters:
      'Sensory decoders test theories of how the brain represents the outside world.',
    questions: [
      {
        prompt: 'A sensory decoder predicts...',
        options: ['Future spikes only', 'External stimuli from neural activity', 'A weight matrix', 'The next experiment'],
        answerIndex: 1,
        explanation: 'It maps neural activity back to the stimulus.',
      },
      {
        prompt: 'Deep priors help reconstructions when...',
        options: [
          'Stimuli are simple gratings only',
          'Reconstructing complex natural stimuli with limited data',
          'There are no stimuli',
          'You forbid using prior knowledge',
        ],
        answerIndex: 1,
        explanation: 'Generative priors fill in plausible structure.',
      },
      {
        prompt: 'Such decoders test theories about...',
        options: ['Tax law', 'Population coding of stimuli', 'Random access memory', 'Cosmology'],
        answerIndex: 1,
        explanation: 'They probe how stimuli are represented across populations.',
      },
    ],
    xpReward: 22,
    coinReward: 8,
    masteryThreshold: 0.8,
  },
  {
    id: 'E11',
    trackId: 'aineuro',
    moduleId: 'E-decoding',
    order: 11,
    title: 'Population decoding with deep nets',
    subtitle: 'Scaling beyond single units',
    estimatedMinutes: 6,
    difficulty: 'intermediate',
    prerequisites: ['E10'],
    explanation:
      'When recordings include hundreds or thousands of neurons, deep networks can capture rich non-linear maps from population activity to behaviour or stimuli. Architectures often respect time (temporal convolutions, RNNs, transformers) and channel structure.',
    keyTerms: ['population code', 'temporal convolution', 'transformer', 'channel'],
    example:
      'Transformer-based decoders on Neuropixels data outperform linear baselines for complex behaviours and stimuli.',
    intuition: 'A crowd of neurons is best read by a model that respects time and structure.',
    whyItMatters:
      'High-channel recordings demand decoders that scale with neuron count and capture temporal dynamics.',
    questions: [
      {
        prompt: 'Population decoders consider...',
        options: ['One neuron at a time only', 'Many neurons jointly', 'Only behaviour', 'Only labels'],
        answerIndex: 1,
        explanation: 'Joint structure across the population is the point.',
      },
      {
        prompt: 'A temporal convolution is suited for...',
        options: ['Static images only', 'Local time-window patterns in spike trains', 'Tabular data only', 'Text-only inputs'],
        answerIndex: 1,
        explanation: 'It sweeps a filter across time.',
      },
      {
        prompt: 'Transformers help decoding when...',
        options: [
          'There is no temporal structure',
          'Long-range temporal relationships across many units matter',
          'Data is tiny',
          'You forbid attention',
        ],
        answerIndex: 1,
        explanation: 'Self-attention captures long-range dependencies.',
      },
    ],
    xpReward: 24,
    coinReward: 9,
    masteryThreshold: 0.8,
  },
  {
    id: 'E12',
    trackId: 'aineuro',
    moduleId: 'E-behavior',
    order: 12,
    title: 'Pose estimation for animal behaviour',
    subtitle: 'Tracking bodies frame by frame',
    estimatedMinutes: 5,
    difficulty: 'beginner',
    prerequisites: ['E04'],
    explanation:
      'Tools like DeepLabCut and SLEAP use convolutional networks to track body parts in video, producing precise time series of pose. These traces feed into analyses linking behaviour to neural activity.',
    keyTerms: ['pose estimation', 'DeepLabCut', 'keypoint', 'behaviour video'],
    example:
      'Mouse paw positions tracked at 60 frames per second can be aligned to neural spikes to study motor learning.',
    intuition: 'Teach a vision model the joints; it follows the animal everywhere.',
    whyItMatters:
      'Quantitative behaviour is the missing partner to neural recordings — without it, neural activity is half the story.',
    questions: [
      {
        prompt: 'Pose estimation tools predict...',
        options: ['Only faces in images', 'Body part keypoint locations in video', 'Only audio', 'Only EEG'],
        answerIndex: 1,
        explanation: 'They output time series of keypoints.',
      },
      {
        prompt: 'Pairing pose with neural data lets you...',
        options: [
          'Link behaviour to neural activity quantitatively',
          'Avoid recording neurons',
          'Replace stimuli',
          'Stop the experiment early',
        ],
        answerIndex: 0,
        explanation: 'Behaviour anchors the meaning of neural patterns.',
      },
      {
        prompt: 'These models are typically...',
        options: ['Random forests', 'Convolutional or transformer-based vision networks', 'Spike sorters', 'Pure rule-based scripts'],
        answerIndex: 1,
        explanation: 'Vision deep learning dominates pose estimation.',
      },
    ],
    xpReward: 20,
    coinReward: 7,
    masteryThreshold: 0.8,
  },
  {
    id: 'E13',
    trackId: 'aineuro',
    moduleId: 'E-behavior',
    order: 13,
    title: 'Unsupervised behaviour segmentation',
    subtitle: 'Discovering motifs in motion',
    estimatedMinutes: 5,
    difficulty: 'intermediate',
    prerequisites: ['E12'],
    explanation:
      'Unsupervised models cluster pose time series into reusable behavioural motifs — such as grooming, rearing, or running — without explicit labels. Hidden Markov models, autoencoders, and clustering on learned embeddings are common tools.',
    keyTerms: ['behaviour motif', 'HMM', 'embedding', 'unsupervised'],
    example:
      'MoSeq segments mouse behaviour into syllable-like motifs from depth video, revealing structure not visible to manual scoring.',
    intuition: 'Behaviour has a vocabulary; let the model find the words.',
    whyItMatters:
      'Automated behavioural alphabets enable large-scale, reproducible studies of natural behaviour and its neural correlates.',
    questions: [
      {
        prompt: 'Unsupervised behaviour segmentation discovers...',
        options: [
          'Manual labels',
          'Recurrent behavioural motifs without labels',
          'Spike sorting templates',
          'Reward functions',
        ],
        answerIndex: 1,
        explanation: 'It clusters behaviour into discovered motifs.',
      },
      {
        prompt: 'A Hidden Markov Model captures...',
        options: [
          'Discrete latent behaviour states with transitions over time',
          'Only static images',
          'No structure',
          'A spreadsheet',
        ],
        answerIndex: 0,
        explanation: 'HMMs model latent states with temporal transitions.',
      },
      {
        prompt: 'These tools are valuable because they...',
        options: [
          'Replace neural recordings',
          'Make behavioural analysis reproducible and large-scale',
          'Are unrelated to data',
          'Are only manual',
        ],
        answerIndex: 1,
        explanation: 'Automation removes scorer bias and scales studies.',
      },
    ],
    xpReward: 22,
    coinReward: 8,
    masteryThreshold: 0.8,
  },
  {
    id: 'E14',
    trackId: 'aineuro',
    moduleId: 'E-behavior',
    order: 14,
    title: 'Closed-loop AI experiments',
    subtitle: 'Letting the model drive the experiment',
    estimatedMinutes: 5,
    difficulty: 'intermediate',
    prerequisites: ['E13'],
    explanation:
      'In closed-loop experiments, an AI model reads neural activity or behaviour in real time and adjusts stimulation, reward, or task difficulty based on what it sees. This enables adaptive paradigms that converge on causal questions much faster.',
    keyTerms: ['closed loop', 'real-time', 'adaptive stimulation', 'causal'],
    example:
      'Real-time decoders trigger optogenetic stimulation when a specific neural pattern appears, probing causal roles in behaviour.',
    intuition: 'The model becomes a co-experimenter that responds to the brain right now.',
    whyItMatters:
      'Closed loops turn brittle one-shot experiments into adaptive, hypothesis-driven studies.',
    questions: [
      {
        prompt: 'A closed-loop experiment requires...',
        options: ['Offline analysis only', 'Real-time inference and control', 'No experiments', 'Only behaviour'],
        answerIndex: 1,
        explanation: 'Real-time response is what makes it closed loop.',
      },
      {
        prompt: 'A scientific advantage of closed-loop AI is...',
        options: [
          'It can target specific neural states for stimulation, helping infer causality',
          'It removes the need for analysis',
          'It eliminates noise entirely',
          'It avoids hypotheses',
        ],
        answerIndex: 0,
        explanation: 'Targeted perturbations reveal causal structure.',
      },
      {
        prompt: 'A practical constraint is...',
        options: ['Latency must stay below experimental timescales', 'Models must be enormous', 'Data is unnecessary', 'Reward is unused'],
        answerIndex: 0,
        explanation: 'Slow models break the loop.',
      },
    ],
    xpReward: 24,
    coinReward: 9,
    masteryThreshold: 0.8,
  },
  {
    id: 'E15',
    trackId: 'aineuro',
    moduleId: 'E-modeling',
    order: 15,
    title: 'CNNs as models of vision',
    subtitle: 'Why deep nets resemble cortex',
    estimatedMinutes: 6,
    difficulty: 'intermediate',
    prerequisites: ['E06'],
    explanation:
      'Trained convolutional networks predict neural responses across the ventral visual stream surprisingly well. Deeper layers map onto higher visual areas. This makes CNNs both useful tools and candidate hypotheses about what cortex computes.',
    keyTerms: ['ventral stream', 'V1, V4, IT', 'representational similarity', 'model-brain mapping'],
    example:
      'Models trained on ImageNet show internal representations that correlate strongly with macaque IT recordings.',
    intuition: 'Solve image recognition well, end up looking like visual cortex.',
    whyItMatters:
      'It supports the idea that cortex implements task-driven, hierarchical feature learning.',
    questions: [
      {
        prompt: 'CNNs trained on natural images tend to align with...',
        options: ['Unrelated brain areas only', 'Hierarchical visual cortex layers', 'Spinal cord only', 'No brain area'],
        answerIndex: 1,
        explanation: 'Layer hierarchies map to visual area hierarchies.',
      },
      {
        prompt: 'Representational similarity analysis compares...',
        options: [
          'Architectures only',
          'Pairwise structure of representations between brains and models',
          'Wallpaper patterns',
          'Temperatures',
        ],
        answerIndex: 1,
        explanation: 'It compares similarity matrices across systems.',
      },
      {
        prompt: 'A reason for the alignment is that both systems...',
        options: [
          'Solve overlapping recognition tasks under similar pressures',
          'Are random',
          'Have nothing in common',
          'Use the same wires',
        ],
        answerIndex: 0,
        explanation: 'Shared task pressures shape similar representations.',
      },
    ],
    xpReward: 26,
    coinReward: 10,
    masteryThreshold: 0.8,
  },
  {
    id: 'E16',
    trackId: 'aineuro',
    moduleId: 'E-modeling',
    order: 16,
    title: 'RNNs as models of motor cortex',
    subtitle: 'Dynamics that look familiar',
    estimatedMinutes: 6,
    difficulty: 'intermediate',
    prerequisites: ['E08'],
    explanation:
      'Recurrent neural networks trained on motor tasks reproduce many features of motor cortex dynamics, including rotational structure during reaching. They are used as models to explain how cortical populations generate movement.',
    keyTerms: ['motor cortex', 'rotational dynamics', 'task-trained RNN', 'dynamical systems'],
    example:
      'Task-trained RNNs reproduce the jPCA rotational dynamics observed in monkey motor cortex during reaching.',
    intuition: 'Train a recurrent network to reach; its hidden state moves like motor cortex.',
    whyItMatters:
      'Such models provide testable hypotheses about how movement emerges from population dynamics.',
    questions: [
      {
        prompt: 'Task-trained RNNs are useful as...',
        options: [
          'Pure decoders only',
          'Mechanistic models of cortical dynamics',
          'Random samplers',
          'Static images',
        ],
        answerIndex: 1,
        explanation: 'They mimic dynamics under task pressure.',
      },
      {
        prompt: 'Rotational dynamics in motor cortex can be matched by...',
        options: ['Randomly initialised networks only', 'Task-trained RNNs', 'A single neuron', 'A linear regression'],
        answerIndex: 1,
        explanation: 'Training on reach tasks produces similar geometry.',
      },
      {
        prompt: 'A modelling claim is that movement emerges from...',
        options: [
          'Population dynamics, not isolated single units',
          'Only one neuron',
          'No structure',
          'External rules typed by hand',
        ],
        answerIndex: 0,
        explanation: 'Population-level state evolution drives movement.',
      },
    ],
    xpReward: 26,
    coinReward: 10,
    masteryThreshold: 0.8,
  },
  {
    id: 'E17',
    trackId: 'aineuro',
    moduleId: 'E-modeling',
    order: 17,
    title: 'Transformers as brain models',
    subtitle: 'Attention as a candidate principle',
    estimatedMinutes: 6,
    difficulty: 'intermediate',
    prerequisites: ['E15'],
    explanation:
      'Transformer architectures are increasingly used to model language and vision in the brain. They predict cortical responses to natural language and complex stimuli at high accuracy and inspire hypotheses about attention and context in cortex.',
    keyTerms: ['attention', 'language model', 'voxel prediction', 'context'],
    example:
      'GPT-style models trained on text predict fMRI responses to spoken stories better than older language models.',
    intuition: 'A model that uses long context well also predicts brains using long context.',
    whyItMatters:
      'Transformers may capture computations beyond what CNNs and RNNs offered, especially for language and high-level cognition.',
    questions: [
      {
        prompt: 'Transformers excel at modelling brain responses to...',
        options: ['Only static gratings', 'Natural language and rich structured stimuli', 'Pure noise', 'No stimuli'],
        answerIndex: 1,
        explanation: 'Rich context plus attention helps for language and cognition.',
      },
      {
        prompt: 'A reason transformers may align with cortex is that they...',
        options: [
          'Avoid context',
          'Integrate long-range context across inputs',
          'Have no training',
          'Use only one parameter',
        ],
        answerIndex: 1,
        explanation: 'Context integration is a shared computational pressure.',
      },
      {
        prompt: 'Predicting fMRI from a language model usually requires...',
        options: [
          'Mapping model activations to voxel responses',
          'Running fMRI without subjects',
          'Random forests of pixels',
          'No model at all',
        ],
        answerIndex: 0,
        explanation: 'Linear or non-linear maps connect model activations to voxels.',
      },
    ],
    xpReward: 26,
    coinReward: 10,
    masteryThreshold: 0.8,
  },
  {
    id: 'E18',
    trackId: 'aineuro',
    moduleId: 'E-modeling',
    order: 18,
    title: 'Brain-score and model-brain alignment',
    subtitle: 'Scoring how brain-like a model is',
    estimatedMinutes: 5,
    difficulty: 'intermediate',
    prerequisites: ['E17'],
    explanation:
      'Brain-score and similar benchmarks evaluate how well an AI model predicts neural and behavioural data across many regions and tasks. Higher scores often, but not always, correlate with better task performance, and the relationship itself is a research question.',
    keyTerms: ['brain-score', 'benchmark', 'alignment', 'predictivity'],
    example:
      'Trained vision models are ranked by their predictivity of single-unit responses in V1, V4, IT, and behaviour.',
    intuition: 'Score the model on how well it pretends to be the brain.',
    whyItMatters:
      'Quantitative benchmarks turn modelling claims into testable comparisons.',
    questions: [
      {
        prompt: 'A brain-score benchmark measures...',
        options: [
          'Only model accuracy on ImageNet',
          'How well models predict neural and behavioural data',
          'Pure compute used',
          'Random matches',
        ],
        answerIndex: 1,
        explanation: 'It scores predictivity against brain measurements.',
      },
      {
        prompt: 'Better task performance...',
        options: [
          'Always implies better brain alignment',
          'Sometimes correlates with brain alignment, but not always',
          'Has nothing to do with anything',
          'Only matters offline',
        ],
        answerIndex: 1,
        explanation: 'The relationship is non-trivial and itself studied.',
      },
      {
        prompt: 'These benchmarks are useful because they...',
        options: ['Eliminate the need for experiments', 'Allow apples-to-apples model comparisons', 'Only run on CPUs', 'Hide model differences'],
        answerIndex: 1,
        explanation: 'They provide standard comparisons across architectures.',
      },
    ],
    xpReward: 24,
    coinReward: 9,
    masteryThreshold: 0.8,
  },
  {
    id: 'E19',
    trackId: 'aineuro',
    moduleId: 'E-modeling',
    order: 19,
    title: 'Predictive coding and learning rules',
    subtitle: 'Errors as the unit of learning',
    estimatedMinutes: 6,
    difficulty: 'intermediate',
    prerequisites: ['E15'],
    explanation:
      'Predictive coding posits that the brain learns by minimising prediction errors at multiple levels. AI implementations cast this as hierarchical generative models that pass predictions down and errors up, and align with several aspects of cortical anatomy.',
    keyTerms: ['predictive coding', 'top-down', 'prediction error', 'generative model'],
    example:
      'Some predictive coding networks reproduce mismatch responses observed in cortex when sensory input violates expectations.',
    intuition: 'Predict the world, then learn from where you were wrong.',
    whyItMatters:
      'Predictive coding is one of the leading candidate principles unifying perception, learning, and cortex.',
    questions: [
      {
        prompt: 'In predictive coding, errors are...',
        options: [
          'Ignored',
          'The signal that drives learning and updates',
          'Only used at test time',
          'Random',
        ],
        answerIndex: 1,
        explanation: 'Prediction errors carry the learning signal.',
      },
      {
        prompt: 'Predictive coding suggests cortex contains...',
        options: [
          'No top-down signals',
          'Top-down predictions and bottom-up errors at multiple levels',
          'Only feedforward pathways',
          'Pure randomness',
        ],
        answerIndex: 1,
        explanation: 'Hierarchical loops are central to the theory.',
      },
      {
        prompt: 'Mismatch responses fit predictive coding because they...',
        options: [
          'Spike when expectations are violated',
          'Never occur in real cortex',
          'Are unrelated to predictions',
          'Are pure noise',
        ],
        answerIndex: 0,
        explanation: 'Violations of expectation produce error-like activity.',
      },
    ],
    xpReward: 26,
    coinReward: 10,
    masteryThreshold: 0.8,
  },
  {
    id: 'E20',
    trackId: 'aineuro',
    moduleId: 'E-modeling',
    order: 20,
    title: 'Reinforcement learning and basal ganglia',
    subtitle: 'Dopamine, reward, and value',
    estimatedMinutes: 6,
    difficulty: 'intermediate',
    prerequisites: ['E07'],
    explanation:
      'Reinforcement learning theory has an unusually deep partnership with neuroscience. Dopamine neuron firing approximates a reward prediction error signal, and basal ganglia circuits are interpreted as actor-critic systems learning from those errors.',
    keyTerms: ['dopamine', 'reward prediction error', 'basal ganglia', 'actor-critic'],
    example:
      'Schultz’s recordings from dopamine neurons match the temporal-difference prediction error from RL theory.',
    intuition: 'A spike of dopamine = "better than expected".',
    whyItMatters:
      'It is one of the cleanest examples where a theoretical AI quantity has a measured neural counterpart.',
    questions: [
      {
        prompt: 'Dopamine neurons are interpreted as encoding...',
        options: ['Pure motor commands', 'Reward prediction errors', 'Visual edges', 'Working memory'],
        answerIndex: 1,
        explanation: 'Their phasic firing tracks RPE.',
      },
      {
        prompt: 'The basal ganglia are often modelled as...',
        options: ['A pure feedforward classifier', 'An actor-critic-like RL system', 'A spike sorter', 'Sensory cortex'],
        answerIndex: 1,
        explanation: 'Striatum and dopamine implement an actor-critic-like loop.',
      },
      {
        prompt: 'Reward prediction errors are large when...',
        options: ['Outcomes match expectations', 'Outcomes are surprisingly better or worse than expected', 'Reward is constant', 'There is no reward signal'],
        answerIndex: 1,
        explanation: 'Surprise drives the error.',
      },
    ],
    xpReward: 26,
    coinReward: 10,
    masteryThreshold: 0.8,
  },
  {
    id: 'E21',
    trackId: 'aineuro',
    moduleId: 'E-frontier',
    order: 21,
    title: 'Self-supervised learning on neural data',
    subtitle: 'Pretraining without labels',
    estimatedMinutes: 5,
    difficulty: 'intermediate',
    prerequisites: ['E11'],
    explanation:
      'Self-supervised learning trains models on unlabelled data using auxiliary tasks like masked prediction. Applied to spike trains and calcium traces, it produces general-purpose embeddings that transfer well to small downstream tasks.',
    keyTerms: ['self-supervised', 'masking', 'embedding', 'transfer'],
    example:
      'A masked autoencoder trained on millions of spike-train segments yields embeddings that improve decoding on small new datasets.',
    intuition: 'Learn the language of the brain first; specialise later.',
    whyItMatters:
      'Brain experiments are expensive; self-supervised pretraining squeezes more value out of every recording.',
    questions: [
      {
        prompt: 'Self-supervised learning needs...',
        options: ['Manual labels for everything', 'No human labels for the pretraining task', 'Only synthetic data', 'No data at all'],
        answerIndex: 1,
        explanation: 'Pretext tasks come from the data itself.',
      },
      {
        prompt: 'Masked prediction in spike data resembles...',
        options: ['MLM in language models', 'A loss function', 'A spike sorter', 'A random forest'],
        answerIndex: 0,
        explanation: 'It hides parts of the signal and predicts them.',
      },
      {
        prompt: 'The downstream win comes from...',
        options: [
          'Better embeddings that transfer to small labelled tasks',
          'Larger random noise',
          'Avoiding training entirely',
          'Skipping evaluation',
        ],
        answerIndex: 0,
        explanation: 'Pretrained features beat training from scratch on small data.',
      },
    ],
    xpReward: 24,
    coinReward: 9,
    masteryThreshold: 0.8,
  },
  {
    id: 'E22',
    trackId: 'aineuro',
    moduleId: 'E-frontier',
    order: 22,
    title: 'Foundation models for neural data',
    subtitle: 'Pretrained brains for transfer',
    estimatedMinutes: 6,
    difficulty: 'advanced',
    prerequisites: ['E21'],
    explanation:
      'Foundation models for neuroscience are large pretrained models that ingest spikes, calcium, EEG, or fMRI from many subjects and tasks, producing general representations that can be fine-tuned to a wide variety of downstream problems.',
    keyTerms: ['foundation model', 'pretraining', 'multi-subject', 'transfer'],
    example:
      'Large pretrained models on heterogeneous neural recordings can decode behaviour on new subjects with minimal additional data.',
    intuition: 'A general model of the brain that you specialise to your experiment.',
    whyItMatters:
      'Foundation models could turn fragmented neuroscience data into a shared resource and dramatically lower the data cost of new studies.',
    questions: [
      {
        prompt: 'A neuroscience foundation model is typically...',
        options: [
          'A single task-specific decoder',
          'A large model pretrained on many sessions and subjects, then fine-tuned',
          'An unlearned random network',
          'Only a database',
        ],
        answerIndex: 1,
        explanation: 'Pretraining + fine-tuning is the recipe.',
      },
      {
        prompt: 'A practical benefit is...',
        options: [
          'Less data needed for new downstream tasks',
          'No need for evaluation',
          'Removing all noise',
          'Avoiding any fine-tuning',
        ],
        answerIndex: 0,
        explanation: 'Pretraining substitutes for missing data downstream.',
      },
      {
        prompt: 'Aggregating across subjects is hard because...',
        options: [
          'Brains and recording setups vary',
          'Brains are identical across subjects',
          'There is no variation',
          'Models cannot use multiple subjects',
        ],
        answerIndex: 0,
        explanation: 'Variability across subjects/sessions complicates joint training.',
      },
    ],
    xpReward: 26,
    coinReward: 10,
    masteryThreshold: 0.8,
  },
  {
    id: 'E23',
    trackId: 'aineuro',
    moduleId: 'E-clinical',
    order: 23,
    title: 'AI for EEG and seizure detection',
    subtitle: 'Catching seizures in noisy traces',
    estimatedMinutes: 5,
    difficulty: 'intermediate',
    prerequisites: ['E02'],
    explanation:
      'EEG produces noisy multichannel time series. Deep models, especially convolutional and recurrent networks, are widely used to detect seizures, classify sleep stages, and flag clinical events with sensitivity that matches or exceeds expert annotators.',
    keyTerms: ['EEG', 'seizure', 'sleep staging', 'multichannel'],
    example:
      'Deep models detect epileptiform discharges in long-term EEG recordings to assist clinicians.',
    intuition: 'Pattern-spotting in a noisy ribbon of channels — exactly what CNNs are for.',
    whyItMatters:
      'Reliable detectors scale clinical care to far more patients than human review allows.',
    questions: [
      {
        prompt: 'EEG signals are typically...',
        options: ['Noiseless and sparse', 'Noisy multichannel time series', 'Static images', 'Pure text'],
        answerIndex: 1,
        explanation: 'EEG is multichannel temporal data with significant noise.',
      },
      {
        prompt: 'Modern seizure detectors often outperform humans because they...',
        options: [
          'Process huge amounts of data consistently and quickly',
          'Are guaranteed to be correct',
          'Use no training',
          'Skip evaluation',
        ],
        answerIndex: 0,
        explanation: 'Throughput and consistency are the practical advantages.',
      },
      {
        prompt: 'A common architecture for EEG analysis is...',
        options: ['Random forest only', 'Convolutional and recurrent networks over time and channels', 'Static MLP on a single sample', 'Spike sorter only'],
        answerIndex: 1,
        explanation: 'Convolution + recurrence captures both local and temporal structure.',
      },
    ],
    xpReward: 24,
    coinReward: 9,
    masteryThreshold: 0.8,
  },
  {
    id: 'E24',
    trackId: 'aineuro',
    moduleId: 'E-clinical',
    order: 24,
    title: 'Deep learning in clinical MRI',
    subtitle: 'Tumours, lesions, and segmentation',
    estimatedMinutes: 5,
    difficulty: 'intermediate',
    prerequisites: ['E04'],
    explanation:
      'In clinical MRI, deep learning is used for tumour segmentation, lesion detection, age and disease prediction, and improving image quality from undersampled scans. These tools assist radiologists rather than replace them.',
    keyTerms: ['MRI', 'segmentation', 'lesion', 'reconstruction'],
    example:
      'U-Net-based models segment brain tumours from multi-modal MRI to support surgical planning.',
    intuition: 'Pixel-level decisions where every voxel matters.',
    whyItMatters:
      'These models compress hours of expert review and improve consistency of diagnoses.',
    questions: [
      {
        prompt: 'A common clinical MRI ML task is...',
        options: ['Predicting stock prices', 'Tumour or lesion segmentation', 'Sentiment analysis', 'Spike sorting'],
        answerIndex: 1,
        explanation: 'Voxel-level segmentation is a major application.',
      },
      {
        prompt: 'In medical imaging, deep models typically...',
        options: [
          'Replace doctors entirely',
          'Assist clinicians by speeding up and standardising analysis',
          'Are unused',
          'Only run offline never on real cases',
        ],
        answerIndex: 1,
        explanation: 'They are decision-support tools.',
      },
      {
        prompt: 'Reconstruction networks can...',
        options: [
          'Improve image quality from undersampled scans',
          'Add random pixels',
          'Erase the scan',
          'Always make images worse',
        ],
        answerIndex: 0,
        explanation: 'Learned priors fill missing information when applied carefully.',
      },
    ],
    xpReward: 24,
    coinReward: 9,
    masteryThreshold: 0.8,
  },
  {
    id: 'E25',
    trackId: 'aineuro',
    moduleId: 'E-clinical',
    order: 25,
    title: 'BCIs with deep decoders',
    subtitle: 'AI in the closed loop with patients',
    estimatedMinutes: 6,
    difficulty: 'advanced',
    prerequisites: ['E08', 'E09'],
    explanation:
      'Modern brain-computer interfaces combine high-channel recordings with deep decoders, language priors, and adaptive recalibration to control cursors, robotic arms, communication devices, and even synthesised speech for patients with paralysis.',
    keyTerms: ['BCI', 'deep decoder', 'recalibration', 'assistive device'],
    example:
      'Patients with ALS have produced text and speech in real time using deep-learning BCIs.',
    intuition: 'Combine the best decoder, the best prior, and the best feedback loop.',
    whyItMatters:
      'Deep BCIs are the most direct example of NeuroAI translating into life-changing assistive technology.',
    questions: [
      {
        prompt: 'Deep-decoder BCIs typically also use...',
        options: [
          'Language or motion priors and adaptive recalibration',
          'Only random outputs',
          'No real-time inference',
          'No subjects',
        ],
        answerIndex: 0,
        explanation: 'Priors and recalibration are essential to performance.',
      },
      {
        prompt: 'A motivation for deep decoders over linear ones is...',
        options: [
          'They can capture non-linear neural patterns when data allows',
          'They always generalise more than simple models',
          'They need no calibration',
          'They never fail',
        ],
        answerIndex: 0,
        explanation: 'Non-linear capacity helps when supported by data.',
      },
      {
        prompt: 'A real-world deployment must also consider...',
        options: [
          'Safety, comfort, and reliability for patients',
          'Only theoretical speed',
          'Only paper publications',
          'Only model size',
        ],
        answerIndex: 0,
        explanation: 'Clinical reality dominates engineering choices.',
      },
    ],
    xpReward: 28,
    coinReward: 11,
    masteryThreshold: 0.8,
  },
  {
    id: 'E26',
    trackId: 'aineuro',
    moduleId: 'E-clinical',
    order: 26,
    title: 'AI for neurodegenerative disease',
    subtitle: 'Earlier signals, better outcomes',
    estimatedMinutes: 5,
    difficulty: 'intermediate',
    prerequisites: ['E24'],
    explanation:
      'Machine learning combines imaging, behaviour, and digital biomarkers from phones and wearables to detect neurodegenerative disease earlier and track progression. Models are trained on multi-modal data with careful attention to bias and generalisation.',
    keyTerms: ['biomarker', 'progression', 'multi-modal', 'fairness'],
    example:
      'Voice, gait, and typing patterns from phones are combined with imaging to detect early Parkinson’s features.',
    intuition: 'Many small signals combined often outpredict any single test.',
    whyItMatters:
      'Earlier detection unlocks earlier intervention, which matters most in degenerative diseases.',
    questions: [
      {
        prompt: 'A digital biomarker is...',
        options: [
          'A measurable behavioural or physiological signal collected by a digital device',
          'A type of MRI machine',
          'A surgical tool',
          'A drug',
        ],
        answerIndex: 0,
        explanation: 'Things like phone-based voice or gait are digital biomarkers.',
      },
      {
        prompt: 'Multi-modal AI in disease prediction typically...',
        options: [
          'Combines imaging, behaviour, and clinical data',
          'Uses only one source forever',
          'Avoids data',
          'Is purely random',
        ],
        answerIndex: 0,
        explanation: 'Combining modalities increases predictive power.',
      },
      {
        prompt: 'A key risk in clinical ML is...',
        options: [
          'Bias and unfair generalisation across demographic groups',
          'Models are always perfect',
          'No risk exists',
          'Datasets are infinite',
        ],
        answerIndex: 0,
        explanation: 'Skewed data can produce harmful, biased models.',
      },
    ],
    xpReward: 24,
    coinReward: 9,
    masteryThreshold: 0.8,
  },
  {
    id: 'E27',
    trackId: 'aineuro',
    moduleId: 'E-frontier',
    order: 27,
    title: 'Generative models of neural activity',
    subtitle: 'Simulating brains to test theories',
    estimatedMinutes: 5,
    difficulty: 'advanced',
    prerequisites: ['E22'],
    explanation:
      'Generative models such as VAEs, normalising flows, and diffusion models are trained to produce realistic neural recordings. They serve as simulators for testing decoders, generating counterfactuals, and characterising the structure of population activity.',
    keyTerms: ['generative model', 'VAE', 'diffusion', 'simulation'],
    example:
      'A VAE trained on motor cortex spikes can generate plausible synthetic trials for benchmarking decoders.',
    intuition: 'If your model can dream the data, it has captured something about the brain.',
    whyItMatters:
      'Generative simulators turn neural science into something testable in silico at scale.',
    questions: [
      {
        prompt: 'A generative model of neural data can be used to...',
        options: [
          'Replace recordings forever',
          'Simulate plausible activity for analysis and benchmarking',
          'Avoid evaluation',
          'Encrypt data',
        ],
        answerIndex: 1,
        explanation: 'Synthetic data complements real recordings.',
      },
      {
        prompt: 'Generative models are validated by...',
        options: [
          'Checking the realism of samples and their match to held-out data',
          'Picking pretty colours only',
          'Counting parameters',
          'Random comparisons',
        ],
        answerIndex: 0,
        explanation: 'Sample quality plus held-out fit is the standard test.',
      },
      {
        prompt: 'Counterfactual generation lets you ask...',
        options: [
          'What activity would look like under different conditions',
          'Only what already happened',
          'Nothing useful',
          'Only the average',
        ],
        answerIndex: 0,
        explanation: 'Counterfactuals probe model behaviour under interventions.',
      },
    ],
    xpReward: 26,
    coinReward: 10,
    masteryThreshold: 0.8,
  },
  {
    id: 'E28',
    trackId: 'aineuro',
    moduleId: 'E-frontier',
    order: 28,
    title: 'Causal inference for neural circuits',
    subtitle: 'Beyond correlation in the brain',
    estimatedMinutes: 6,
    difficulty: 'advanced',
    prerequisites: ['E14'],
    explanation:
      'Causal inference techniques combine perturbations (optogenetic stimulation, lesions, drugs) with statistical models to estimate direct effects between brain regions or cell types. AI helps design optimal perturbations and analyse the resulting data.',
    keyTerms: ['causal inference', 'perturbation', 'optogenetics', 'intervention'],
    example:
      'Optogenetic stimulation paired with population recordings and counterfactual modelling can reveal which neurons drive a behaviour.',
    intuition: 'Wiggle a part, watch the brain, learn what depends on what.',
    whyItMatters:
      'Pure correlation cannot tell you what would happen if you intervened. Causal inference is essential for circuit-level understanding.',
    questions: [
      {
        prompt: 'A core idea of causal inference is to...',
        options: [
          'Use interventions to estimate the effect of one variable on another',
          'Avoid any experiments',
          'Only measure correlations',
          'Skip statistics',
        ],
        answerIndex: 0,
        explanation: 'Interventions break confounding that pure correlation cannot.',
      },
      {
        prompt: 'Optogenetic stimulation provides...',
        options: [
          'A fast, targeted causal perturbation of specific neurons',
          'Random recordings',
          'Only behavioural data',
          'No experimental control',
        ],
        answerIndex: 0,
        explanation: 'It is a powerful causal tool with cell-type specificity.',
      },
      {
        prompt: 'AI helps causal neuroscience by...',
        options: [
          'Designing better perturbations and analysing high-dimensional outcomes',
          'Replacing all biology',
          'Adding noise only',
          'Removing data',
        ],
        answerIndex: 0,
        explanation: 'AI augments experimental design and analysis.',
      },
    ],
    xpReward: 28,
    coinReward: 11,
    masteryThreshold: 0.8,
  },
  {
    id: 'E29',
    trackId: 'aineuro',
    moduleId: 'E-frontier',
    order: 29,
    title: 'Ethics, privacy, and bias in NeuroAI',
    subtitle: 'Powerful tools demand care',
    estimatedMinutes: 5,
    difficulty: 'intermediate',
    prerequisites: ['E26'],
    explanation:
      'NeuroAI raises sharp ethical questions: brain data is intimate, models can leak it, and biased datasets can produce unfair clinical or BCI tools. Responsible practice means privacy-preserving training, equitable datasets, and transparent evaluation across groups.',
    keyTerms: ['privacy', 'fairness', 'consent', 'governance'],
    example:
      'A clinical model trained mostly on one demographic may fail badly on others — fairness audits catch this before deployment.',
    intuition: 'Brain data is unusually personal. Treat it that way.',
    whyItMatters:
      'NeuroAI is moving fast into clinics and consumer products; the ethics must move just as fast.',
    questions: [
      {
        prompt: 'An ethical issue specific to neural data is...',
        options: [
          'Its high intimacy and potential to reveal private mental information',
          'It being purely public',
          'Being identical to general tabular data',
          'Having no consent issues',
        ],
        answerIndex: 0,
        explanation: 'Brain data is intrinsically sensitive.',
      },
      {
        prompt: 'A fairness audit checks that a model...',
        options: [
          'Performs comparably across demographic and clinical subgroups',
          'Has no parameters',
          'Runs only on GPUs',
          'Has the largest possible accuracy on one group only',
        ],
        answerIndex: 0,
        explanation: 'Cross-group performance is the focus of fairness checks.',
      },
      {
        prompt: 'Privacy-preserving training techniques include...',
        options: [
          'Differential privacy and federated learning',
          'Public data dumps',
          'Sharing all raw recordings online',
          'No safeguards',
        ],
        answerIndex: 0,
        explanation: 'These are standard tools for privacy-aware ML.',
      },
    ],
    xpReward: 24,
    coinReward: 9,
    masteryThreshold: 0.8,
  },
  {
    id: 'E30',
    trackId: 'aineuro',
    moduleId: 'E-frontier',
    order: 30,
    title: 'The future of NeuroAI',
    subtitle: 'Where the two fields are heading',
    estimatedMinutes: 6,
    difficulty: 'advanced',
    prerequisites: ['E22', 'E25', 'E29'],
    explanation:
      'NeuroAI is moving toward shared foundation models for brain data, tighter closed-loop experiments, more sophisticated BCIs, and theories that go beyond pattern matching to mechanism. Progress depends on open data, open models, and careful science.',
    keyTerms: ['foundation models', 'closed loop', 'theory', 'open science'],
    example:
      'Open repositories of multi-subject neural recordings, paired with shared pretrained models, are starting to look like ImageNet did for computer vision.',
    intuition: 'The next decade is about scaling, sharing, and explaining.',
    whyItMatters:
      'NeuroAI is one of the few fields where progress on the engineering side directly compounds with progress on the basic science side.',
    questions: [
      {
        prompt: 'A likely near-term direction is...',
        options: [
          'Shared foundation models on open neural datasets',
          'Going back to single-electrode recordings only',
          'Abandoning closed-loop experiments',
          'Avoiding all AI tools',
        ],
        answerIndex: 0,
        explanation: 'Shared pretraining is reshaping the field.',
      },
      {
        prompt: 'Mechanistic understanding goes beyond...',
        options: [
          'Pure pattern matching toward explanations of how circuits compute',
          'Avoiding any models',
          'Only behavioural metrics',
          'Pure data plotting',
        ],
        answerIndex: 0,
        explanation: 'Mechanism asks how, not just what predicts what.',
      },
      {
        prompt: 'Open science accelerates NeuroAI because it...',
        options: [
          'Allows the same data to feed many models and many labs',
          'Hides results from the community',
          'Removes accountability',
          'Avoids reproducibility',
        ],
        answerIndex: 0,
        explanation: 'Shared data and models compound across the community.',
      },
    ],
    xpReward: 30,
    coinReward: 12,
    masteryThreshold: 0.8,
  },
];
