import { Lesson } from './types';

/**
 * Track A — Neuroscience Basics. 20 lessons. Unlocked from the start.
 */
export const trackALessons: Lesson[] = [
  {
    id: 'A01',
    trackId: 'neuroscience',
    moduleId: 'A-cells',
    order: 1,
    title: 'Neuron anatomy',
    subtitle: 'The shape of a thinking cell',
    estimatedMinutes: 4,
    difficulty: 'intro',
    prerequisites: [],
    explanation:
      'A neuron has three working parts. Dendrites reach out like branches to catch incoming signals. The cell body, called the soma, gathers these signals and decides whether to respond. A long cable called the axon carries the neuron\u2019s own signal to other cells, often ending at specialised tips called axon terminals.',
    notation: 'dendrites \u2192 soma \u2192 axon \u2192 terminals',
    keyTerms: ['dendrite', 'soma', 'axon', 'axon terminal'],
    example:
      'A pyramidal neuron in your cortex can have a dendritic tree the size of a coin and an axon that travels a dozen centimetres to speak with a distant brain region.',
    intuition: 'Input in, signal out. The neuron is a tiny messenger with branches to listen and a wire to speak.',
    whyItMatters:
      'Every model you will meet later is a simplification of this shape. Knowing the parts lets you connect equations to real biology.',
    questions: [
      {
        prompt: 'Which part of a neuron mainly receives incoming signals?',
        options: ['Axon', 'Dendrites', 'Myelin', 'Synaptic vesicles'],
        answerIndex: 1,
        explanation: 'Dendrites branch outward to collect inputs from other neurons.',
      },
      {
        prompt: 'The axon is best described as...',
        options: [
          'The cell\u2019s input tree',
          'The decision-making core',
          'A cable that carries the cell\u2019s output',
          'A type of supporting glial cell',
        ],
        answerIndex: 2,
        explanation: 'The axon carries a neuron\u2019s outgoing signal, often far from the soma.',
      },
      {
        prompt: 'The soma is also called the...',
        options: ['Synapse', 'Cell body', 'Node of Ranvier', 'Dendritic spine'],
        answerIndex: 1,
        explanation: 'Soma simply means "body". It houses the nucleus and integrates signals.',
      },
    ],
    xpReward: 15,
    coinReward: 5,
    masteryThreshold: 0.8,
  },
  {
    id: 'A02',
    trackId: 'neuroscience',
    moduleId: 'A-membrane',
    order: 2,
    title: 'Resting membrane potential',
    subtitle: 'Why a quiet neuron is not zero',
    estimatedMinutes: 5,
    difficulty: 'beginner',
    prerequisites: ['A01'],
    explanation:
      'A neuron at rest holds a small voltage across its membrane, typically around minus 65 millivolts inside relative to outside. This difference exists because potassium can leak out while sodium is kept mostly outside, and negatively charged proteins sit inside the cell.',
    notation: 'V_rest \u2248 \u221265 mV',
    keyTerms: ['membrane potential', 'ion gradient', 'K+ leak', 'Na+/K+ pump'],
    example:
      'Cortical neurons are not silent at rest \u2014 they sit negatively charged and ready, like a tiny battery waiting for a reason to fire.',
    intuition: 'Rest is not off. Rest is a charged silence.',
    whyItMatters:
      'Every spike begins from rest. Computational models start with a resting state and ask how inputs push it toward threshold.',
    questions: [
      {
        prompt: 'A typical resting membrane potential is approximately...',
        options: ['+30 mV', '0 mV', '\u221265 mV', '\u2212150 mV'],
        answerIndex: 2,
        explanation: 'Most neurons rest near \u221265 mV, a small negative voltage relative to outside.',
      },
      {
        prompt: 'Resting potential is maintained mainly because...',
        options: [
          'Ion concentrations inside and outside are equal',
          'K+ leaks out and negative proteins stay in',
          'The cell is electrically insulated',
          'Sodium floods in constantly',
        ],
        answerIndex: 1,
        explanation: 'Potassium leak plus trapped anions produce the small negative interior.',
      },
      {
        prompt: 'The Na+/K+ pump uses energy to...',
        options: [
          'Open voltage-gated sodium channels',
          'Move Na+ out and K+ in against their gradients',
          'Fire action potentials',
          'Release neurotransmitters',
        ],
        answerIndex: 1,
        explanation: 'The pump trades three Na+ out for two K+ in, maintaining the gradients that make resting potential possible.',
      },
    ],
    xpReward: 18,
    coinReward: 6,
    masteryThreshold: 0.8,
  },
  {
    id: 'A03',
    trackId: 'neuroscience',
    moduleId: 'A-membrane',
    order: 3,
    title: 'Ion channels and membrane currents',
    subtitle: 'The gates that shape every signal',
    estimatedMinutes: 5,
    difficulty: 'beginner',
    prerequisites: ['A02'],
    explanation:
      'Ion channels are proteins that span the membrane and let specific ions pass. Some are always open. Many open in response to voltage changes or chemical signals. When open, they produce a tiny electrical current that nudges the membrane potential.',
    notation: 'I = g (V \u2212 E)',
    keyTerms: ['ion channel', 'conductance', 'reversal potential', 'gating'],
    example:
      'Voltage-gated sodium channels are the spark plugs of the action potential \u2014 they snap open when the membrane depolarises past threshold.',
    intuition: 'Channels are tiny doors. Opening a door lets charge flow and pushes the voltage.',
    whyItMatters:
      'Every formal neuron model talks about conductances. If you can read I = g times (V \u2212 E), you can read most of them.',
    questions: [
      {
        prompt: 'In I = g (V \u2212 E), what does E represent?',
        options: ['Total current', 'The reversal potential of the channel', 'Membrane capacitance', 'Resting input'],
        answerIndex: 1,
        explanation: 'E is the reversal potential, the voltage at which no net current flows through that channel.',
      },
      {
        prompt: 'A voltage-gated channel changes its open probability because of...',
        options: ['Light', 'Local voltage changes', 'Temperature alone', 'Gravity'],
        answerIndex: 1,
        explanation: 'Voltage-gated channels sense the membrane potential and open or close accordingly.',
      },
      {
        prompt: 'Higher conductance g, with everything else equal, means...',
        options: ['Less current flows', 'More current flows', 'The reversal potential shifts', 'The channel reverses direction'],
        answerIndex: 1,
        explanation: 'Current scales linearly with conductance for a fixed driving force.',
      },
    ],
    xpReward: 20,
    coinReward: 7,
    masteryThreshold: 0.8,
  },
  {
    id: 'A04',
    trackId: 'neuroscience',
    moduleId: 'A-spikes',
    order: 4,
    title: 'Action potentials',
    subtitle: 'The all-or-none spike',
    estimatedMinutes: 5,
    difficulty: 'beginner',
    prerequisites: ['A03'],
    explanation:
      'An action potential is a short, stereotyped voltage burst. Once the membrane crosses threshold, voltage-gated sodium channels open and the interior flips positive. Potassium channels then open and the voltage returns, even overshooting briefly before settling.',
    keyTerms: ['threshold', 'depolarisation', 'repolarisation', 'refractory period'],
    example:
      'A single cortical neuron may spike only a few times per second on average, but each spike is a crisp, all-or-none event lasting about a millisecond.',
    intuition: 'Below threshold, nothing. Above threshold, a full reliable pulse.',
    whyItMatters:
      'Neurons talk in spikes. Modelling spikes lets us study how information hops between cells in real time.',
    questions: [
      {
        prompt: 'Action potentials are usually described as...',
        options: ['Graded', 'All-or-none', 'Slow-wave', 'Continuous'],
        answerIndex: 1,
        explanation: 'Either threshold is crossed and a full spike fires, or nothing happens.',
      },
      {
        prompt: 'Depolarisation during a spike is driven mainly by...',
        options: ['Potassium efflux', 'Calcium influx', 'Sodium influx', 'Chloride efflux'],
        answerIndex: 2,
        explanation: 'Voltage-gated sodium channels open, and Na+ rushes in, flipping the membrane briefly positive.',
      },
      {
        prompt: 'The refractory period ensures that...',
        options: [
          'Spikes repeat rapidly and without limit',
          'Spikes travel backwards',
          'A second spike cannot immediately follow the first',
          'All spikes have equal amplitude forever',
        ],
        answerIndex: 2,
        explanation: 'After a spike, the cell cannot immediately fire again, enforcing a maximum firing rate.',
      },
    ],
    xpReward: 20,
    coinReward: 7,
    masteryThreshold: 0.8,
  },
  {
    id: 'A05',
    trackId: 'neuroscience',
    moduleId: 'A-synapses',
    order: 5,
    title: 'Chemical synapses',
    subtitle: 'How neurons pass the message',
    estimatedMinutes: 5,
    difficulty: 'beginner',
    prerequisites: ['A04'],
    explanation:
      'When a spike arrives at an axon terminal, calcium enters and vesicles fuse with the membrane, releasing neurotransmitter into a narrow gap. The molecules bind to receptors on the receiving cell and briefly change its membrane conductance, nudging it toward or away from firing.',
    keyTerms: ['vesicle', 'neurotransmitter', 'receptor', 'synaptic cleft'],
    example:
      'At a hippocampal synapse, a spike can release glutamate in under a millisecond, producing a tiny postsynaptic response just a few millivolts high.',
    intuition: 'Electric becomes chemical becomes electric again \u2014 a three-step handoff.',
    whyItMatters:
      'Synapses are where learning happens. Most models of learning are rules that change synaptic strength.',
    questions: [
      {
        prompt: 'What ion triggers neurotransmitter release at the terminal?',
        options: ['Sodium', 'Chloride', 'Calcium', 'Magnesium'],
        answerIndex: 2,
        explanation: 'Calcium enters through voltage-gated channels and triggers vesicle fusion.',
      },
      {
        prompt: 'Chemical synaptic transmission uses...',
        options: [
          'Direct ion flow between cells',
          'Magnetic fields',
          'Release of neurotransmitter across a small gap',
          'Vibration of the membrane',
        ],
        answerIndex: 2,
        explanation: 'Neurotransmitter diffuses across the synaptic cleft to receptors on the next cell.',
      },
      {
        prompt: 'A postsynaptic receptor typically...',
        options: [
          'Ignores the chemical signal',
          'Opens an ion channel or triggers a signalling cascade',
          'Fires its own action potential',
          'Releases neurotransmitter itself',
        ],
        answerIndex: 1,
        explanation: 'Binding opens ligand-gated channels or activates intracellular messengers.',
      },
    ],
    xpReward: 22,
    coinReward: 8,
    masteryThreshold: 0.8,
  },
  {
    id: 'A06',
    trackId: 'neuroscience',
    moduleId: 'A-synapses',
    order: 6,
    title: 'Excitatory vs inhibitory transmission',
    subtitle: 'Push the spike, pull it back',
    estimatedMinutes: 4,
    difficulty: 'beginner',
    prerequisites: ['A05'],
    explanation:
      'Excitatory synapses push the receiving neuron closer to its firing threshold. Inhibitory synapses push it further away. Most of the balance in a cortical microcircuit is maintained by a mix of both acting on the same cells.',
    keyTerms: ['EPSP', 'IPSP', 'balance', 'glutamate', 'GABA'],
    example:
      'In the cortex, pyramidal cells release glutamate (excitatory) while interneurons release GABA (inhibitory), creating fast gate-keeping dynamics.',
    intuition: 'Every neuron lives with an accelerator and a brake on the same pedal.',
    whyItMatters:
      'Excitation-inhibition balance appears in many models of stability, timing, and decision-making.',
    questions: [
      {
        prompt: 'An EPSP moves the membrane potential...',
        options: ['More negative', 'Toward threshold', 'Away from threshold', 'Nowhere'],
        answerIndex: 1,
        explanation: 'An excitatory postsynaptic potential depolarises the cell, pushing it toward firing.',
      },
      {
        prompt: 'The main excitatory transmitter in cortex is...',
        options: ['GABA', 'Glutamate', 'Dopamine', 'Acetylcholine'],
        answerIndex: 1,
        explanation: 'Glutamate is the dominant excitatory transmitter in the vertebrate CNS.',
      },
      {
        prompt: 'GABA usually has a(n)...',
        options: ['Excitatory role', 'No effect', 'Inhibitory role', 'Delayed excitatory role only'],
        answerIndex: 2,
        explanation: 'GABA opens chloride channels, hyperpolarising or shunting most mature neurons.',
      },
    ],
    xpReward: 20,
    coinReward: 7,
    masteryThreshold: 0.8,
  },
  {
    id: 'A07',
    trackId: 'neuroscience',
    moduleId: 'A-synapses',
    order: 7,
    title: 'Neurotransmitters',
    subtitle: 'A small vocabulary of chemical words',
    estimatedMinutes: 4,
    difficulty: 'beginner',
    prerequisites: ['A06'],
    explanation:
      'Neurotransmitters are the chemicals neurons use to talk. A few are fast and point-to-point, like glutamate and GABA. Others act more broadly, tuning circuits \u2014 dopamine, serotonin, norepinephrine, and acetylcholine.',
    keyTerms: ['glutamate', 'GABA', 'dopamine', 'serotonin', 'acetylcholine'],
    example:
      'Dopamine neurons in the midbrain fire briefly when a reward is better than expected, helping the brain update its predictions.',
    intuition: 'Some transmitters send a message. Others set the mood.',
    whyItMatters:
      'Models of reward learning, attention, and motivation depend on these neuromodulators.',
    questions: [
      {
        prompt: 'Which transmitter is most associated with reward prediction error?',
        options: ['GABA', 'Glutamate', 'Dopamine', 'Histamine'],
        answerIndex: 2,
        explanation: 'Midbrain dopamine neurons carry signals closely related to reward prediction error.',
      },
      {
        prompt: 'Fast point-to-point excitation in cortex uses mostly...',
        options: ['Serotonin', 'Glutamate', 'Noradrenaline', 'Oxytocin'],
        answerIndex: 1,
        explanation: 'Glutamate mediates the majority of fast excitatory transmission.',
      },
      {
        prompt: 'Neuromodulators like serotonin or noradrenaline typically...',
        options: [
          'Act instantly and point-to-point',
          'Change circuit-wide excitability on slower timescales',
          'Produce action potentials directly',
          'Ignore postsynaptic receptors',
        ],
        answerIndex: 1,
        explanation: 'Neuromodulators adjust how circuits respond on slower, broader timescales.',
      },
    ],
    xpReward: 20,
    coinReward: 7,
    masteryThreshold: 0.8,
  },
  {
    id: 'A08',
    trackId: 'neuroscience',
    moduleId: 'A-synapses',
    order: 8,
    title: 'Receptors and neuromodulation',
    subtitle: 'Tuning the conversation',
    estimatedMinutes: 4,
    difficulty: 'beginner',
    prerequisites: ['A07'],
    explanation:
      'Receptors come in two main flavours. Ionotropic receptors are themselves ion channels and react in milliseconds. Metabotropic receptors trigger internal signalling cascades and act over seconds to minutes. Neuromodulators usually use the slower kind to shape how neurons respond to their inputs.',
    keyTerms: ['ionotropic', 'metabotropic', 'G-protein', 'gain control'],
    example:
      'During focused attention, acetylcholine can boost how strongly cortical neurons respond to the same input \u2014 a gain-like effect.',
    intuition: 'Fast gates send signals. Slow cascades change how signals are heard.',
    whyItMatters:
      'Gain and modulation are central ideas in many computational models of attention and context.',
    questions: [
      {
        prompt: 'Ionotropic receptors act on the order of...',
        options: ['Milliseconds', 'Minutes', 'Hours', 'Days'],
        answerIndex: 0,
        explanation: 'They are ion channels themselves and respond within milliseconds.',
      },
      {
        prompt: 'Metabotropic receptors usually...',
        options: [
          'Open instantly',
          'Activate G-proteins and internal cascades',
          'Do not affect cells',
          'Are found only in glia',
        ],
        answerIndex: 1,
        explanation: 'They act through intracellular signalling, producing slower but longer-lasting effects.',
      },
      {
        prompt: 'Neuromodulation mostly changes...',
        options: [
          'Which neurons exist',
          'How neurons respond to inputs they receive',
          'The shape of the skull',
          'The number of synapses in one second',
        ],
        answerIndex: 1,
        explanation: 'Modulators tune gain, excitability, and plasticity rather than carry fast messages.',
      },
    ],
    xpReward: 20,
    coinReward: 7,
    masteryThreshold: 0.8,
  },
  {
    id: 'A09',
    trackId: 'neuroscience',
    moduleId: 'A-support',
    order: 9,
    title: 'Glia and support cells',
    subtitle: 'The other half of the brain',
    estimatedMinutes: 4,
    difficulty: 'beginner',
    prerequisites: ['A01'],
    explanation:
      'Glial cells outnumber neurons in many brain regions. Astrocytes regulate ions and neurotransmitters around synapses. Oligodendrocytes and Schwann cells wrap axons in myelin. Microglia patrol for damage and prune unused connections.',
    keyTerms: ['astrocyte', 'oligodendrocyte', 'microglia', 'myelin'],
    example:
      'Myelinated axons in white matter can conduct spikes many times faster than unmyelinated ones, letting distant brain regions coordinate on millisecond timescales.',
    intuition: 'Glia are not passive. They shape the conditions in which neurons compute.',
    whyItMatters:
      'Models of signal speed, energy, and synaptic reliability depend on glial support.',
    questions: [
      {
        prompt: 'Myelin is produced in the central nervous system by...',
        options: ['Astrocytes', 'Oligodendrocytes', 'Schwann cells', 'Microglia'],
        answerIndex: 1,
        explanation: 'Oligodendrocytes wrap multiple CNS axons in myelin; Schwann cells do so in the peripheral nervous system.',
      },
      {
        prompt: 'Which glial cells prune synapses and respond to damage?',
        options: ['Astrocytes', 'Microglia', 'Schwann cells', 'Neurons'],
        answerIndex: 1,
        explanation: 'Microglia are the brain\u2019s resident immune cells and help sculpt circuits.',
      },
      {
        prompt: 'Astrocytes help by...',
        options: [
          'Firing action potentials at high rates',
          'Regulating ions and transmitters around synapses',
          'Producing cerebrospinal fluid alone',
          'Storing long-term memories',
        ],
        answerIndex: 1,
        explanation: 'Astrocytes buffer ions and recycle transmitters so synapses stay reliable.',
      },
    ],
    xpReward: 18,
    coinReward: 6,
    masteryThreshold: 0.8,
  },
  {
    id: 'A10',
    trackId: 'neuroscience',
    moduleId: 'A-systems',
    order: 10,
    title: 'Sensory systems and receptive fields',
    subtitle: 'What does this neuron care about?',
    estimatedMinutes: 5,
    difficulty: 'beginner',
    prerequisites: ['A04'],
    explanation:
      'A sensory neuron\u2019s receptive field is the region of the world where a stimulus changes its firing rate. In vision it is a patch on the retina. In touch it is a patch of skin. In audition it is a range of frequencies.',
    keyTerms: ['receptive field', 'feature', 'preferred stimulus', 'tuning'],
    example:
      'A V1 neuron in the primary visual cortex often responds best to a bar at a specific orientation in a specific small part of the visual field.',
    intuition: 'Every sensory neuron asks one tiny question and answers with its firing rate.',
    whyItMatters:
      'Receptive fields are the bridge between physical stimuli and neural computation.',
    questions: [
      {
        prompt: 'A receptive field is best described as...',
        options: [
          'A type of synapse',
          'The stimulus region that changes a neuron\u2019s firing',
          'The voltage at which a spike fires',
          'A sensory organ',
        ],
        answerIndex: 1,
        explanation: 'It is the subset of the stimulus space to which a neuron is sensitive.',
      },
      {
        prompt: 'V1 neurons often respond to...',
        options: ['Faces only', 'Oriented edges', 'Words only', 'Pure red colour'],
        answerIndex: 1,
        explanation: 'Many V1 cells are orientation-tuned, a foundational result of visual neuroscience.',
      },
      {
        prompt: 'The preferred stimulus of a neuron is...',
        options: [
          'One that produces no response',
          'One that maximises its firing',
          'The one it can inhibit',
          'The first stimulus it ever saw',
        ],
        answerIndex: 1,
        explanation: 'Its preferred stimulus is the one that drives the highest firing rate.',
      },
    ],
    xpReward: 22,
    coinReward: 8,
    masteryThreshold: 0.8,
  },
  {
    id: 'A11',
    trackId: 'neuroscience',
    moduleId: 'A-systems',
    order: 11,
    title: 'Motor systems',
    subtitle: 'From intention to movement',
    estimatedMinutes: 5,
    difficulty: 'beginner',
    prerequisites: ['A10'],
    explanation:
      'Motor neurons in the spinal cord drive muscles directly, while motor cortex, cerebellum, and basal ganglia plan and refine movement. The final common path is always the motor neuron, whose firing rate sets muscle force.',
    keyTerms: ['motor neuron', 'motor unit', 'motor cortex', 'final common path'],
    example:
      'When you reach for a cup, cortical areas plan the trajectory while spinal motor neurons actually command your arm muscles.',
    intuition: 'Thought becomes action only through the spikes of a motor neuron.',
    whyItMatters:
      'Models of control and motor learning depend on understanding this pipeline.',
    questions: [
      {
        prompt: 'The "final common path" for motor output is the...',
        options: ['Thalamus', 'Spinal motor neuron', 'Hippocampus', 'Retina'],
        answerIndex: 1,
        explanation: 'Every voluntary movement exits the nervous system through spinal motor neurons.',
      },
      {
        prompt: 'Which area fine-tunes and corrects movements using error signals?',
        options: ['Hippocampus', 'Cerebellum', 'Amygdala', 'Olfactory bulb'],
        answerIndex: 1,
        explanation: 'The cerebellum compares intended and actual movement and corrects the difference.',
      },
      {
        prompt: 'A motor unit consists of...',
        options: [
          'One muscle and one thought',
          'One motor neuron and all muscle fibres it controls',
          'Two competing muscles',
          'One synapse in the brain',
        ],
        answerIndex: 1,
        explanation: 'A motor unit is one motor neuron together with the fibres it activates.',
      },
    ],
    xpReward: 22,
    coinReward: 8,
    masteryThreshold: 0.8,
  },
  {
    id: 'A12',
    trackId: 'neuroscience',
    moduleId: 'A-cortex',
    order: 12,
    title: 'Cortex and cortical layers',
    subtitle: 'A thin sheet, six stories deep',
    estimatedMinutes: 5,
    difficulty: 'beginner',
    prerequisites: ['A10'],
    explanation:
      'The cerebral cortex is a folded sheet about 2 to 4 millimetres thick, organised into six layers. Each layer has characteristic cells and connections. Sensory inputs arrive mostly in layer 4, and output projections leave mostly from layers 5 and 6.',
    keyTerms: ['cortex', 'layer 4', 'layer 5', 'column'],
    example:
      'In primary visual cortex, thalamic inputs land in layer 4, feedforward processing climbs through layers 2 and 3, and motor-linked outputs leave via layer 5.',
    intuition: 'Cortex is not a bag of cells. It is a sheet with a wiring diagram.',
    whyItMatters:
      'Most cortical models echo this layered structure, especially models of prediction and feedforward/feedback interactions.',
    questions: [
      {
        prompt: 'Sensory input from the thalamus typically arrives in cortical...',
        options: ['Layer 1', 'Layer 4', 'Layer 6', 'Outside the cortex'],
        answerIndex: 1,
        explanation: 'Layer 4 is the main input layer for sensory cortex.',
      },
      {
        prompt: 'Cortical output to distant areas comes mostly from...',
        options: ['Layer 2', 'Layer 4', 'Layer 5', 'Layer 1'],
        answerIndex: 2,
        explanation: 'Large pyramidal neurons in layer 5 project out to subcortical and other cortical targets.',
      },
      {
        prompt: 'A cortical column roughly refers to...',
        options: [
          'A bone in the skull',
          'A vertical group of cells with shared tuning',
          'A type of glial cell',
          'A brainstem nucleus',
        ],
        answerIndex: 1,
        explanation: 'Columns are vertical clusters of neurons that tend to share functional properties.',
      },
    ],
    xpReward: 24,
    coinReward: 8,
    masteryThreshold: 0.8,
  },
  {
    id: 'A13',
    trackId: 'neuroscience',
    moduleId: 'A-cortex',
    order: 13,
    title: 'Thalamus as relay and gate',
    subtitle: 'The hub at the centre',
    estimatedMinutes: 4,
    difficulty: 'beginner',
    prerequisites: ['A12'],
    explanation:
      'The thalamus sits at the centre of the brain and relays information between the periphery and the cortex. It is not just a passive switchboard: it gates, filters, and synchronises flow depending on behavioural state.',
    keyTerms: ['thalamus', 'relay nucleus', 'LGN', 'gating'],
    example:
      'The lateral geniculate nucleus is a thalamic station that relays visual information from the retina to primary visual cortex.',
    intuition: 'The thalamus is a gate that can open wide during wakefulness and narrow during sleep.',
    whyItMatters:
      'Models of attention and state-dependent processing almost always treat the thalamus as a gain gate.',
    questions: [
      {
        prompt: 'The LGN in the thalamus relays...',
        options: ['Touch', 'Vision', 'Smell', 'Balance'],
        answerIndex: 1,
        explanation: 'The lateral geniculate nucleus is the thalamic relay for vision.',
      },
      {
        prompt: 'The thalamus is best described as...',
        options: ['A passive pipe', 'A state-dependent gate and relay', 'A source of spikes without input', 'A sensor organ'],
        answerIndex: 1,
        explanation: 'Its relays are modulated by state, attention, and inhibitory circuits.',
      },
      {
        prompt: 'During deep sleep, thalamic relay generally becomes...',
        options: ['More open', 'More gated and rhythmic', 'Completely unaffected', 'Replaced by the hippocampus'],
        answerIndex: 1,
        explanation: 'Thalamic circuits produce slow rhythms and reduce feedforward flow during deep sleep.',
      },
    ],
    xpReward: 22,
    coinReward: 8,
    masteryThreshold: 0.8,
  },
  {
    id: 'A14',
    trackId: 'neuroscience',
    moduleId: 'A-subcort',
    order: 14,
    title: 'Basal ganglia and action selection',
    subtitle: 'Choosing what to do next',
    estimatedMinutes: 4,
    difficulty: 'beginner',
    prerequisites: ['A11'],
    explanation:
      'The basal ganglia are a set of deep nuclei involved in selecting and initiating actions. Direct and indirect pathways either release or suppress motor plans, and dopamine shifts the balance between them.',
    keyTerms: ['striatum', 'direct pathway', 'indirect pathway', 'dopamine'],
    example:
      'In Parkinson\u2019s disease, loss of dopamine makes it harder to release actions, slowing movement and making initiation effortful.',
    intuition: 'The basal ganglia are a selector that says "yes, do this one" and "no, not that one".',
    whyItMatters:
      'Reinforcement-learning models of the brain lean heavily on this circuit for selecting actions.',
    questions: [
      {
        prompt: 'The direct pathway of the basal ganglia tends to...',
        options: ['Suppress all movement', 'Release selected actions', 'Record memory only', 'Produce emotions directly'],
        answerIndex: 1,
        explanation: 'The direct pathway reduces inhibition on the thalamus, facilitating action.',
      },
      {
        prompt: 'Dopamine loss in the basal ganglia tends to cause...',
        options: ['Easier action initiation', 'Slowed movement', 'Forgetfulness only', 'Improved coordination'],
        answerIndex: 1,
        explanation: 'Less dopamine makes direct-pathway activation weaker, slowing movement.',
      },
      {
        prompt: 'The striatum is the main input region of the...',
        options: ['Cerebellum', 'Basal ganglia', 'Hippocampus', 'Retina'],
        answerIndex: 1,
        explanation: 'The striatum receives cortical and thalamic input into the basal ganglia.',
      },
    ],
    xpReward: 22,
    coinReward: 8,
    masteryThreshold: 0.8,
  },
  {
    id: 'A15',
    trackId: 'neuroscience',
    moduleId: 'A-subcort',
    order: 15,
    title: 'Cerebellum and error correction',
    subtitle: 'The engine of fine timing',
    estimatedMinutes: 4,
    difficulty: 'beginner',
    prerequisites: ['A11'],
    explanation:
      'The cerebellum contains more neurons than the rest of the brain combined. It uses climbing fibre error signals to teach Purkinje cells how to correct ongoing movements, and it contributes to the timing of many tasks, not just motor ones.',
    keyTerms: ['Purkinje cell', 'climbing fibre', 'parallel fibre', 'error signal'],
    example:
      'When you first learn to catch a ball, your cerebellum updates timing and precision every time you miss, until the movement feels effortless.',
    intuition: 'Errors are not punishment. They are teaching signals.',
    whyItMatters:
      'Classic theories of supervised learning in biology draw inspiration from cerebellar circuits.',
    questions: [
      {
        prompt: 'Climbing fibres in the cerebellum are thought to carry...',
        options: ['Reward signals', 'Error-like teaching signals', 'Sensory brightness', 'Voluntary decisions'],
        answerIndex: 1,
        explanation: 'Climbing fibres convey strong, sparse events that look like teaching signals.',
      },
      {
        prompt: 'Purkinje cells are the...',
        options: [
          'Input cells of the cerebellum',
          'Only output cells of the cerebellar cortex',
          'Glia',
          'Motor neurons',
        ],
        answerIndex: 1,
        explanation: 'Purkinje cells send the sole output from the cerebellar cortex.',
      },
      {
        prompt: 'The cerebellum is critical for...',
        options: ['Emotion only', 'Fine timing and motor correction', 'Color vision only', 'Blood circulation'],
        answerIndex: 1,
        explanation: 'It fine-tunes timing and precision for movement (and more).',
      },
    ],
    xpReward: 22,
    coinReward: 8,
    masteryThreshold: 0.8,
  },
  {
    id: 'A16',
    trackId: 'neuroscience',
    moduleId: 'A-memory',
    order: 16,
    title: 'Hippocampus and episodic memory',
    subtitle: 'Place, time, and story',
    estimatedMinutes: 5,
    difficulty: 'beginner',
    prerequisites: ['A12'],
    explanation:
      'The hippocampus helps bind "what", "where", and "when" into memories we can later replay. Place cells fire at specific locations, and during rest, sequences of them reactivate, as if the brain is rehearsing paths it has taken.',
    keyTerms: ['place cell', 'CA3', 'CA1', 'replay'],
    example:
      'In a maze, a rat\u2019s hippocampal place cells fire when the animal is in specific spots, collectively forming a map of the environment.',
    intuition: 'The hippocampus writes short, vivid stories the cortex later reads and keeps.',
    whyItMatters:
      'Models of memory, navigation, and offline learning start here.',
    questions: [
      {
        prompt: 'Place cells fire when an animal is in...',
        options: ['Any location', 'A specific location', 'Only at night', 'Only near walls'],
        answerIndex: 1,
        explanation: 'Place cells have receptive fields in space and fire when the animal enters them.',
      },
      {
        prompt: 'Hippocampal replay tends to occur during...',
        options: ['Only active running', 'Rest and sleep', 'Only REM sleep', 'Only during loud noises'],
        answerIndex: 1,
        explanation: 'Sequential replay often happens during quiet rest and sleep, and supports memory consolidation.',
      },
      {
        prompt: 'The hippocampus is most associated with...',
        options: ['Fine motor control', 'Binding episodic memories', 'Breathing rhythm', 'Balance'],
        answerIndex: 1,
        explanation: 'Damage to the hippocampus impairs the formation of new episodic memories.',
      },
    ],
    xpReward: 24,
    coinReward: 9,
    masteryThreshold: 0.8,
  },
  {
    id: 'A17',
    trackId: 'neuroscience',
    moduleId: 'A-memory',
    order: 17,
    title: 'Amygdala and emotion',
    subtitle: 'Fast tags for what matters',
    estimatedMinutes: 4,
    difficulty: 'beginner',
    prerequisites: ['A16'],
    explanation:
      'The amygdala is a small group of nuclei in the temporal lobe that tags stimuli with emotional significance, especially threat and reward. It modulates memory and attention so that important events stick.',
    keyTerms: ['amygdala', 'fear', 'salience', 'consolidation'],
    example:
      'A sudden loud sound activates the amygdala, which can speed heart rate, focus attention, and strengthen the memory of what just happened.',
    intuition: 'The amygdala says "mark this moment \u2014 it matters".',
    whyItMatters:
      'Many models of emotional learning, particularly fear conditioning, are grounded in amygdala circuits.',
    questions: [
      {
        prompt: 'The amygdala is most associated with...',
        options: ['Fine motor control', 'Tagging emotional significance', 'Breathing rhythm', 'Skin colour'],
        answerIndex: 1,
        explanation: 'It assigns emotional value, particularly for threat and salient events.',
      },
      {
        prompt: 'Fear conditioning experiments depend heavily on the...',
        options: ['Cerebellum', 'Amygdala', 'Retina', 'Thalamus only'],
        answerIndex: 1,
        explanation: 'Amygdala circuits are essential for forming conditioned fear.',
      },
      {
        prompt: 'Emotionally significant events tend to be remembered...',
        options: ['Worse than neutral ones', 'The same as neutral ones', 'Better than neutral ones', 'Not at all'],
        answerIndex: 2,
        explanation: 'Amygdala activity boosts consolidation, strengthening memories of salient events.',
      },
    ],
    xpReward: 22,
    coinReward: 8,
    masteryThreshold: 0.8,
  },
  {
    id: 'A18',
    trackId: 'neuroscience',
    moduleId: 'A-cognition',
    order: 18,
    title: 'Attention and executive control',
    subtitle: 'The spotlight and the conductor',
    estimatedMinutes: 5,
    difficulty: 'beginner',
    prerequisites: ['A12'],
    explanation:
      'Attention selects which signals the brain processes more fully, and executive control coordinates goals and actions. Prefrontal cortex plays a central role, interacting with parietal and subcortical areas to maintain goals and shift focus.',
    keyTerms: ['prefrontal cortex', 'selective attention', 'working memory', 'cognitive control'],
    example:
      'Finding a friend in a crowd relies on the prefrontal cortex holding their features in mind and biasing visual processing toward matching patterns.',
    intuition: 'Attention is not noticing more. It is noticing the right thing more.',
    whyItMatters:
      'Models of attention combine gain control, gating, and working memory loops.',
    questions: [
      {
        prompt: 'Prefrontal cortex is most associated with...',
        options: ['Primary touch sensation', 'Goal maintenance and cognitive control', 'Breathing', 'Sleep rhythms only'],
        answerIndex: 1,
        explanation: 'Prefrontal cortex maintains and manipulates information relevant to current goals.',
      },
      {
        prompt: 'Attention typically changes neural responses by...',
        options: [
          'Replacing them with new neurons',
          'Adjusting gain and selectivity',
          'Shutting off the thalamus permanently',
          'Disconnecting synapses',
        ],
        answerIndex: 1,
        explanation: 'Attentional effects include gain boosts, reduced noise, and sharper tuning.',
      },
      {
        prompt: 'Working memory can be thought of as...',
        options: [
          'A long-term storage vault',
          'A short-term scratch pad supported by ongoing activity',
          'A sensory organ',
          'A type of emotion',
        ],
        answerIndex: 1,
        explanation: 'Working memory is a transient store often linked to sustained neural activity.',
      },
    ],
    xpReward: 24,
    coinReward: 9,
    masteryThreshold: 0.8,
  },
  {
    id: 'A19',
    trackId: 'neuroscience',
    moduleId: 'A-cognition',
    order: 19,
    title: 'Sleep, rhythms, and oscillations',
    subtitle: 'When the brain rewrites itself',
    estimatedMinutes: 5,
    difficulty: 'beginner',
    prerequisites: ['A18'],
    explanation:
      'The brain is never truly idle. It cycles through rhythms from slow waves in deep sleep to faster gamma activity in wakefulness. These rhythms organise communication and support memory consolidation.',
    keyTerms: ['NREM sleep', 'REM sleep', 'slow oscillation', 'gamma rhythm'],
    example:
      'During deep sleep, slow oscillations coordinate reactivation of recent experiences, helping transfer them into more durable cortical memory.',
    intuition: 'Rhythms are the brain\u2019s schedule. Different bands mean different work shifts.',
    whyItMatters:
      'Models of sleep-based consolidation rely on oscillatory coupling between hippocampus and cortex.',
    questions: [
      {
        prompt: 'Slow oscillations are most prominent during...',
        options: ['REM sleep only', 'Deep NREM sleep', 'Focused attention', 'Physical exercise'],
        answerIndex: 1,
        explanation: 'Slow oscillations dominate deep non-REM sleep stages.',
      },
      {
        prompt: 'Gamma rhythms are often associated with...',
        options: ['Deep sleep', 'Active processing and perception', 'Unconsciousness', 'Muscle twitches only'],
        answerIndex: 1,
        explanation: 'Gamma activity tends to accompany active, focused neural processing.',
      },
      {
        prompt: 'Memory consolidation during sleep involves...',
        options: [
          'Erasing recent events to save space',
          'Reactivating recent experiences in coordination with cortex',
          'Randomly generating new memories',
          'Blocking all hippocampal activity',
        ],
        answerIndex: 1,
        explanation: 'Coordinated reactivation helps stabilise recent memories in cortical networks.',
      },
    ],
    xpReward: 24,
    coinReward: 9,
    masteryThreshold: 0.8,
  },
  {
    id: 'A20',
    trackId: 'neuroscience',
    moduleId: 'A-methods',
    order: 20,
    title: 'Modern neuroscience methods',
    subtitle: 'Electrophysiology, calcium imaging, fMRI, optogenetics',
    estimatedMinutes: 6,
    difficulty: 'beginner',
    prerequisites: ['A04'],
    explanation:
      'Neuroscientists have a growing toolkit. Electrophysiology records electrical signals directly from neurons. Calcium imaging uses fluorescent indicators to visualise many neurons at once. fMRI maps blood-flow changes across the whole brain. Optogenetics uses light to turn specific neurons on or off.',
    keyTerms: ['ephys', 'calcium imaging', 'fMRI', 'optogenetics'],
    example:
      'In a single modern experiment, researchers may image thousands of neurons with calcium imaging while using optogenetics to briefly silence a subset to see how others respond.',
    intuition: 'Different methods trade speed, coverage, and specificity \u2014 no single tool sees everything.',
    whyItMatters:
      'Understanding what a method can and cannot measure is essential to interpreting a model or a paper.',
    questions: [
      {
        prompt: 'fMRI measures which signal most directly?',
        options: ['Single spikes', 'Blood-flow changes related to activity', 'Neurotransmitter levels', 'DNA expression'],
        answerIndex: 1,
        explanation: 'fMRI tracks the BOLD signal, a proxy for local activity via blood oxygenation.',
      },
      {
        prompt: 'Optogenetics lets researchers...',
        options: [
          'Measure genes in the blood',
          'Turn specific neurons on or off with light',
          'See inside a closed skull with radiation',
          'Record muscle force only',
        ],
        answerIndex: 1,
        explanation: 'Light-sensitive channels like channelrhodopsin allow targeted neuronal control.',
      },
      {
        prompt: 'Calcium imaging is attractive because it...',
        options: [
          'Measures single spike timing perfectly',
          'Lets you watch many neurons at once with cell-type specificity',
          'Works without any indicator',
          'Requires no optics or microscope',
        ],
        answerIndex: 1,
        explanation: 'Calcium imaging scales to many neurons simultaneously, though its time resolution is coarser than ephys.',
      },
    ],
    xpReward: 26,
    coinReward: 10,
    masteryThreshold: 0.8,
  },
];
