import { Lesson } from './types';

/**
 * Track D — AI Basics. 30 lessons covering theory, model families, choosing
 * and building models, training, inference, and refining (fine-tuning, RAG).
 * Sequentially unlocked by completion of prior lessons.
 */
export const trackDLessons: Lesson[] = [
  {
    id: 'D01',
    trackId: 'aibasis',
    moduleId: 'D-foundations',
    order: 1,
    title: 'What is artificial intelligence?',
    subtitle: 'A working definition',
    estimatedMinutes: 4,
    difficulty: 'intro',
    prerequisites: [],
    explanation:
      'Artificial intelligence is the field of building systems that perform tasks usually associated with human intelligence — perceiving, reasoning, learning, and deciding. In practice, today’s AI is dominated by machine learning: algorithms that improve their behaviour from data rather than being told every rule.',
    keyTerms: ['AI', 'machine learning', 'data-driven', 'task'],
    example:
      'A spam filter that learns from millions of labelled emails which features predict junk is a classic AI system.',
    intuition: 'Modern AI = patterns learned from data, not rules typed by hand.',
    whyItMatters:
      'Defining the field clearly is the first step to choosing the right tool for a problem rather than chasing buzzwords.',
    questions: [
      {
        prompt: 'Which best describes today’s AI in practice?',
        options: [
          'Hand-coded rules for every situation',
          'Algorithms that learn behaviour from data',
          'A single universal program',
          'Random number generators',
        ],
        answerIndex: 1,
        explanation: 'Most modern AI is machine learning — systems that improve from data.',
      },
      {
        prompt: 'A spam filter trained on labelled emails is an example of...',
        options: ['A rule-based expert system only', 'A learned classifier', 'A search engine', 'A database lookup'],
        answerIndex: 1,
        explanation: 'It learns from labelled data, which is a learned classifier.',
      },
      {
        prompt: 'AI in 2024+ is dominated by which paradigm?',
        options: ['Symbolic logic', 'Machine learning', 'Brute-force search', 'None of the above'],
        answerIndex: 1,
        explanation: 'Machine learning, especially deep learning, dominates current AI.',
      },
    ],
    xpReward: 14,
    coinReward: 5,
    masteryThreshold: 0.8,
  },
  {
    id: 'D02',
    trackId: 'aibasis',
    moduleId: 'D-foundations',
    order: 2,
    title: 'Machine learning vs rule-based AI',
    subtitle: 'Two ways to make a machine smart',
    estimatedMinutes: 4,
    difficulty: 'intro',
    prerequisites: ['D01'],
    explanation:
      'Rule-based AI follows explicit if-then rules written by humans. Machine learning instead fits parameters of a flexible model to data. Rules are transparent but brittle; ML is flexible but data-hungry and harder to explain.',
    keyTerms: ['rule-based', 'machine learning', 'data', 'parameters'],
    example:
      'A chess engine using hand-tuned heuristics is rule-based. AlphaZero, which learned chess by self-play, is ML.',
    intuition: 'Rules: humans encode the logic. ML: data shapes the parameters.',
    whyItMatters:
      'Picking between explicit rules and learning is the first design choice in any AI project.',
    questions: [
      {
        prompt: 'A rule-based system is best when...',
        options: [
          'You have huge data and unclear rules',
          'The rules are well known and stable',
          'You need to learn from raw images',
          'You want unsupervised behaviour',
        ],
        answerIndex: 1,
        explanation: 'Stable, well-known logic suits explicit rules.',
      },
      {
        prompt: 'Machine learning is preferable when...',
        options: [
          'Rules are hard to write and data is plentiful',
          'There is no data',
          'Determinism is mandatory',
          'You forbid any approximation',
        ],
        answerIndex: 0,
        explanation: 'ML shines when patterns are real but writing rules is hopeless.',
      },
      {
        prompt: 'A weakness of pure ML is that it is...',
        options: ['Always faster than rules', 'Often less transparent', 'Free to train', 'Always correct'],
        answerIndex: 1,
        explanation: 'Learned models are typically harder to interpret than human-written rules.',
      },
    ],
    xpReward: 14,
    coinReward: 5,
    masteryThreshold: 0.8,
  },
  {
    id: 'D03',
    trackId: 'aibasis',
    moduleId: 'D-foundations',
    order: 3,
    title: 'Supervised, unsupervised, reinforcement',
    subtitle: 'The three big learning regimes',
    estimatedMinutes: 5,
    difficulty: 'intro',
    prerequisites: ['D02'],
    explanation:
      'Supervised learning fits inputs to known target labels. Unsupervised learning looks for structure in unlabelled data. Reinforcement learning learns by acting in an environment and receiving rewards. Most modern systems combine at least two of these.',
    keyTerms: ['supervised', 'unsupervised', 'reinforcement', 'labels'],
    example:
      'Classifying photos into "cat" or "dog" is supervised. Grouping similar customers is unsupervised. A robot learning to walk by reward is reinforcement.',
    intuition: 'Labels = supervised. No labels = unsupervised. Reward = reinforcement.',
    whyItMatters:
      'Naming the regime tells you what data and what evaluation you need.',
    questions: [
      {
        prompt: 'Which is supervised learning?',
        options: [
          'Predicting house price from labelled examples',
          'Clustering songs into genres without labels',
          'A robot maximising reward',
          'A random walk',
        ],
        answerIndex: 0,
        explanation: 'Supervised learning needs labelled targets.',
      },
      {
        prompt: 'Reinforcement learning is characterised by...',
        options: ['Static labelled datasets', 'Reward signals from an environment', 'No optimisation', 'Random outputs'],
        answerIndex: 1,
        explanation: 'RL learns from rewards earned while acting.',
      },
      {
        prompt: 'Unsupervised learning works on...',
        options: ['Labelled data only', 'Reward signals only', 'Unlabelled data, looking for structure', 'Nothing'],
        answerIndex: 2,
        explanation: 'Unsupervised methods find patterns without explicit labels.',
      },
    ],
    xpReward: 16,
    coinReward: 5,
    masteryThreshold: 0.8,
  },
  {
    id: 'D04',
    trackId: 'aibasis',
    moduleId: 'D-theory',
    order: 4,
    title: 'Features, labels, and datasets',
    subtitle: 'The raw material of learning',
    estimatedMinutes: 4,
    difficulty: 'beginner',
    prerequisites: ['D03'],
    explanation:
      'A dataset is a collection of examples. Each example has features (the inputs the model sees) and, in supervised learning, a label (the target answer). Good features and clean labels matter more than fancy models.',
    notation: 'D = {(x_i, y_i)} for i = 1..N',
    keyTerms: ['feature', 'label', 'example', 'dataset'],
    example:
      'For predicting cancer from an image: features = pixel values, label = "tumor" or "no tumor".',
    intuition: 'Garbage in, garbage out. Most of the work is in the data.',
    whyItMatters:
      'No model can rescue badly defined features or noisy labels — understanding the data comes first.',
    questions: [
      {
        prompt: 'In a supervised dataset, the label is...',
        options: ['The input', 'The target the model should predict', 'A hyperparameter', 'A loss value'],
        answerIndex: 1,
        explanation: 'Labels are the supervised target.',
      },
      {
        prompt: 'A feature is...',
        options: ['Any model parameter', 'A piece of input information', 'The training loop', 'A reward'],
        answerIndex: 1,
        explanation: 'Features describe the input.',
      },
      {
        prompt: 'A common ML lesson is that...',
        options: [
          'Architecture matters more than data quality',
          'Data quality and features often dominate model choice',
          'Labels do not matter',
          'Datasets are unnecessary',
        ],
        answerIndex: 1,
        explanation: 'Better data usually beats fancier models.',
      },
    ],
    xpReward: 16,
    coinReward: 6,
    masteryThreshold: 0.8,
  },
  {
    id: 'D05',
    trackId: 'aibasis',
    moduleId: 'D-theory',
    order: 5,
    title: 'Loss functions',
    subtitle: 'The score we try to lower',
    estimatedMinutes: 5,
    difficulty: 'beginner',
    prerequisites: ['D04'],
    explanation:
      'A loss function measures how wrong the model is on a given example or batch. Training shrinks this loss. Common choices include mean squared error for regression and cross-entropy for classification.',
    notation: 'MSE = mean (y − ŷ)²     CE = −Σ y log ŷ',
    keyTerms: ['loss', 'MSE', 'cross-entropy', 'objective'],
    example:
      'Predicting house prices with MSE penalises large errors more than small ones because of the square.',
    intuition: 'Loss is the dial we push down by training.',
    whyItMatters:
      'The chosen loss silently encodes what you actually want — the wrong loss optimises the wrong thing.',
    questions: [
      {
        prompt: 'For multi-class classification, a standard loss is...',
        options: ['Mean squared error', 'Cross-entropy', 'Accuracy', 'Hamming distance'],
        answerIndex: 1,
        explanation: 'Cross-entropy is the standard for predicted class probabilities.',
      },
      {
        prompt: 'Training reduces...',
        options: ['Number of parameters', 'Loss on the training data', 'Memory use', 'Dataset size'],
        answerIndex: 1,
        explanation: 'Optimisation pushes the loss down.',
      },
      {
        prompt: 'MSE penalises large errors...',
        options: ['Less than small ones', 'About the same', 'More than small ones', 'Not at all'],
        answerIndex: 2,
        explanation: 'Squaring inflates the cost of larger residuals.',
      },
    ],
    xpReward: 18,
    coinReward: 6,
    masteryThreshold: 0.8,
  },
  {
    id: 'D06',
    trackId: 'aibasis',
    moduleId: 'D-theory',
    order: 6,
    title: 'Bias-variance trade-off',
    subtitle: 'Why simple and complex models both fail',
    estimatedMinutes: 5,
    difficulty: 'beginner',
    prerequisites: ['D05'],
    explanation:
      'Bias is error from a model being too simple to capture the truth. Variance is error from being too sensitive to which data it saw. A good model balances these: enough capacity to fit, not so much that it memorises noise.',
    notation: 'expected error ≈ bias² + variance + irreducible noise',
    keyTerms: ['bias', 'variance', 'capacity', 'generalisation'],
    example:
      'A straight line fitting curved data has high bias. A 30-degree polynomial fitting 30 points has high variance.',
    intuition: 'Bias = consistently wrong. Variance = inconsistent across data.',
    whyItMatters:
      'Almost every modelling decision — model size, regularisation, data amount — is a bias-variance trade.',
    questions: [
      {
        prompt: 'A high-bias model typically...',
        options: ['Memorises training data', 'Underfits and misses the pattern', 'Has perfect accuracy', 'Has huge variance'],
        answerIndex: 1,
        explanation: 'High bias = too simple = underfits.',
      },
      {
        prompt: 'A high-variance model typically...',
        options: ['Overfits training noise', 'Underfits everything', 'Ignores data', 'Has zero parameters'],
        answerIndex: 0,
        explanation: 'High variance = too sensitive = overfits.',
      },
      {
        prompt: 'Adding more training data tends to...',
        options: ['Increase variance', 'Reduce variance', 'Increase bias', 'Have no effect'],
        answerIndex: 1,
        explanation: 'More data stabilises estimates and reduces variance.',
      },
    ],
    xpReward: 20,
    coinReward: 7,
    masteryThreshold: 0.8,
  },
  {
    id: 'D07',
    trackId: 'aibasis',
    moduleId: 'D-theory',
    order: 7,
    title: 'Overfitting and regularisation',
    subtitle: 'Stopping a model from memorising',
    estimatedMinutes: 5,
    difficulty: 'beginner',
    prerequisites: ['D06'],
    explanation:
      'Overfitting happens when a model fits training data well but fails on new data. Regularisation discourages overfitting by penalising complexity — with weight decay (L2), L1 sparsity, dropout, early stopping, or data augmentation.',
    notation: 'loss + λ ‖w‖²',
    keyTerms: ['overfitting', 'regularisation', 'L1', 'L2', 'dropout'],
    example:
      'A neural net memorising training images can be tamed by adding dropout layers and weight decay.',
    intuition: 'Make it harder for the model to win by cheating on the training set.',
    whyItMatters:
      'Real-world value comes from generalisation. Regularisation is the main tool to get it.',
    questions: [
      {
        prompt: 'Overfitting means...',
        options: [
          'Great training loss but poor test performance',
          'Bad training loss',
          'No loss at all',
          'A small dataset',
        ],
        answerIndex: 0,
        explanation: 'It is good on train, bad on test — the gap is the symptom.',
      },
      {
        prompt: 'Dropout fights overfitting by...',
        options: [
          'Doubling parameters',
          'Randomly disabling units during training',
          'Training longer',
          'Increasing learning rate',
        ],
        answerIndex: 1,
        explanation: 'Dropout adds noise that prevents fragile co-adaptations.',
      },
      {
        prompt: 'L2 regularisation adds a term proportional to...',
        options: ['Sum of weights', 'Sum of absolute weights', 'Sum of squared weights', 'Loss'],
        answerIndex: 2,
        explanation: 'L2 penalises ‖w‖².',
      },
    ],
    xpReward: 20,
    coinReward: 7,
    masteryThreshold: 0.8,
  },
  {
    id: 'D08',
    trackId: 'aibasis',
    moduleId: 'D-models',
    order: 8,
    title: 'Linear and logistic regression',
    subtitle: 'The smallest models that still work',
    estimatedMinutes: 5,
    difficulty: 'beginner',
    prerequisites: ['D07'],
    explanation:
      'Linear regression predicts a continuous output as a weighted sum of features. Logistic regression squashes this sum through a sigmoid to predict a probability for binary classification. Both are easy to fit and interpret.',
    notation: 'ŷ = w·x + b ;  p = σ(w·x + b)',
    keyTerms: ['linear regression', 'logistic regression', 'sigmoid', 'weights'],
    example:
      'Predicting tumour malignancy from a few biomarkers with logistic regression often beats fancier models on small data.',
    intuition: 'A line for numbers, a squashed line for probabilities.',
    whyItMatters:
      'They are the strong baselines every project should beat before reaching for deep models.',
    questions: [
      {
        prompt: 'Logistic regression outputs...',
        options: ['Any real number', 'A probability between 0 and 1', 'A class index only', 'A vector of one-hots'],
        answerIndex: 1,
        explanation: 'The sigmoid maps to (0, 1).',
      },
      {
        prompt: 'Linear regression assumes the relationship between features and target is...',
        options: ['Strongly non-linear', 'Approximately linear', 'Random', 'Periodic'],
        answerIndex: 1,
        explanation: 'A linear functional form is the modelling choice.',
      },
      {
        prompt: 'A good first step on a new tabular problem is to...',
        options: [
          'Train a transformer',
          'Try a simple linear or logistic baseline first',
          'Skip data inspection',
          'Use only KNN',
        ],
        answerIndex: 1,
        explanation: 'Strong baselines protect you from chasing complexity that does not pay off.',
      },
    ],
    xpReward: 22,
    coinReward: 8,
    masteryThreshold: 0.8,
  },
  {
    id: 'D09',
    trackId: 'aibasis',
    moduleId: 'D-models',
    order: 9,
    title: 'Decision trees and random forests',
    subtitle: 'Splits, leaves, and ensembles',
    estimatedMinutes: 5,
    difficulty: 'beginner',
    prerequisites: ['D08'],
    explanation:
      'A decision tree splits the feature space recursively to make a prediction in each leaf. A random forest averages many trees, each trained on bootstrapped data and random feature subsets. Forests are accurate, fast, and surprisingly strong on tabular data.',
    keyTerms: ['decision tree', 'split', 'random forest', 'bagging'],
    example:
      'A random forest predicting credit default outperforms many neural nets on standard financial tabular data.',
    intuition: 'A tree asks 20 questions; a forest asks them many ways and averages.',
    whyItMatters:
      'For tabular problems, trees and gradient-boosted variants remain the workhorses.',
    questions: [
      {
        prompt: 'A random forest reduces variance by...',
        options: ['Using one giant tree', 'Averaging many decorrelated trees', 'Pruning everything', 'Skipping splits'],
        answerIndex: 1,
        explanation: 'Bagging plus feature randomness decorrelates the ensemble.',
      },
      {
        prompt: 'Decision trees naturally handle...',
        options: ['Only continuous features', 'Mixed feature types and non-linear splits', 'Nothing', 'Sequences only'],
        answerIndex: 1,
        explanation: 'Trees can split on numeric or categorical features and capture non-linearity.',
      },
      {
        prompt: 'On classic tabular benchmarks, gradient-boosted trees are often...',
        options: ['Far worse than deep nets', 'Highly competitive', 'Never used', 'Untrainable'],
        answerIndex: 1,
        explanation: 'Boosted trees still hold their own on many tabular tasks.',
      },
    ],
    xpReward: 22,
    coinReward: 8,
    masteryThreshold: 0.8,
  },
  {
    id: 'D10',
    trackId: 'aibasis',
    moduleId: 'D-models',
    order: 10,
    title: 'Neural networks',
    subtitle: 'Stacked linear-plus-nonlinear layers',
    estimatedMinutes: 6,
    difficulty: 'beginner',
    prerequisites: ['D09'],
    explanation:
      'A neural network is a chain of linear transformations and non-linear activations. With enough layers and parameters, it can approximate complicated functions. The non-linearity is the key — stacking pure linear layers reduces to a single linear layer.',
    notation: 'h = σ(W x + b)',
    keyTerms: ['layer', 'activation', 'ReLU', 'feedforward'],
    example:
      'A two-layer network with ReLU can already classify handwritten digits at high accuracy.',
    intuition: 'Linear, then bend, then linear, then bend — a flexible function builder.',
    whyItMatters:
      'Most modern AI is some flavour of neural network, so this is the basic vocabulary.',
    questions: [
      {
        prompt: 'Without non-linear activations, a deep network reduces to...',
        options: ['A single linear function', 'A polynomial', 'A tree', 'A random forest'],
        answerIndex: 0,
        explanation: 'Composing linear maps gives one linear map.',
      },
      {
        prompt: 'A common non-linearity is...',
        options: ['Identity', 'ReLU', 'Constant 0', 'Random'],
        answerIndex: 1,
        explanation: 'ReLU(x) = max(0, x) is widely used.',
      },
      {
        prompt: 'Width and depth give a neural network...',
        options: ['No extra power', 'Capacity to fit complex functions', 'Less variance always', 'Infinite training speed'],
        answerIndex: 1,
        explanation: 'More parameters mean more functions can be represented.',
      },
    ],
    xpReward: 24,
    coinReward: 9,
    masteryThreshold: 0.8,
  },
  {
    id: 'D11',
    trackId: 'aibasis',
    moduleId: 'D-models',
    order: 11,
    title: 'Convolutional neural networks',
    subtitle: 'Sliding filters for grids',
    estimatedMinutes: 6,
    difficulty: 'beginner',
    prerequisites: ['D10'],
    explanation:
      'A convolutional layer slides small filters across an input grid (like an image), reusing the same weights everywhere. This builds in translation equivariance and dramatically reduces parameter counts compared to a dense layer.',
    keyTerms: ['convolution', 'filter', 'pooling', 'translation equivariance'],
    example:
      'Modern image classifiers stack convolutions, normalisations, and pooling to recognise thousands of object categories.',
    intuition: 'Same little detector, applied everywhere on the image.',
    whyItMatters:
      'CNNs were the first deep models to dominate vision and remain core to many systems.',
    questions: [
      {
        prompt: 'Convolutional layers exploit...',
        options: ['Random shuffling', 'Translation structure of the input', 'Only colour', 'Word order'],
        answerIndex: 1,
        explanation: 'Weights shared across positions encode translation structure.',
      },
      {
        prompt: 'A pooling layer typically...',
        options: ['Increases spatial resolution', 'Reduces spatial resolution', 'Adds parameters', 'Computes a loss'],
        answerIndex: 1,
        explanation: 'Pooling downsamples the spatial dimensions.',
      },
      {
        prompt: 'CNNs are most natural for...',
        options: ['Sparse text tokens only', 'Grid-like data such as images', 'Single scalars', 'Audio waveforms only'],
        answerIndex: 1,
        explanation: 'They are designed for grid-structured data.',
      },
    ],
    xpReward: 24,
    coinReward: 9,
    masteryThreshold: 0.8,
  },
  {
    id: 'D12',
    trackId: 'aibasis',
    moduleId: 'D-models',
    order: 12,
    title: 'Recurrent networks and sequences',
    subtitle: 'Remembering across time',
    estimatedMinutes: 6,
    difficulty: 'beginner',
    prerequisites: ['D10'],
    explanation:
      'Recurrent neural networks process sequences one step at a time and carry a hidden state forward. Variants such as LSTMs and GRUs add gating to keep useful information across longer time spans.',
    notation: 'h_t = f(h_{t−1}, x_t)',
    keyTerms: ['RNN', 'hidden state', 'LSTM', 'GRU'],
    example:
      'Before transformers, LSTMs powered most translation, speech, and language models.',
    intuition: 'A function that updates its memory step by step.',
    whyItMatters:
      'Many time-series and signal-processing problems still benefit from recurrent structure.',
    questions: [
      {
        prompt: 'An RNN’s hidden state lets it...',
        options: ['Forget the input', 'Carry information across time steps', 'Skip computation', 'Run in parallel only'],
        answerIndex: 1,
        explanation: 'The hidden state is the recurrent memory.',
      },
      {
        prompt: 'LSTMs were designed to fight...',
        options: ['Overfitting only', 'Vanishing gradients in long sequences', 'Slow inference only', 'GPU memory'],
        answerIndex: 1,
        explanation: 'Gating helps gradients flow over long sequences.',
      },
      {
        prompt: 'Compared to a CNN, an RNN better fits...',
        options: ['2D images', 'Sequential data with temporal order', 'Static tables', 'Constant signals'],
        answerIndex: 1,
        explanation: 'RNNs are built for ordered sequences.',
      },
    ],
    xpReward: 24,
    coinReward: 9,
    masteryThreshold: 0.8,
  },
  {
    id: 'D13',
    trackId: 'aibasis',
    moduleId: 'D-models',
    order: 13,
    title: 'Transformers and attention',
    subtitle: 'Tokens looking at each other',
    estimatedMinutes: 6,
    difficulty: 'intermediate',
    prerequisites: ['D12'],
    explanation:
      'A transformer processes a sequence of tokens by computing attention: each token forms queries, keys, and values, and looks at every other token. This avoids recurrence and exposes massive parallelism, which scales beautifully on modern hardware.',
    notation: 'Attention(Q, K, V) = softmax(QKᵀ / √d) V',
    keyTerms: ['transformer', 'self-attention', 'token', 'context window'],
    example:
      'Large language models such as GPT and Claude are stacked transformer blocks trained on enormous text corpora.',
    intuition: 'Every token reads every other token in the sequence and decides what to copy.',
    whyItMatters:
      'Transformers underlie nearly all modern foundation models for text, code, vision, and beyond.',
    questions: [
      {
        prompt: 'Self-attention computes...',
        options: [
          'A single linear function',
          'Weighted combinations across all tokens in the input',
          'Random projections only',
          'A pooling layer',
        ],
        answerIndex: 1,
        explanation: 'Each token attends to others through Q·Kᵀ weights.',
      },
      {
        prompt: 'Compared to RNNs, transformers are usually...',
        options: ['Less parallel', 'More parallel during training', 'Only useful for images', 'Recurrent in nature'],
        answerIndex: 1,
        explanation: 'No recurrence means whole sequences process in parallel.',
      },
      {
        prompt: 'Modern large language models are mostly built from...',
        options: ['LSTMs', 'Decision trees', 'Stacked transformer blocks', 'Hand-written rules'],
        answerIndex: 2,
        explanation: 'LLMs are deep transformers.',
      },
    ],
    xpReward: 26,
    coinReward: 10,
    masteryThreshold: 0.8,
  },
  {
    id: 'D14',
    trackId: 'aibasis',
    moduleId: 'D-models',
    order: 14,
    title: 'Generative models',
    subtitle: 'Sampling new things from data',
    estimatedMinutes: 6,
    difficulty: 'intermediate',
    prerequisites: ['D13'],
    explanation:
      'Generative models learn the distribution of data so they can sample new examples. Major families include autoregressive models (predict next token), diffusion models (denoise), and variational autoencoders (compress and decode).',
    keyTerms: ['generative', 'autoregressive', 'diffusion', 'VAE'],
    example:
      'Image generators such as Stable Diffusion are diffusion models. Language models like GPT are autoregressive.',
    intuition: 'A discriminative model decides; a generative model imagines.',
    whyItMatters:
      'Generative AI is reshaping content creation, simulation, and even scientific discovery.',
    questions: [
      {
        prompt: 'An autoregressive language model predicts...',
        options: ['All tokens at once', 'The next token from the previous ones', 'Pixels from labels', 'Nothing'],
        answerIndex: 1,
        explanation: 'It conditions on the prefix to predict each next token.',
      },
      {
        prompt: 'Diffusion models generate by...',
        options: ['One forward pass only', 'Iteratively denoising from random noise', 'Hand-written rules', 'Random sampling without learning'],
        answerIndex: 1,
        explanation: 'A learned denoiser is run for many steps.',
      },
      {
        prompt: 'A discriminative model differs from a generative one in that it...',
        options: [
          'Models p(y|x) rather than p(x) or p(x, y)',
          'Always uses diffusion',
          'Cannot be trained',
          'Has no parameters',
        ],
        answerIndex: 0,
        explanation: 'Discriminative → conditional. Generative → model the data itself.',
      },
    ],
    xpReward: 26,
    coinReward: 10,
    masteryThreshold: 0.8,
  },
  {
    id: 'D15',
    trackId: 'aibasis',
    moduleId: 'D-models',
    order: 15,
    title: 'Reinforcement learning basics',
    subtitle: 'Learning from reward',
    estimatedMinutes: 6,
    difficulty: 'intermediate',
    prerequisites: ['D03'],
    explanation:
      'In reinforcement learning, an agent observes a state, takes an action, and receives a reward. It learns a policy that maximises expected long-term reward. Algorithms include Q-learning, policy gradient, and actor-critic.',
    notation: 'Q(s, a) ← Q(s, a) + α [r + γ max_a′ Q(s′, a′) − Q(s, a)]',
    keyTerms: ['agent', 'policy', 'reward', 'value function'],
    example:
      'AlphaGo combined RL with self-play and search to surpass top human Go players.',
    intuition: 'Try things, keep what was rewarded, in the right context.',
    whyItMatters:
      'RL underlies game-playing AIs, robotics policies, and the alignment fine-tuning of large language models.',
    questions: [
      {
        prompt: 'A policy is...',
        options: [
          'A mapping from states to actions',
          'A loss function',
          'A type of dataset',
          'A fixed initial weight',
        ],
        answerIndex: 0,
        explanation: 'The policy decides which action to take in each state.',
      },
      {
        prompt: 'In RL, the discount factor γ...',
        options: [
          'Removes rewards entirely',
          'Weights future reward less than immediate reward',
          'Sets the learning rate',
          'Makes training faster',
        ],
        answerIndex: 1,
        explanation: 'γ in [0, 1) trades off immediate vs delayed reward.',
      },
      {
        prompt: 'Q-learning learns...',
        options: ['Only a policy directly', 'An action-value function', 'Random labels', 'Nothing'],
        answerIndex: 1,
        explanation: 'Q-learning estimates Q(s, a), the expected future reward.',
      },
    ],
    xpReward: 26,
    coinReward: 10,
    masteryThreshold: 0.8,
  },
  {
    id: 'D16',
    trackId: 'aibasis',
    moduleId: 'D-choose',
    order: 16,
    title: 'How to pick a model family',
    subtitle: 'Match the tool to the data',
    estimatedMinutes: 5,
    difficulty: 'beginner',
    prerequisites: ['D14'],
    explanation:
      'Choosing a model starts from the data and the task. Tabular and small? Try linear models or boosted trees. Images? Convolutional networks or vision transformers. Text? Transformer language models. Sequences with limited data? Often classical methods or small RNNs are best.',
    keyTerms: ['inductive bias', 'data type', 'task type', 'baseline'],
    example:
      'For a small medical tabular dataset, gradient-boosted trees often beat a deep network out of the box.',
    intuition: 'Data shape and size constrain which models will actually work.',
    whyItMatters:
      'Picking the wrong family wastes weeks. Picking the right one makes the rest of the project easy.',
    questions: [
      {
        prompt: 'For grid-structured image data, a sensible default family is...',
        options: ['Logistic regression', 'A CNN or vision transformer', 'A simple Markov chain', 'KNN on raw pixels'],
        answerIndex: 1,
        explanation: 'CNNs / ViTs are designed for grid-structured visual data.',
      },
      {
        prompt: 'For tabular data with thousands of rows, a strong default is...',
        options: [
          'A 100-billion-parameter LLM',
          'Gradient-boosted trees or simple linear baselines',
          'Random sampling',
          'A diffusion model',
        ],
        answerIndex: 1,
        explanation: 'Boosted trees and linear baselines often dominate small tabular tasks.',
      },
      {
        prompt: 'A useful heuristic is to...',
        options: [
          'Always start with the biggest model possible',
          'Start with a strong simple baseline and only escalate if needed',
          'Skip baselines',
          'Pick a model by lottery',
        ],
        answerIndex: 1,
        explanation: 'Baselines define what counts as progress.',
      },
    ],
    xpReward: 22,
    coinReward: 8,
    masteryThreshold: 0.8,
  },
  {
    id: 'D17',
    trackId: 'aibasis',
    moduleId: 'D-choose',
    order: 17,
    title: 'Data and compute requirements',
    subtitle: 'How much you actually need',
    estimatedMinutes: 5,
    difficulty: 'beginner',
    prerequisites: ['D16'],
    explanation:
      'Bigger models usually need more data and more compute to train. Scaling laws describe how loss falls roughly as a power of model size, data size, and compute. With limited data, smaller models or pretrained-then-fine-tuned models are smarter choices.',
    keyTerms: ['scaling laws', 'compute budget', 'data budget', 'pretraining'],
    example:
      'A modest fine-tune of a pretrained foundation model often beats training a fresh huge model on the same small dataset.',
    intuition: 'Data, parameters, and compute should be balanced — not one giant and two pebbles.',
    whyItMatters:
      'The biggest mistakes in modelling come from imbalanced budgets across data, compute, and parameters.',
    questions: [
      {
        prompt: 'Scaling laws roughly say loss falls as a power of...',
        options: [
          'Random factors',
          'Model size, dataset size, and compute',
          'GPU brand only',
          'Programming language',
        ],
        answerIndex: 1,
        explanation: 'Loss ∝ (param size)^a, (data size)^b, (compute)^c approximately.',
      },
      {
        prompt: 'With small data, a smart move is to...',
        options: [
          'Train a giant model from scratch',
          'Fine-tune a pretrained model or use a smaller one',
          'Skip training',
          'Use only random predictions',
        ],
        answerIndex: 1,
        explanation: 'Pretrained features compensate for limited data.',
      },
      {
        prompt: 'A balanced budget cares about...',
        options: ['Only compute', 'Only data', 'Only parameters', 'All three together'],
        answerIndex: 3,
        explanation: 'Optimal training balances all three.',
      },
    ],
    xpReward: 22,
    coinReward: 8,
    masteryThreshold: 0.8,
  },
  {
    id: 'D18',
    trackId: 'aibasis',
    moduleId: 'D-build',
    order: 18,
    title: 'Train, validation, and test splits',
    subtitle: 'Honest measurement of generalisation',
    estimatedMinutes: 5,
    difficulty: 'beginner',
    prerequisites: ['D17'],
    explanation:
      'You split the data into a training set (fit parameters), a validation set (choose hyperparameters and stop training), and a held-out test set (final unbiased estimate of generalisation). The test set is touched only once.',
    keyTerms: ['train', 'validation', 'test', 'leakage'],
    example:
      'Reusing the test set to tune hyperparameters silently overfits it and inflates reported numbers.',
    intuition: 'The test set is sacred. Look at it once, at the end.',
    whyItMatters:
      'Most real-world model failures trace to leaky splits, not exotic architecture choices.',
    questions: [
      {
        prompt: 'The test set should be used to...',
        options: [
          'Tune hyperparameters',
          'Train the model',
          'Estimate generalisation performance once',
          'Pick the architecture',
        ],
        answerIndex: 2,
        explanation: 'Touch it only once for the final unbiased estimate.',
      },
      {
        prompt: 'Validation data is for...',
        options: ['Final reporting only', 'Choosing hyperparameters and early stopping', 'Training', 'Nothing'],
        answerIndex: 1,
        explanation: 'It guides modelling choices without touching the test set.',
      },
      {
        prompt: 'Data leakage means...',
        options: [
          'Information from test or future flows into training',
          'A small dataset',
          'GPUs running hot',
          'Loss going to zero',
        ],
        answerIndex: 0,
        explanation: 'Leakage breaks the honesty of the evaluation.',
      },
    ],
    xpReward: 22,
    coinReward: 8,
    masteryThreshold: 0.8,
  },
  {
    id: 'D19',
    trackId: 'aibasis',
    moduleId: 'D-build',
    order: 19,
    title: 'Cross-validation',
    subtitle: 'Better estimates from small data',
    estimatedMinutes: 5,
    difficulty: 'beginner',
    prerequisites: ['D18'],
    explanation:
      'k-fold cross-validation splits the training data into k parts, trains on k−1 of them, and validates on the rest, rotating through folds. The average score is a more stable estimate of generalisation than a single split.',
    keyTerms: ['k-fold', 'cross-validation', 'fold', 'variance'],
    example:
      'On a tiny medical dataset, 5- or 10-fold CV gives much more reliable model comparisons than a single split.',
    intuition: 'Use the data many ways to reduce the noise in your evaluation.',
    whyItMatters:
      'In small-data regimes, picking models with one split is gambling.',
    questions: [
      {
        prompt: 'In 5-fold cross-validation, each example serves as validation...',
        options: ['Never', 'Once', 'Five times', 'Always'],
        answerIndex: 1,
        explanation: 'Each fold is held out exactly once.',
      },
      {
        prompt: 'Cross-validation mainly reduces...',
        options: ['Bias of the model', 'Variance of the evaluation estimate', 'Inference time', 'Number of parameters'],
        answerIndex: 1,
        explanation: 'Averaging over folds stabilises the score.',
      },
      {
        prompt: 'CV is most useful when data is...',
        options: ['Huge', 'Moderate or scarce', 'Synthetic only', 'Already labelled by the model'],
        answerIndex: 1,
        explanation: 'Big data needs less help; small data needs CV.',
      },
    ],
    xpReward: 22,
    coinReward: 8,
    masteryThreshold: 0.8,
  },
  {
    id: 'D20',
    trackId: 'aibasis',
    moduleId: 'D-training',
    order: 20,
    title: 'Backpropagation',
    subtitle: 'How gradients flow through a network',
    estimatedMinutes: 6,
    difficulty: 'intermediate',
    prerequisites: ['D10'],
    explanation:
      'Backpropagation applies the chain rule to compute gradients of the loss with respect to every parameter, by walking backwards through the computational graph. Modern frameworks build the graph automatically and call backward() to get the gradients.',
    notation: '∂L/∂w = (∂L/∂y) (∂y/∂w)',
    keyTerms: ['chain rule', 'autograd', 'computational graph', 'gradient'],
    example:
      'PyTorch and JAX construct dynamic graphs and run reverse-mode autodiff to train arbitrary networks.',
    intuition: 'Errors travel from the loss back to every weight.',
    whyItMatters:
      'Every neural-network optimiser relies on this. Understanding it is the difference between using and tuning a framework.',
    questions: [
      {
        prompt: 'Backpropagation computes...',
        options: [
          'Forward predictions only',
          'Gradients of loss w.r.t. parameters via the chain rule',
          'A new dataset',
          'Random noise',
        ],
        answerIndex: 1,
        explanation: 'Backprop is reverse-mode autodiff over the chain rule.',
      },
      {
        prompt: 'Modern ML frameworks typically build...',
        options: ['Static rules only', 'A computational graph for autodiff', 'A spreadsheet', 'Nothing'],
        answerIndex: 1,
        explanation: 'The graph enables automatic differentiation.',
      },
      {
        prompt: 'Without gradients, you cannot...',
        options: [
          'Run forward inference',
          'Use gradient-based optimisers like SGD or Adam',
          'Load data',
          'Define a model',
        ],
        answerIndex: 1,
        explanation: 'Gradient-based training depends on backprop.',
      },
    ],
    xpReward: 26,
    coinReward: 10,
    masteryThreshold: 0.8,
  },
  {
    id: 'D21',
    trackId: 'aibasis',
    moduleId: 'D-training',
    order: 21,
    title: 'Gradient descent and optimisers',
    subtitle: 'Walking down the loss surface',
    estimatedMinutes: 5,
    difficulty: 'beginner',
    prerequisites: ['D20'],
    explanation:
      'Gradient descent updates parameters in the direction of the negative gradient. Stochastic gradient descent uses small batches. Optimisers such as Momentum, RMSProp, and Adam adjust the step size and direction based on running statistics of the gradients.',
    notation: 'w ← w − η ∇L(w)',
    keyTerms: ['SGD', 'momentum', 'Adam', 'learning rate'],
    example:
      'Adam is a sensible default for most deep-learning training because it adapts step sizes per parameter.',
    intuition: 'Walk downhill, but with shock absorbers.',
    whyItMatters:
      'Optimiser choice and tuning are among the most impactful decisions in training neural networks.',
    questions: [
      {
        prompt: 'Stochastic gradient descent uses...',
        options: ['The full dataset every step', 'A small mini-batch each step', 'Random noise only', 'No gradients'],
        answerIndex: 1,
        explanation: 'Mini-batches speed up training and add useful noise.',
      },
      {
        prompt: 'Adam combines...',
        options: ['Momentum and adaptive per-parameter learning rates', 'Only momentum', 'Only L2', 'No tricks'],
        answerIndex: 0,
        explanation: 'Adam tracks first and second moments of gradients.',
      },
      {
        prompt: 'A learning rate that is too large typically...',
        options: ['Speeds convergence reliably', 'Causes loss to oscillate or diverge', 'Has no effect', 'Reduces parameters'],
        answerIndex: 1,
        explanation: 'Big steps overshoot minima.',
      },
    ],
    xpReward: 24,
    coinReward: 9,
    masteryThreshold: 0.8,
  },
  {
    id: 'D22',
    trackId: 'aibasis',
    moduleId: 'D-training',
    order: 22,
    title: 'Learning rate and batch size',
    subtitle: 'The two knobs you tune first',
    estimatedMinutes: 5,
    difficulty: 'beginner',
    prerequisites: ['D21'],
    explanation:
      'Learning rate controls how big each update is. Batch size controls how many examples produce each gradient. They interact: larger batches usually allow larger learning rates. Schedules that warm up and then decay the learning rate are widely used.',
    keyTerms: ['learning rate', 'batch size', 'warmup', 'decay'],
    example:
      'Many transformer training recipes warm up the learning rate over the first 1000 steps, then decay slowly.',
    intuition: 'LR = step size. Batch size = how confident each step is.',
    whyItMatters:
      'These two hyperparameters explain most training failures and are usually the first to revisit.',
    questions: [
      {
        prompt: 'Doubling the batch size, all else equal, typically allows you to...',
        options: ['Use a smaller learning rate only', 'Use a somewhat larger learning rate', 'Skip backprop', 'Reach zero loss instantly'],
        answerIndex: 1,
        explanation: 'A common heuristic scales LR with batch size up to a point.',
      },
      {
        prompt: 'A warmup phase exists to...',
        options: ['Slowly increase the learning rate at the start', 'Add random noise', 'Skip early data', 'Reduce gradients'],
        answerIndex: 0,
        explanation: 'Warmup avoids large unstable updates early in training.',
      },
      {
        prompt: 'When loss diverges, the first thing to check is often...',
        options: ['The dataset name', 'Learning rate magnitude', 'Activation choice only', 'GPU brand'],
        answerIndex: 1,
        explanation: 'A too-large LR is a common cause of divergence.',
      },
    ],
    xpReward: 22,
    coinReward: 8,
    masteryThreshold: 0.8,
  },
  {
    id: 'D23',
    trackId: 'aibasis',
    moduleId: 'D-training',
    order: 23,
    title: 'Initialisation and normalisation',
    subtitle: 'Healthy gradients across layers',
    estimatedMinutes: 5,
    difficulty: 'intermediate',
    prerequisites: ['D22'],
    explanation:
      'Good initialisation (Xavier, He) and normalisation layers (BatchNorm, LayerNorm) keep activations and gradients well-scaled across many layers, which is essential for deep networks to train reliably.',
    keyTerms: ['initialisation', 'BatchNorm', 'LayerNorm', 'gradient flow'],
    example:
      'Transformers use LayerNorm to stabilise training across very deep stacks of attention blocks.',
    intuition: 'If signals shrink or explode as they go through the network, training collapses.',
    whyItMatters:
      'Normalisation and good init are quiet workhorses behind almost every deep model that trains successfully.',
    questions: [
      {
        prompt: 'Without good initialisation, deep networks often suffer from...',
        options: ['Perfect gradients', 'Vanishing or exploding gradients', 'No parameters', 'Too few layers'],
        answerIndex: 1,
        explanation: 'Bad scales of weights kill or blow up gradients.',
      },
      {
        prompt: 'LayerNorm normalises across...',
        options: ['The batch dimension only', 'The features within an example', 'Random axes', 'Time only'],
        answerIndex: 1,
        explanation: 'LayerNorm standardises across feature dimensions per example.',
      },
      {
        prompt: 'BatchNorm depends on...',
        options: ['One example only', 'Statistics across the mini-batch', 'No statistics', 'Future data'],
        answerIndex: 1,
        explanation: 'It uses mini-batch mean and variance.',
      },
    ],
    xpReward: 24,
    coinReward: 9,
    masteryThreshold: 0.8,
  },
  {
    id: 'D24',
    trackId: 'aibasis',
    moduleId: 'D-training',
    order: 24,
    title: 'Hyperparameter tuning',
    subtitle: 'Searching the knobs',
    estimatedMinutes: 5,
    difficulty: 'intermediate',
    prerequisites: ['D23'],
    explanation:
      'Hyperparameters are settings that are not learned by gradient descent: learning rate, model size, regularisation strength, etc. You search over them with grid search, random search, or Bayesian optimisation, evaluating each candidate on validation data.',
    keyTerms: ['hyperparameter', 'grid search', 'random search', 'Bayesian optimisation'],
    example:
      'Random search frequently beats grid search because most hyperparameters do not matter equally.',
    intuition: 'Pick a budget of trials, search smartly, score on validation.',
    whyItMatters:
      'Tuning often produces larger gains than swapping models, especially in the medium-data regime.',
    questions: [
      {
        prompt: 'Hyperparameters are tuned on...',
        options: ['Training data', 'Validation data', 'Test data', 'Random noise'],
        answerIndex: 1,
        explanation: 'Validation is the right place; test is sacred.',
      },
      {
        prompt: 'A reason random search often beats grid search is that...',
        options: [
          'It exhaustively covers everything',
          'Few hyperparameters dominate, so random samples explore better in high dimensions',
          'It uses no compute',
          'It always finds the global optimum',
        ],
        answerIndex: 1,
        explanation: 'Random search avoids wasting trials on irrelevant axes.',
      },
      {
        prompt: 'Bayesian optimisation models...',
        options: [
          'The loss surface to choose promising next points',
          'The data only',
          'The user only',
          'The hardware only',
        ],
        answerIndex: 0,
        explanation: 'It builds a surrogate of the validation score.',
      },
    ],
    xpReward: 24,
    coinReward: 9,
    masteryThreshold: 0.8,
  },
  {
    id: 'D25',
    trackId: 'aibasis',
    moduleId: 'D-inference',
    order: 25,
    title: 'Inference and deployment',
    subtitle: 'From training to running in production',
    estimatedMinutes: 5,
    difficulty: 'beginner',
    prerequisites: ['D24'],
    explanation:
      'Inference is using a trained model to produce predictions on new inputs. Deployment cares about latency, throughput, memory, monitoring, and rollback. Many production systems freeze the model and serve it through a versioned API.',
    keyTerms: ['inference', 'deployment', 'latency', 'monitoring'],
    example:
      'A search ranker may train weekly but must respond to user queries in tens of milliseconds.',
    intuition: 'Training is a marathon you run once; inference is a sprint you run constantly.',
    whyItMatters:
      'A model that cannot be deployed reliably is a research result, not a product.',
    questions: [
      {
        prompt: 'Inference latency is the time to...',
        options: [
          'Train the model end-to-end',
          'Produce a single prediction for one input',
          'Backpropagate gradients',
          'Read the dataset',
        ],
        answerIndex: 1,
        explanation: 'It is the per-request prediction time.',
      },
      {
        prompt: 'A deployment must usually monitor for...',
        options: ['Only training loss', 'Drift, latency, error rates, and quality', 'Number of GPUs only', 'Nothing'],
        answerIndex: 1,
        explanation: 'Production reality demands continuous observability.',
      },
      {
        prompt: 'A versioned model API helps with...',
        options: ['Faster training only', 'Safe rollouts and rollback', 'Bigger datasets', 'Higher accuracy automatically'],
        answerIndex: 1,
        explanation: 'Versioning is essential for safe deployments.',
      },
    ],
    xpReward: 22,
    coinReward: 8,
    masteryThreshold: 0.8,
  },
  {
    id: 'D26',
    trackId: 'aibasis',
    moduleId: 'D-inference',
    order: 26,
    title: 'Quantisation and distillation',
    subtitle: 'Smaller, faster, cheaper models',
    estimatedMinutes: 5,
    difficulty: 'intermediate',
    prerequisites: ['D25'],
    explanation:
      'Quantisation stores weights and activations at lower precision (for example 8-bit or 4-bit) to shrink models and speed up inference. Distillation trains a smaller student model to imitate a larger teacher, often with little quality loss.',
    keyTerms: ['quantisation', 'distillation', 'student-teacher', 'precision'],
    example:
      'Many on-device LLMs are 4-bit quantised distilled versions of much larger pretrained models.',
    intuition: 'Lose a few bits of precision to gain orders of magnitude of speed.',
    whyItMatters:
      'Production AI lives or dies on cost and latency, and these techniques unlock both.',
    questions: [
      {
        prompt: 'Quantisation reduces...',
        options: ['Numerical precision of weights and activations', 'Number of layers', 'Training data', 'Loss function choices'],
        answerIndex: 0,
        explanation: 'Precision goes down; size and speed improve.',
      },
      {
        prompt: 'Distillation trains a student model to...',
        options: ['Ignore the teacher', 'Match the teacher’s outputs or distributions', 'Run only on CPU', 'Skip data entirely'],
        answerIndex: 1,
        explanation: 'The student learns from the teacher’s soft targets.',
      },
      {
        prompt: 'A typical reason to quantise a model is to...',
        options: ['Increase parameter count', 'Run on phones or tight memory budgets', 'Train more slowly', 'Add randomness'],
        answerIndex: 1,
        explanation: 'Lower precision → smaller, faster on constrained hardware.',
      },
    ],
    xpReward: 24,
    coinReward: 9,
    masteryThreshold: 0.8,
  },
  {
    id: 'D27',
    trackId: 'aibasis',
    moduleId: 'D-refining',
    order: 27,
    title: 'Transfer learning and fine-tuning',
    subtitle: 'Standing on a pretrained model’s shoulders',
    estimatedMinutes: 5,
    difficulty: 'intermediate',
    prerequisites: ['D17'],
    explanation:
      'Transfer learning starts from a model pretrained on a large general corpus and adapts it to a specific task. Full fine-tuning updates all weights. Parameter-efficient methods such as LoRA add small trainable adapters and keep the base model frozen.',
    keyTerms: ['transfer learning', 'fine-tune', 'LoRA', 'adapter'],
    example:
      'Fine-tuning a pretrained vision model on a few thousand medical images can reach accuracies that would need millions of images from scratch.',
    intuition: 'The model already knows a lot. Just teach it the new bits.',
    whyItMatters:
      'Fine-tuning is the most cost-effective way to specialise foundation models to a domain or task.',
    questions: [
      {
        prompt: 'Fine-tuning differs from training from scratch because it...',
        options: [
          'Starts from random weights',
          'Starts from a pretrained model',
          'Uses no data',
          'Trains the same way always',
        ],
        answerIndex: 1,
        explanation: 'Fine-tuning leverages prior representations.',
      },
      {
        prompt: 'LoRA-style adapters are useful because they...',
        options: [
          'Train only a small number of parameters while keeping the base frozen',
          'Replace all weights',
          'Skip optimisation',
          'Are only for vision',
        ],
        answerIndex: 0,
        explanation: 'Small adapters cut compute and memory dramatically.',
      },
      {
        prompt: 'Transfer learning is most useful when...',
        options: ['You have huge data and infinite compute', 'You have limited data and a related pretrained model', 'There is no pretrained model anywhere', 'You forbid using prior models'],
        answerIndex: 1,
        explanation: 'Pretraining substitutes for missing data.',
      },
    ],
    xpReward: 24,
    coinReward: 9,
    masteryThreshold: 0.8,
  },
  {
    id: 'D28',
    trackId: 'aibasis',
    moduleId: 'D-refining',
    order: 28,
    title: 'Prompting and retrieval-augmented generation',
    subtitle: 'Refining behaviour without changing weights',
    estimatedMinutes: 5,
    difficulty: 'intermediate',
    prerequisites: ['D13'],
    explanation:
      'Prompt engineering shapes a foundation model’s behaviour by carefully constructing the input. Retrieval-augmented generation (RAG) adds an external retriever that fetches relevant documents and injects them into the prompt, grounding the model in up-to-date sources.',
    keyTerms: ['prompt', 'RAG', 'retriever', 'context window'],
    example:
      'A customer-support assistant that searches your docs and feeds matching paragraphs to an LLM is a typical RAG system.',
    intuition: 'Don’t retrain the brain — give it the right book to read.',
    whyItMatters:
      'For many applications, prompting and retrieval are cheaper, faster, and safer than fine-tuning.',
    questions: [
      {
        prompt: 'RAG combines...',
        options: [
          'A fine-tuned model only',
          'A retriever and a generator',
          'No model at all',
          'Two random forests',
        ],
        answerIndex: 1,
        explanation: 'RAG retrieves documents and conditions generation on them.',
      },
      {
        prompt: 'A reason to prefer prompting over fine-tuning is...',
        options: [
          'It updates the model weights',
          'It is cheaper and faster to iterate on',
          'It guarantees correctness',
          'It removes the need for evaluation',
        ],
        answerIndex: 1,
        explanation: 'Prompts can be changed in seconds without training runs.',
      },
      {
        prompt: 'A pitfall of pure prompting is that...',
        options: [
          'The model still has limited context length and may hallucinate',
          'It always remembers your data forever',
          'It needs no evaluation',
          'It cannot use any external data',
        ],
        answerIndex: 0,
        explanation: 'Context windows are finite and ungrounded answers can be wrong.',
      },
    ],
    xpReward: 24,
    coinReward: 9,
    masteryThreshold: 0.8,
  },
  {
    id: 'D29',
    trackId: 'aibasis',
    moduleId: 'D-refining',
    order: 29,
    title: 'Alignment with RLHF and feedback',
    subtitle: 'Refining what a model should say',
    estimatedMinutes: 6,
    difficulty: 'intermediate',
    prerequisites: ['D15', 'D27'],
    explanation:
      'Reinforcement learning from human feedback (RLHF) refines a pretrained model using human preference data. Annotators rank model outputs; a reward model is trained on these preferences; the policy is then fine-tuned to maximise that reward.',
    keyTerms: ['RLHF', 'preference data', 'reward model', 'alignment'],
    example:
      'Conversational assistants like ChatGPT and Claude rely on RLHF and related techniques to be helpful and harmless.',
    intuition: 'Pretraining teaches what is likely; alignment teaches what is wanted.',
    whyItMatters:
      'Without alignment, raw foundation models emit useful but often unhelpful or unsafe text.',
    questions: [
      {
        prompt: 'In RLHF, the reward model is trained from...',
        options: ['Random labels', 'Human preference comparisons between outputs', 'Internet noise only', 'Loss values from pretraining'],
        answerIndex: 1,
        explanation: 'Annotators rank outputs; the reward model imitates those rankings.',
      },
      {
        prompt: 'Alignment refines a model’s...',
        options: ['Architecture', 'Behaviour and style of responses', 'Random seed only', 'Tokeniser'],
        answerIndex: 1,
        explanation: 'Alignment shapes how the model responds, not its capacity.',
      },
      {
        prompt: 'A risk of poorly tuned RLHF is...',
        options: [
          'Reward hacking and over-optimised behaviour',
          'Losing all parameters',
          'Forgetting how to do inference',
          'Crashing the GPU',
        ],
        answerIndex: 0,
        explanation: 'Models can game the reward and produce undesired outputs.',
      },
    ],
    xpReward: 26,
    coinReward: 10,
    masteryThreshold: 0.8,
  },
  {
    id: 'D30',
    trackId: 'aibasis',
    moduleId: 'D-refining',
    order: 30,
    title: 'Evaluation, monitoring, and iteration',
    subtitle: 'Closing the loop in real systems',
    estimatedMinutes: 6,
    difficulty: 'intermediate',
    prerequisites: ['D29'],
    explanation:
      'A real AI product is never finished. You build evaluation suites that match user value, monitor live performance for drift and failures, collect human and automatic feedback, and feed that back into data, prompts, fine-tunes, or new models on a regular cadence.',
    keyTerms: ['evaluation', 'monitoring', 'drift', 'iteration'],
    example:
      'A coding assistant tracks suggestion acceptance rate, latency, and error reports, then ships weekly improvements.',
    intuition: 'Train, deploy, watch, learn, repeat.',
    whyItMatters:
      'The teams that win in AI are not those with the biggest first model, but those with the best feedback loop.',
    questions: [
      {
        prompt: 'A useful evaluation suite measures...',
        options: [
          'Loss only',
          'Behaviour the user actually cares about, with multiple metrics',
          'GPU utilisation only',
          'Random samples without metrics',
        ],
        answerIndex: 1,
        explanation: 'Evals must reflect user value, not just training loss.',
      },
      {
        prompt: 'Distribution drift in production means...',
        options: [
          'The model file moves between machines',
          'Inputs change over time and degrade model quality',
          'Loss is always rising during training',
          'Users disappear',
        ],
        answerIndex: 1,
        explanation: 'Real-world inputs evolve; models must be re-evaluated.',
      },
      {
        prompt: 'The most important AI engineering habit is...',
        options: [
          'Shipping a single big model and never touching it',
          'Running a tight, evidence-driven iteration loop',
          'Avoiding evaluation',
          'Maximising parameter count only',
        ],
        answerIndex: 1,
        explanation: 'Iteration over honest evaluation is what compounds in practice.',
      },
    ],
    xpReward: 28,
    coinReward: 11,
    masteryThreshold: 0.8,
  },
];
