import { Lesson } from './types';

/**
 * Track B - Math Foundations for Computational Neuroscience. 40 lessons.
 * Sequentially unlocked by completion of prior lessons. Lessons B21-B40
 * extend the basics with the core linear algebra, multivariable calculus,
 * probability, statistics, and information theory needed for the
 * Computational Neuroscience and AI tracks.
 */
export const trackBLessons: Lesson[] = [
  {
    id: 'B01',
    trackId: 'math',
    moduleId: 'B-numbers',
    order: 1,
    title: 'Scalar',
    subtitle: 'A single number with meaning',
    estimatedMinutes: 4,
    difficulty: 'intro',
    prerequisites: [],
    explanation:
      'A scalar is just one number. In neuroscience it might be a firing rate, a membrane voltage, or a reaction time. Before we build vectors or matrices, we have to be comfortable with a single value that carries a unit.',
    notation: 'r = 12 Hz   |   V = \u221265 mV',
    keyTerms: ['scalar', 'quantity', 'unit'],
    example:
      'A cortical neuron firing at 12 spikes per second has a scalar firing rate r = 12 Hz.',
    intuition: 'A scalar is "one number and what it means".',
    whyItMatters:
      'Most measurements start as scalars. Vectors and matrices are ways of packing many scalars together.',
    questions: [
      {
        prompt: 'Which of these is a scalar?',
        options: ['(3, 4)', '12 Hz', 'A 2x2 matrix', 'A function from \u211d to \u211d'],
        answerIndex: 1,
        explanation: 'A scalar is a single number with a unit, like 12 Hz.',
      },
      {
        prompt: 'A scalar alone typically does not encode...',
        options: ['A value', 'A unit', 'A magnitude', 'A list of values'],
        answerIndex: 3,
        explanation: 'A scalar is one value - you need a vector for a list.',
      },
      {
        prompt: 'Which statement is most accurate?',
        options: [
          'Every matrix is a scalar.',
          'A scalar is the simplest quantity: one number with meaning.',
          'Scalars are always integers.',
          'Scalars cannot have units.',
        ],
        answerIndex: 1,
        explanation: 'Scalars are single numbers; they can be real, can carry units, and can be non-integer.',
      },
    ],
    xpReward: 14,
    coinReward: 5,
    masteryThreshold: 0.8,
  },
  {
    id: 'B02',
    trackId: 'math',
    moduleId: 'B-numbers',
    order: 2,
    title: 'Vector',
    subtitle: 'A short list of numbers that go together',
    estimatedMinutes: 4,
    difficulty: 'intro',
    prerequisites: ['B01'],
    explanation:
      'A vector is an ordered list of scalars that we treat as a single object. In neuroscience, a vector often represents the firing rates of many neurons at one moment.',
    notation: 'r = (r\u2081, r\u2082, \u2026, r\u2099)',
    keyTerms: ['vector', 'ordered list', 'length'],
    example:
      'The firing rates of 50 simultaneously recorded neurons at time t form a vector r(t) with 50 entries.',
    intuition: 'A vector is a row of boxes where each box is a scalar.',
    whyItMatters:
      'Everything from population coding to neural decoding thinks of neural activity as a vector.',
    questions: [
      {
        prompt: 'Which of these is a vector with three entries?',
        options: ['12.0', '(3, 5, 1)', 'A single matrix', 'An empty set'],
        answerIndex: 1,
        explanation: '(3, 5, 1) is a list of three scalars - a three-dimensional vector.',
      },
      {
        prompt: 'The length (number of entries) of a vector is also called its...',
        options: ['Mass', 'Dimension', 'Colour', 'Threshold'],
        answerIndex: 1,
        explanation: 'We call the number of entries the dimension of the vector.',
      },
      {
        prompt: 'A neural population of N neurons at time t can be summarised as...',
        options: [
          'A scalar',
          'A vector with N entries',
          'A matrix with one row',
          'A scalar times a scalar',
        ],
        answerIndex: 1,
        explanation: 'A vector with N entries, one per neuron.',
      },
    ],
    xpReward: 16,
    coinReward: 6,
    masteryThreshold: 0.8,
  },
  {
    id: 'B03',
    trackId: 'math',
    moduleId: 'B-numbers',
    order: 3,
    title: 'Component',
    subtitle: 'Each entry has a name',
    estimatedMinutes: 4,
    difficulty: 'intro',
    prerequisites: ['B02'],
    explanation:
      'Each entry of a vector is called a component. In r = (r\u2081, r\u2082, r\u2083), r\u2082 is the second component. The index (the small number below) picks one component from the whole vector.',
    notation: 'r\u2081, r\u2082, r\u2083, \u2026',
    keyTerms: ['component', 'index', 'entry'],
    example:
      'If r is a population rate vector, r\u2085 is the firing rate of the fifth neuron in the population.',
    intuition: 'Indices are tiny pointers that say "this box, please".',
    whyItMatters:
      'Without comfortable indexing, sums like \u03a3 w\u1d62 r\u1d62 are hard to read. With it, they are just "weighted sums".',
    questions: [
      {
        prompt: 'In r = (4, 7, 3), what is r\u2082?',
        options: ['4', '7', '3', 'Not defined'],
        answerIndex: 1,
        explanation: 'Indexing from 1, r\u2082 is the second entry: 7.',
      },
      {
        prompt: 'The index of a component tells you...',
        options: ['Its unit', 'Which position in the vector it sits in', 'The slope of the vector', 'Its colour'],
        answerIndex: 1,
        explanation: 'Indices identify a specific position in the vector.',
      },
      {
        prompt: 'A component of a firing-rate vector is typically...',
        options: [
          'The entire vector at once',
          'The firing rate of one neuron',
          'The number of neurons',
          'The time axis',
        ],
        answerIndex: 1,
        explanation: 'Each component corresponds to the activity of a single neuron.',
      },
    ],
    xpReward: 16,
    coinReward: 6,
    masteryThreshold: 0.8,
  },
  {
    id: 'B04',
    trackId: 'math',
    moduleId: 'B-numbers',
    order: 4,
    title: 'Dimension',
    subtitle: 'How many numbers does it take to describe this?',
    estimatedMinutes: 4,
    difficulty: 'intro',
    prerequisites: ['B03'],
    explanation:
      'The dimension of a vector is the number of components it has. A 3D vector lives in 3 dimensions; a 500D vector describes 500 numbers at once. Dimension is the language of "how many degrees of freedom" we are tracking.',
    notation: 'dim(r) = n  when  r \u2208 \u211d\u207f',
    keyTerms: ['dimension', 'degrees of freedom'],
    example:
      'Recording 200 neurons gives you a 200-dimensional vector at each time step.',
    intuition: 'More dimensions = more independent numbers needed to pin the state down.',
    whyItMatters:
      'Neural activity lives in high-dimensional spaces. Dimensionality is the first honest word to use when we talk about it.',
    questions: [
      {
        prompt: 'A vector with 7 components lives in which space?',
        options: ['\u211d\u00b2', '\u211d\u2077', '\u211d\u00b9\u2070', 'A plane'],
        answerIndex: 1,
        explanation: 'Seven components \u2192 seven-dimensional space, \u211d\u2077.',
      },
      {
        prompt: 'If we record 50 neurons, the instantaneous activity vector has dimension...',
        options: ['5', '50', '500', 'It depends on firing rate'],
        answerIndex: 1,
        explanation: 'One component per neuron \u2192 50 dimensions.',
      },
      {
        prompt: 'Dimension is best described as...',
        options: [
          'The colour of a variable',
          'The number of independent numbers needed to describe the state',
          'The slope of a function',
          'The total number of samples over time',
        ],
        answerIndex: 1,
        explanation: 'It tells you how many numbers are needed to pin the state down.',
      },
    ],
    xpReward: 16,
    coinReward: 6,
    masteryThreshold: 0.8,
  },
  {
    id: 'B05',
    trackId: 'math',
    moduleId: 'B-notation',
    order: 5,
    title: 'Notation x\u1d62',
    subtitle: 'Reading indexed variables',
    estimatedMinutes: 4,
    difficulty: 'intro',
    prerequisites: ['B04'],
    explanation:
      'When you see x\u1d62, read it as "the i-th entry of x". The letter i is a placeholder that can take values from 1 up to n. When you vary i, you are walking through the components of the vector.',
    notation: 'x\u1d62  for i = 1, 2, \u2026, n',
    keyTerms: ['index', 'subscript', 'dummy variable'],
    example:
      'If r\u1d62 is the firing rate of neuron i, then r\u2083 is simply the firing rate of the third neuron in your recording.',
    intuition: 'Indices are placeholders. Substituting a number selects one entry.',
    whyItMatters:
      'Mathematical writing in computational neuroscience is covered in indexed variables. Reading them should feel natural.',
    questions: [
      {
        prompt: 'x\u1d62 with i = 4 means...',
        options: [
          'The fourth component of x',
          'The total of all components',
          'The variable times 4',
          'The square of x',
        ],
        answerIndex: 0,
        explanation: 'It picks out the fourth entry of the vector x.',
      },
      {
        prompt: 'In "for i = 1, \u2026, n", i is...',
        options: [
          'A constant',
          'A dummy variable that ranges over indices',
          'A real-valued function',
          'A measurement unit',
        ],
        answerIndex: 1,
        explanation: 'i is a dummy variable walking through positions.',
      },
      {
        prompt: 'If r\u1d62 is the firing rate of the i-th neuron, then r\u2081 + r\u2082 is...',
        options: [
          'A meaningless expression',
          'The sum of the first two neurons\u2019 firing rates',
          'The product of their rates',
          'The third neuron\u2019s rate',
        ],
        answerIndex: 1,
        explanation: 'Adding r\u2081 and r\u2082 gives the combined rate of neurons 1 and 2.',
      },
    ],
    xpReward: 16,
    coinReward: 6,
    masteryThreshold: 0.8,
  },
  {
    id: 'B06',
    trackId: 'math',
    moduleId: 'B-notation',
    order: 6,
    title: 'Notation x(t)',
    subtitle: 'A variable that changes with time',
    estimatedMinutes: 4,
    difficulty: 'intro',
    prerequisites: ['B05'],
    explanation:
      'When we write x(t), we mean "the value of x at time t". It is a function of time. Plugging in a specific time gives a specific value. If x is a vector, x(t) is a vector at each moment.',
    notation: 'x(t)  for t \u2208 \u211d',
    keyTerms: ['time', 'signal', 'function of time'],
    example:
      'The membrane potential V(t) of a neuron is a function of time, changing millisecond to millisecond as inputs arrive.',
    intuition: 'x(t) is a recipe: "given time t, here is a number (or vector)".',
    whyItMatters:
      'Neural dynamics are descriptions of how variables evolve over time. You will live in x(t) notation.',
    questions: [
      {
        prompt: 'V(t) with t = 5 ms means...',
        options: ['The voltage at t = 5 ms', 'The fifth voltage', 'Five times voltage', 'Voltage at t = 0'],
        answerIndex: 0,
        explanation: 'It is the value of V when time equals 5 milliseconds.',
      },
      {
        prompt: 'A signal that does not change over time has x(t) that is...',
        options: ['A constant', 'Always zero', 'A matrix', 'Undefined'],
        answerIndex: 0,
        explanation: 'A constant function takes the same value at every t.',
      },
      {
        prompt: 'If r(t) is a firing-rate vector over time, then r(t) is...',
        options: [
          'A scalar at each moment',
          'A vector at each moment',
          'A matrix at each moment',
          'Meaningless',
        ],
        answerIndex: 1,
        explanation: 'At every time, r(t) is a vector of firing rates.',
      },
    ],
    xpReward: 16,
    coinReward: 6,
    masteryThreshold: 0.8,
  },
  {
    id: 'B07',
    trackId: 'math',
    moduleId: 'B-spaces',
    order: 7,
    title: 'R^n',
    subtitle: 'The space of n-dimensional vectors',
    estimatedMinutes: 4,
    difficulty: 'beginner',
    prerequisites: ['B04'],
    explanation:
      'R^n, written \u211d\u207f, is the set of all vectors with exactly n real-valued entries. When we say r \u2208 \u211d\u207f, we mean r is one of those vectors.',
    notation: 'r \u2208 \u211d\u207f',
    keyTerms: ['real numbers', 'vector space'],
    example:
      'A 100-neuron population vector at one moment is an element of \u211d\u00b9\u2070\u2070.',
    intuition: 'Think of \u211d\u207f as a giant bag of all possible n-number lists.',
    whyItMatters:
      'Reading "r \u2208 \u211d\u207f" tells you at a glance the shape of the object you are reasoning about.',
    questions: [
      {
        prompt: 'A vector (1.0, 3.5) belongs to which space?',
        options: ['\u211d\u00b9', '\u211d\u00b2', '\u211d\u00b3', '\u2124'],
        answerIndex: 1,
        explanation: 'Two real components \u2192 \u211d\u00b2.',
      },
      {
        prompt: 'The set of all 100-neuron rate vectors lives in...',
        options: ['\u211d\u00b9\u2070\u2070', '\u211d\u00b2', '\u211d\u00b9', 'A single scalar'],
        answerIndex: 0,
        explanation: 'Each component is a rate of one neuron \u2192 100 dimensions.',
      },
      {
        prompt: '"r \u2208 \u211d\u2075" is another way to say r is...',
        options: [
          'A number between 0 and 5',
          'A vector with 5 real components',
          'A matrix with 5 rows and 5 columns',
          'A function of 5 inputs',
        ],
        answerIndex: 1,
        explanation: 'It is simply a real-valued 5-dimensional vector.',
      },
    ],
    xpReward: 18,
    coinReward: 6,
    masteryThreshold: 0.8,
  },
  {
    id: 'B08',
    trackId: 'math',
    moduleId: 'B-matrices',
    order: 8,
    title: 'Matrix',
    subtitle: 'A grid of numbers that connect things',
    estimatedMinutes: 5,
    difficulty: 'beginner',
    prerequisites: ['B07'],
    explanation:
      'A matrix is a rectangular array of numbers arranged in rows and columns. In neuroscience, matrices frequently describe how one set of variables maps to another - for example, how presynaptic neurons influence postsynaptic ones.',
    notation: 'W \u2208 \u211d^{m\u00d7n}',
    keyTerms: ['matrix', 'rows', 'columns', 'shape'],
    example:
      'A 100-by-200 connectivity matrix W specifies how strongly each of 200 presynaptic neurons influences each of 100 postsynaptic neurons.',
    intuition: 'A matrix is a table where every entry is a "connection number".',
    whyItMatters:
      'Most linear models of neural circuits reduce to multiplying a vector by a matrix.',
    questions: [
      {
        prompt: 'A 100\u00d7200 matrix has how many rows?',
        options: ['100', '200', '20000', '1'],
        answerIndex: 0,
        explanation: 'The first number is rows, the second is columns.',
      },
      {
        prompt: 'W \u2208 \u211d^{m\u00d7n} means W has...',
        options: [
          'm total entries',
          'm rows and n columns of real numbers',
          'm columns and n rows',
          'Just m components',
        ],
        answerIndex: 1,
        explanation: 'm rows, n columns, real-valued entries.',
      },
      {
        prompt: 'A connectivity matrix in a neural network usually encodes...',
        options: [
          'Only the firing rate of each neuron',
          'Strength of connections between units',
          'The neuron\u2019s colour',
          'Time constants only',
        ],
        answerIndex: 1,
        explanation: 'Entries represent synaptic weights or influences between units.',
      },
    ],
    xpReward: 20,
    coinReward: 7,
    masteryThreshold: 0.8,
  },
  {
    id: 'B09',
    trackId: 'math',
    moduleId: 'B-matrices',
    order: 9,
    title: 'Rows and columns',
    subtitle: 'Reading a matrix like a map',
    estimatedMinutes: 4,
    difficulty: 'beginner',
    prerequisites: ['B08'],
    explanation:
      'Each row of a matrix can be read as a vector across columns, and each column as a vector across rows. In a connectivity matrix W where W_{ij} is the strength from input j to output i, the i-th row tells you how output i listens to every input.',
    notation: 'W_{ij}  =  strength from j to i',
    keyTerms: ['row', 'column', 'entry'],
    example:
      'The first row of W might describe how the first postsynaptic neuron weights all 200 of its inputs.',
    intuition: 'Rows are "who listens". Columns are "who speaks".',
    whyItMatters:
      'Understanding row-vs-column is the difference between saying "neuron i receives" and "neuron j sends".',
    questions: [
      {
        prompt: 'In W_{ij}, i typically indexes...',
        options: ['Columns', 'Rows', 'Time', 'Spatial position'],
        answerIndex: 1,
        explanation: 'By convention the first index is the row.',
      },
      {
        prompt: 'A row of a connectivity matrix describes how...',
        options: [
          'A single postsynaptic neuron listens to all inputs',
          'A single presynaptic neuron broadcasts',
          'The whole circuit changes over time',
          'Neurons are coloured',
        ],
        answerIndex: 0,
        explanation: 'Each row is the full input weighting for one output unit.',
      },
      {
        prompt: 'A column of that matrix describes how...',
        options: [
          'A single postsynaptic neuron listens',
          'A single presynaptic neuron influences all outputs',
          'The network loses energy',
          'Biases shift over time',
        ],
        answerIndex: 1,
        explanation: 'Each column is the full fan-out of one input unit.',
      },
    ],
    xpReward: 18,
    coinReward: 6,
    masteryThreshold: 0.8,
  },
  {
    id: 'B10',
    trackId: 'math',
    moduleId: 'B-matrices',
    order: 10,
    title: 'Matrix-vector product',
    subtitle: 'One circuit operation, explained',
    estimatedMinutes: 5,
    difficulty: 'beginner',
    prerequisites: ['B09'],
    explanation:
      'Multiplying a matrix W by a vector r gives a new vector y where each entry is the dot product of a row of W with r. For a circuit, this is a compact way to compute all weighted sums of inputs for all output neurons at once.',
    notation: 'y = W r   with   y\u1d62 = \u03a3\u2c7c W_{ij} r\u2c7c',
    keyTerms: ['matrix-vector product', 'linear map'],
    example:
      'If r is the vector of 200 presynaptic firing rates and W is a 100\u00d7200 weight matrix, then W r is the vector of 100 weighted summed inputs to postsynaptic neurons.',
    intuition: 'y = W r is "every postsynaptic neuron does its own weighted sum, all at the same time".',
    whyItMatters:
      'This is the most common operation you will meet in linear neural models.',
    questions: [
      {
        prompt: 'If W is 50\u00d7200 and r is a 200-vector, then y = W r has dimension...',
        options: ['50', '200', '10000', 'Undefined'],
        answerIndex: 0,
        explanation: 'The output vector has as many entries as the matrix has rows.',
      },
      {
        prompt: 'The i-th entry of y = W r equals...',
        options: [
          '\u03a3\u2c7c W_{ij} r\u2c7c',
          '\u03a0\u2c7c r\u2c7c',
          'r\u1d62',
          '\u03a3\u2c7c W_{ji} r\u1d62',
        ],
        answerIndex: 0,
        explanation: 'It is the dot product of the i-th row of W with r.',
      },
      {
        prompt: 'A neural interpretation of y = W r is...',
        options: [
          'Each neuron runs independent physics',
          'Each postsynaptic neuron computes a weighted sum of its inputs',
          'Only one neuron is active',
          'The network fires all at once with the same value',
        ],
        answerIndex: 1,
        explanation: 'Every output entry is one postsynaptic neuron\u2019s weighted sum of its inputs.',
      },
    ],
    xpReward: 22,
    coinReward: 8,
    masteryThreshold: 0.8,
  },
  {
    id: 'B11',
    trackId: 'math',
    moduleId: 'B-matrices',
    order: 11,
    title: 'Weighted sum',
    subtitle: 'The most useful operation in this app',
    estimatedMinutes: 4,
    difficulty: 'beginner',
    prerequisites: ['B10'],
    explanation:
      'A weighted sum multiplies each component of a vector by a weight and adds the results. \u03a3\u1d62 w\u1d62 x\u1d62 is how neurons combine their inputs, how we score decisions, and how most linear features of neural models work.',
    notation: 'u = \u03a3\u1d62 w\u1d62 x\u1d62',
    keyTerms: ['weight', 'inner product', 'dot product'],
    example:
      'A postsynaptic neuron computes u = \u03a3\u1d62 w\u1d62 r\u1d62 where w\u1d62 is its synaptic strength from neuron i and r\u1d62 is that neuron\u2019s firing rate.',
    intuition: 'A weighted sum is a vote where each voter has their own volume.',
    whyItMatters:
      'Dot products, projections, decoding, and linear filters all start here.',
    questions: [
      {
        prompt: 'With w = (0.5, 0.5) and x = (4, 6), the weighted sum is...',
        options: ['5', '10', '24', '\u22122'],
        answerIndex: 0,
        explanation: '0.5*4 + 0.5*6 = 2 + 3 = 5.',
      },
      {
        prompt: 'A neuron increases its output to a stimulus by...',
        options: [
          'Removing weights',
          'Strengthening weights for relevant inputs',
          'Randomising weights',
          'Deleting its soma',
        ],
        answerIndex: 1,
        explanation: 'Larger positive weights for informative inputs increase the weighted sum.',
      },
      {
        prompt: 'The dot product w \u00b7 x is another name for...',
        options: ['The cross product', 'A weighted sum', 'A matrix product', 'A trace'],
        answerIndex: 1,
        explanation: 'The dot product and weighted sum are the same operation.',
      },
    ],
    xpReward: 20,
    coinReward: 7,
    masteryThreshold: 0.8,
  },
  {
    id: 'B12',
    trackId: 'math',
    moduleId: 'B-matrices',
    order: 12,
    title: 'Connectivity matrix',
    subtitle: 'A circuit written down as a grid',
    estimatedMinutes: 5,
    difficulty: 'beginner',
    prerequisites: ['B11'],
    explanation:
      'A connectivity matrix stores every pairwise connection in a circuit. Entry W_{ij} is how strongly neuron j influences neuron i. Zero means no connection, positive often means excitatory, negative means inhibitory.',
    notation: 'W_{ij} \u2208 \u211d',
    keyTerms: ['connectivity', 'recurrent', 'sparse', 'sign'],
    example:
      'Recurrent cortical models often use a square N\u00d7N weight matrix where each entry reflects a learned or random synaptic strength.',
    intuition: 'A circuit is not a pile of wires. It is a grid of "how much does A move B".',
    whyItMatters:
      'Recurrent networks and their stability analyses live and die on the structure of W.',
    questions: [
      {
        prompt: 'In W_{ij}, if the entry is large and positive...',
        options: [
          'Neuron j strongly inhibits neuron i',
          'Neuron j strongly excites neuron i',
          'Neuron i is disconnected',
          'The matrix is illegal',
        ],
        answerIndex: 1,
        explanation: 'A large positive entry usually reflects a strong excitatory influence from j to i.',
      },
      {
        prompt: 'If most entries of W are zero, the network is...',
        options: ['Dense', 'Sparse', 'Symmetric', 'Orthogonal'],
        answerIndex: 1,
        explanation: 'Sparse means most connections are absent.',
      },
      {
        prompt: 'A symmetric connectivity matrix has...',
        options: [
          'W_{ij} = W_{ji}',
          'W_{ij} = 0',
          'Only positive entries',
          'No diagonal entries',
        ],
        answerIndex: 0,
        explanation: 'Symmetry means the entry from i to j equals the entry from j to i.',
      },
    ],
    xpReward: 22,
    coinReward: 8,
    masteryThreshold: 0.8,
  },
  {
    id: 'B13',
    trackId: 'math',
    moduleId: 'B-functions',
    order: 13,
    title: 'Function',
    subtitle: 'A machine that turns inputs into outputs',
    estimatedMinutes: 4,
    difficulty: 'beginner',
    prerequisites: ['B06'],
    explanation:
      'A function takes an input and produces exactly one output. Writing f(x) = y means: give me an x, I give you back a y. Neurons can be thought of as functions mapping inputs to firing rates.',
    notation: 'f: \u211d \u2192 \u211d,  y = f(x)',
    keyTerms: ['function', 'input', 'output', 'transfer function'],
    example:
      'A simple firing-rate model is r = f(u), where u is a weighted input and f is a saturating nonlinearity like a sigmoid.',
    intuition: 'A function is a vending machine that always gives the same item for the same coin.',
    whyItMatters:
      'Transfer functions (also called activation functions) sit at the heart of every rate model and every neural network.',
    questions: [
      {
        prompt: 'A function must produce...',
        options: [
          'Zero outputs per input',
          'Exactly one output per input',
          'Many outputs per input',
          'An input for every output',
        ],
        answerIndex: 1,
        explanation: 'A function assigns a single output to each input.',
      },
      {
        prompt: 'In r = f(u), u is called the...',
        options: ['Output', 'Input', 'Label', 'Error'],
        answerIndex: 1,
        explanation: 'The input to the function is u, and the output is r.',
      },
      {
        prompt: 'A saturating transfer function...',
        options: [
          'Produces unbounded outputs',
          'Caps output at a maximum as input grows',
          'Only has negative outputs',
          'Is linear everywhere',
        ],
        answerIndex: 1,
        explanation: 'It approaches a plateau for large inputs.',
      },
    ],
    xpReward: 18,
    coinReward: 6,
    masteryThreshold: 0.8,
  },
  {
    id: 'B14',
    trackId: 'math',
    moduleId: 'B-calculus',
    order: 14,
    title: 'Derivative intuition',
    subtitle: 'Rate of change without the scary notation',
    estimatedMinutes: 5,
    difficulty: 'beginner',
    prerequisites: ['B13'],
    explanation:
      'The derivative of f at a point tells you how fast f is changing there. If f is a function of time, df/dt is the instantaneous rate of change. If df/dt is positive, f is rising; if negative, falling; if zero, flat.',
    notation: 'df/dt = rate of change of f with respect to t',
    keyTerms: ['derivative', 'slope', 'rate of change'],
    example:
      'If V(t) is the voltage of a neuron, dV/dt describes how quickly the voltage is moving at time t.',
    intuition: 'The derivative is the speedometer. The function itself is your position.',
    whyItMatters:
      'Every differential equation you will see is a rule that says what df/dt should equal.',
    questions: [
      {
        prompt: 'If df/dt > 0 at some time, then f is...',
        options: ['Decreasing', 'Constant', 'Increasing', 'Undefined'],
        answerIndex: 2,
        explanation: 'Positive derivative means f is rising at that moment.',
      },
      {
        prompt: 'At a flat maximum of f(t), df/dt is...',
        options: ['Large positive', 'Large negative', 'Approximately zero', 'Complex-valued'],
        answerIndex: 2,
        explanation: 'At a maximum the instantaneous slope is zero.',
      },
      {
        prompt: 'For membrane voltage V(t), dV/dt is...',
        options: [
          'The voltage itself',
          'The rate of change of voltage',
          'The resting potential',
          'The final voltage',
        ],
        answerIndex: 1,
        explanation: 'It is the speed at which voltage is changing.',
      },
    ],
    xpReward: 22,
    coinReward: 8,
    masteryThreshold: 0.8,
  },
  {
    id: 'B15',
    trackId: 'math',
    moduleId: 'B-calculus',
    order: 15,
    title: 'Differential equation intuition',
    subtitle: 'Rules for how things change',
    estimatedMinutes: 5,
    difficulty: 'beginner',
    prerequisites: ['B14'],
    explanation:
      'A differential equation is a rule that connects a quantity to its rate of change. A classic example is \u03c4 dV/dt = \u2212(V \u2212 V_rest), which says: whenever the voltage drifts away from rest, it decays back toward it with time constant \u03c4.',
    notation: '\u03c4 dV/dt = \u2212(V \u2212 V_rest)',
    keyTerms: ['ODE', 'time constant', 'steady state'],
    example:
      'A simple leaky neuron relaxes toward its resting potential whenever no input is present.',
    intuition: 'Differential equations are recipes that describe how now becomes next.',
    whyItMatters:
      'Most neuron models, rate models, and learning rules are written as differential equations.',
    questions: [
      {
        prompt: 'In \u03c4 dV/dt = \u2212(V \u2212 V_rest), if V > V_rest, then dV/dt is...',
        options: ['Positive', 'Zero', 'Negative', 'Undefined'],
        answerIndex: 2,
        explanation: 'The right side becomes negative, so V decreases back toward rest.',
      },
      {
        prompt: 'The time constant \u03c4 controls...',
        options: [
          'The height of the spike',
          'How fast the system relaxes',
          'The reversal potential',
          'The total number of neurons',
        ],
        answerIndex: 1,
        explanation: 'A smaller \u03c4 means faster relaxation; a larger \u03c4 is slower.',
      },
      {
        prompt: 'A steady state of a differential equation satisfies...',
        options: [
          'dV/dt = 0',
          'V = 0',
          'V > V_rest always',
          'V is time-dependent',
        ],
        answerIndex: 0,
        explanation: 'At steady state the rate of change vanishes.',
      },
    ],
    xpReward: 22,
    coinReward: 8,
    masteryThreshold: 0.8,
  },
  {
    id: 'B16',
    trackId: 'math',
    moduleId: 'B-dynamics',
    order: 16,
    title: 'State of a system',
    subtitle: 'What do we need to know right now?',
    estimatedMinutes: 4,
    difficulty: 'beginner',
    prerequisites: ['B15'],
    explanation:
      'The state of a dynamical system at time t is the smallest set of numbers needed to predict its future given the inputs. For a single leaky neuron, the state is the voltage V. For a network of N neurons, the state is a vector of their N voltages (or rates).',
    notation: 'x(t) = state vector',
    keyTerms: ['state', 'state vector', 'initial condition'],
    example:
      'In a recurrent rate model with N = 500 neurons, the state at any time is a 500-dimensional vector.',
    intuition: 'The state is a complete snapshot that determines what happens next.',
    whyItMatters:
      'Talking about state is what lets you reason about neural dynamics precisely.',
    questions: [
      {
        prompt: 'The state of a single leaky neuron is typically...',
        options: [
          'Its spike count',
          'Its membrane voltage',
          'Its color',
          'Its synaptic address',
        ],
        answerIndex: 1,
        explanation: 'For a leaky membrane, V alone is enough to predict the future.',
      },
      {
        prompt: 'The state of a 500-neuron rate network is a...',
        options: ['Scalar', '500-dimensional vector', 'Single matrix', 'Empty set'],
        answerIndex: 1,
        explanation: 'You need one number per neuron.',
      },
      {
        prompt: 'An initial condition tells you...',
        options: [
          'What future inputs will be',
          'The starting state of the system',
          'The reversal potential',
          'The output label',
        ],
        answerIndex: 1,
        explanation: 'It is the value of the state at time zero.',
      },
    ],
    xpReward: 20,
    coinReward: 7,
    masteryThreshold: 0.8,
  },
  {
    id: 'B17',
    trackId: 'math',
    moduleId: 'B-dynamics',
    order: 17,
    title: 'State space',
    subtitle: 'All possible states at once',
    estimatedMinutes: 4,
    difficulty: 'beginner',
    prerequisites: ['B16'],
    explanation:
      'The state space is the set of all possible states a system can take. For a single leaky neuron it is an interval of voltages. For a network it is a high-dimensional space. The trajectory of the system is a curve through that space over time.',
    notation: 'x(t) \u2208 X (the state space)',
    keyTerms: ['state space', 'trajectory', 'phase space'],
    example:
      'Picture a 2-neuron network with firing rates (r\u2081, r\u2082). Its state space is a 2D plane and its trajectory is a curve through that plane over time.',
    intuition: 'State space is the map. The trajectory is your path across the map.',
    whyItMatters:
      'Thinking in state space is the main modern lens on neural dynamics.',
    questions: [
      {
        prompt: 'A trajectory is...',
        options: [
          'A random spike',
          'A curve through state space over time',
          'A synaptic weight',
          'A static snapshot',
        ],
        answerIndex: 1,
        explanation: 'A trajectory traces how the state changes as time advances.',
      },
      {
        prompt: 'The state space of a 2-neuron rate network is...',
        options: ['A point', 'A 2D plane', 'A 100D hyperspace', 'Empty'],
        answerIndex: 1,
        explanation: 'With two rates you need two numbers, so the space is 2D.',
      },
      {
        prompt: 'Neural trajectories are a useful concept because...',
        options: [
          'They hide the math',
          'They let us picture population activity as geometry',
          'They replace spikes entirely',
          'They apply only to static inputs',
        ],
        answerIndex: 1,
        explanation: 'They turn time-varying high-dimensional activity into geometric curves we can reason about.',
      },
    ],
    xpReward: 20,
    coinReward: 7,
    masteryThreshold: 0.8,
  },
  {
    id: 'B18',
    trackId: 'math',
    moduleId: 'B-prob',
    order: 18,
    title: 'Random variable',
    subtitle: 'When the next number is uncertain',
    estimatedMinutes: 5,
    difficulty: 'beginner',
    prerequisites: ['B13'],
    explanation:
      'A random variable is a quantity whose value is uncertain, described by a probability distribution. A single draw gives a concrete number, but across many draws the values follow the distribution.',
    notation: 'X ~ P  (X is distributed as P)',
    keyTerms: ['random variable', 'distribution', 'probability'],
    example:
      'The number of spikes fired by a neuron in a 100 ms window can be treated as a random variable with its own distribution.',
    intuition: 'A random variable is a die that always follows the same unseen rules.',
    whyItMatters:
      'Neural signals are noisy. Treating them as random variables is how we reason about that noise.',
    questions: [
      {
        prompt: 'A random variable is best described as...',
        options: [
          'A fixed number',
          'A quantity with a probability distribution',
          'A synaptic weight',
          'A matrix',
        ],
        answerIndex: 1,
        explanation: 'Its value is uncertain but follows a known distribution.',
      },
      {
        prompt: '"X ~ P" reads as...',
        options: [
          'X equals P',
          'X is distributed according to P',
          'X approximates P',
          'X contains P',
        ],
        answerIndex: 1,
        explanation: 'It says X follows the distribution P.',
      },
      {
        prompt: 'A single realisation (draw) of a random variable is...',
        options: [
          'A distribution',
          'A concrete value sampled from the distribution',
          'A derivative',
          'A synapse',
        ],
        answerIndex: 1,
        explanation: 'A sample is a single concrete outcome.',
      },
    ],
    xpReward: 22,
    coinReward: 8,
    masteryThreshold: 0.8,
  },
  {
    id: 'B19',
    trackId: 'math',
    moduleId: 'B-prob',
    order: 19,
    title: 'Binary spike and Bernoulli',
    subtitle: 'The simplest random neuron event',
    estimatedMinutes: 5,
    difficulty: 'beginner',
    prerequisites: ['B18'],
    explanation:
      'Within a very short time window, we can treat the presence of a spike as a binary event: 1 if it fires, 0 if it does not. If the probability of firing is p, this is a Bernoulli random variable with mean p.',
    notation: 'X \u2208 {0, 1},  P(X=1) = p',
    keyTerms: ['Bernoulli', 'binary variable', 'spike probability'],
    example:
      'In a 1 ms bin, a neuron either spiked (1) or did not (0). Over many trials, the average of these binary outcomes estimates the spike probability p.',
    intuition: 'A tiny time bin is a coin flip, and p is how biased the coin is.',
    whyItMatters:
      'Discretising spike trains into binary vectors is the starting point of countless analyses.',
    questions: [
      {
        prompt: 'A Bernoulli random variable has possible values...',
        options: ['Any real number', '0 or 1', '0, 1, or 2', 'Only 1'],
        answerIndex: 1,
        explanation: 'Bernoulli outcomes are binary: 0 or 1.',
      },
      {
        prompt: 'The mean of a Bernoulli(p) random variable is...',
        options: ['0.5', '1 \u2212 p', 'p', 'p\u00b2'],
        answerIndex: 2,
        explanation: 'E[X] = p for Bernoulli(p).',
      },
      {
        prompt: 'Estimating p from spike data uses...',
        options: [
          'A single trial',
          'The average number of 1s over many trials',
          'The derivative of spikes',
          'A matrix inversion',
        ],
        answerIndex: 1,
        explanation: 'You estimate p as the empirical fraction of trials with a spike.',
      },
    ],
    xpReward: 22,
    coinReward: 8,
    masteryThreshold: 0.8,
  },
  {
    id: 'B20',
    trackId: 'math',
    moduleId: 'B-prob',
    order: 20,
    title: 'Spike counts and Poisson',
    subtitle: 'Counting spikes in bigger windows',
    estimatedMinutes: 5,
    difficulty: 'beginner',
    prerequisites: ['B19'],
    explanation:
      'A Poisson distribution describes the number of independent events in a fixed interval given an average rate \u03bb. Spike counts from neurons are often approximated as Poisson for simplicity. Its mean and variance both equal \u03bb.',
    notation: 'X ~ Poisson(\u03bb),  E[X] = Var[X] = \u03bb',
    keyTerms: ['Poisson', 'spike count', 'variance'],
    example:
      'If a neuron fires about 5 spikes on average per 100 ms window, a Poisson(5) distribution gives a rough baseline model of its spike counts.',
    intuition: 'Poisson is what happens when many rare independent events add up.',
    whyItMatters:
      'It is the standard starting point for noisy spike-count models.',
    questions: [
      {
        prompt: 'For X ~ Poisson(\u03bb), the mean equals...',
        options: ['\u03bb', '\u03bb\u00b2', '1/\u03bb', '0'],
        answerIndex: 0,
        explanation: 'Poisson has mean \u03bb.',
      },
      {
        prompt: 'For Poisson, the variance equals...',
        options: ['0', '1', '\u03bb', '\u03bb\u00b2'],
        answerIndex: 2,
        explanation: 'A defining property: mean equals variance.',
      },
      {
        prompt: 'Poisson is a reasonable rough model for...',
        options: [
          'Precisely periodic spikes',
          'Independent, random spikes in a fixed window',
          'Perfectly silent neurons',
          'Deterministic voltage traces',
        ],
        answerIndex: 1,
        explanation: 'Poisson fits roughly independent random events over a fixed window.',
      },
    ],
    xpReward: 22,
    coinReward: 8,
    masteryThreshold: 0.8,
  },
  {
    id: 'B21',
    trackId: 'math',
    moduleId: 'B-spaces',
    order: 21,
    title: 'Dot product',
    subtitle: 'Multiplying two vectors into one number',
    estimatedMinutes: 5,
    difficulty: 'beginner',
    prerequisites: ['B20'],
    explanation:
      'The dot product of two vectors of the same length multiplies them entry-by-entry and adds the results. It returns a single scalar that measures how much the two vectors point in the same direction.',
    notation: 'u · v = Σᵢ uᵢ vᵢ',
    keyTerms: ['dot product', 'inner product', 'alignment', 'scalar'],
    example:
      'A neuron computing a weighted sum of its inputs is computing the dot product between the weight vector w and the input vector x.',
    intuition: 'It is the simplest measure of how aligned two lists of numbers are.',
    whyItMatters:
      'Almost every neural computation - weighted sums, projections, similarity - is a dot product in disguise.',
    questions: [
      {
        prompt: 'For u = (1, 2) and v = (3, 4), the dot product u · v equals...',
        options: ['7', '11', '14', '12'],
        answerIndex: 1,
        explanation: '1·3 + 2·4 = 3 + 8 = 11.',
      },
      {
        prompt: 'A neuron with weights w receives input x. Its weighted sum is...',
        options: ['x · x', 'w · w', 'w · x', 'a matrix product'],
        answerIndex: 2,
        explanation: 'The weighted sum is the dot product of weights and inputs.',
      },
      {
        prompt: 'If u and v point in opposite directions, u · v is...',
        options: ['Positive', 'Zero', 'Negative', 'Undefined'],
        answerIndex: 2,
        explanation: 'Opposite directions give a negative scalar.',
      },
    ],
    xpReward: 22,
    coinReward: 8,
    masteryThreshold: 0.8,
  },
  {
    id: 'B22',
    trackId: 'math',
    moduleId: 'B-spaces',
    order: 22,
    title: 'Vector norm',
    subtitle: 'How long is this vector?',
    estimatedMinutes: 4,
    difficulty: 'beginner',
    prerequisites: ['B21'],
    explanation:
      'The norm (or length) of a vector is the square root of its dot product with itself. In two or three dimensions it agrees with the everyday notion of length and is computed via the Pythagorean theorem.',
    notation: '‖v‖ = √(v · v)',
    keyTerms: ['norm', 'length', 'magnitude', 'unit vector'],
    example:
      'A firing-rate vector r = (3, 4) over two neurons has norm √(9 + 16) = 5 - a single number summarising its overall magnitude.',
    intuition: 'Norm = how far the vector reaches from the origin.',
    whyItMatters:
      'Many distances, errors, and energies in neural models are vector norms.',
    questions: [
      {
        prompt: 'The norm of (0, 3, 4) is...',
        options: ['7', '12', '5', '√25 / 2'],
        answerIndex: 2,
        explanation: '√(0 + 9 + 16) = √25 = 5.',
      },
      {
        prompt: 'A unit vector has norm equal to...',
        options: ['0', '1', 'Its length', '√2'],
        answerIndex: 1,
        explanation: 'Unit vectors are normalised so ‖v‖ = 1.',
      },
      {
        prompt: 'Doubling every entry of v changes its norm by a factor of...',
        options: ['1', '√2', '2', '4'],
        answerIndex: 2,
        explanation: 'Norm is linear in scale: ‖2v‖ = 2‖v‖.',
      },
    ],
    xpReward: 20,
    coinReward: 7,
    masteryThreshold: 0.8,
  },
  {
    id: 'B23',
    trackId: 'math',
    moduleId: 'B-spaces',
    order: 23,
    title: 'Orthogonality and angle',
    subtitle: 'When vectors are at right angles',
    estimatedMinutes: 5,
    difficulty: 'beginner',
    prerequisites: ['B22'],
    explanation:
      'The dot product encodes the angle between two vectors: u · v = ‖u‖ ‖v‖ cos θ. Two non-zero vectors are orthogonal when their dot product is zero, meaning the angle between them is 90°.',
    notation: 'cos θ = (u · v) / (‖u‖ ‖v‖)',
    keyTerms: ['orthogonal', 'angle', 'cosine similarity'],
    example:
      'Two population activity vectors are orthogonal when knowing the response of one tells you nothing about the projection along the other.',
    intuition: 'Zero dot product = at right angles = no shared direction.',
    whyItMatters:
      'Orthogonality is the basis of independent components, principal axes, and neural subspaces.',
    questions: [
      {
        prompt: 'If u · v = 0 and both are non-zero, the angle between them is...',
        options: ['0°', '45°', '90°', '180°'],
        answerIndex: 2,
        explanation: 'A zero dot product means orthogonal.',
      },
      {
        prompt: 'Cosine similarity between two vectors is...',
        options: ['Always 1', 'Their dot product divided by the product of their norms', 'Their sum', 'Their cross product'],
        answerIndex: 1,
        explanation: 'It normalises the dot product to focus on direction.',
      },
      {
        prompt: 'Two vectors pointing in the same direction have cosine similarity equal to...',
        options: ['-1', '0', '1', '∞'],
        answerIndex: 2,
        explanation: 'cos 0° = 1.',
      },
    ],
    xpReward: 22,
    coinReward: 8,
    masteryThreshold: 0.8,
  },
  {
    id: 'B24',
    trackId: 'math',
    moduleId: 'B-spaces',
    order: 24,
    title: 'Projection',
    subtitle: 'Shadow of one vector along another',
    estimatedMinutes: 5,
    difficulty: 'beginner',
    prerequisites: ['B23'],
    explanation:
      'The projection of v onto a unit vector u is the scalar u · v, and the projected vector is (u · v) u. Projection extracts the component of v along the direction u.',
    notation: 'proj_u(v) = (u · v) u   (u unit)',
    keyTerms: ['projection', 'component', 'orthogonal complement'],
    example:
      'Projecting a population firing rate vector onto a stimulus axis gives a scalar that summarises how much the population represents that stimulus.',
    intuition: 'Projection answers "how much of v points along u?"',
    whyItMatters:
      'Decoding, dimensionality reduction, and population analyses are projections.',
    questions: [
      {
        prompt: 'For unit u, the scalar projection of v onto u is...',
        options: ['‖v‖', 'u · v', 'v · v', '‖u‖'],
        answerIndex: 1,
        explanation: 'Projection onto a unit vector is just the dot product.',
      },
      {
        prompt: 'If v is orthogonal to u, the projection of v onto u is...',
        options: ['v itself', 'The zero vector', 'A unit vector', 'Undefined'],
        answerIndex: 1,
        explanation: 'Orthogonal vectors have zero projection.',
      },
      {
        prompt: 'Projecting a population vector onto a single direction reduces dimensionality from n to...',
        options: ['n + 1', 'n', '1', '0'],
        answerIndex: 2,
        explanation: 'A scalar projection is one dimensional.',
      },
    ],
    xpReward: 22,
    coinReward: 8,
    masteryThreshold: 0.8,
  },
  {
    id: 'B25',
    trackId: 'math',
    moduleId: 'B-spaces',
    order: 25,
    title: 'Linear independence and basis',
    subtitle: 'Coordinate systems for vectors',
    estimatedMinutes: 5,
    difficulty: 'intermediate',
    prerequisites: ['B24'],
    explanation:
      'A set of vectors is linearly independent if none can be written as a weighted sum of the others. A basis of an n-dimensional space is a set of n linearly independent vectors. Every vector in the space has unique coordinates in any basis.',
    keyTerms: ['linear independence', 'span', 'basis', 'coordinates'],
    example:
      'In a population of n neurons, choosing n orthogonal directions in firing-rate space gives a basis in which any pattern of activity has a unique decomposition.',
    intuition: 'Independent vectors carry non-redundant directions; a basis is enough of them to describe the whole space.',
    whyItMatters:
      'Choosing the right basis (e.g. PCA axes) is what makes high-dimensional data interpretable.',
    questions: [
      {
        prompt: 'A basis of ℝ³ must contain...',
        options: ['1 vector', '2 vectors', '3 linearly independent vectors', '4 vectors'],
        answerIndex: 2,
        explanation: 'The dimension equals the number of basis vectors.',
      },
      {
        prompt: 'Three vectors with one being the sum of the other two are...',
        options: ['Linearly independent', 'Linearly dependent', 'Orthonormal', 'A basis'],
        answerIndex: 1,
        explanation: 'A linear combination relation makes them dependent.',
      },
      {
        prompt: 'The standard basis of ℝⁿ consists of...',
        options: [
          'Random vectors',
          'The unit vectors along each axis',
          'A single vector',
          'Only the zero vector',
        ],
        answerIndex: 1,
        explanation: 'e₁, e₂, ..., eₙ form the canonical basis.',
      },
    ],
    xpReward: 24,
    coinReward: 9,
    masteryThreshold: 0.8,
  },
  {
    id: 'B26',
    trackId: 'math',
    moduleId: 'B-matrices',
    order: 26,
    title: 'Transpose',
    subtitle: 'Swapping rows and columns',
    estimatedMinutes: 4,
    difficulty: 'beginner',
    prerequisites: ['B12'],
    explanation:
      'The transpose Aᵀ of a matrix A swaps its rows and columns: (Aᵀ)ᵢⱼ = Aⱼᵢ. For a column vector v, vᵀ is a row vector, and vᵀ w equals the dot product v · w.',
    notation: '(Aᵀ)ᵢⱼ = Aⱼᵢ',
    keyTerms: ['transpose', 'symmetric matrix', 'row vector', 'column vector'],
    example:
      'A symmetric connectivity matrix W with W = Wᵀ means the connection from neuron i to neuron j has the same weight as from j to i.',
    intuition: 'Transpose is just turning a matrix on its side.',
    whyItMatters:
      'Many neural and statistical formulas (covariance, gradient, energy) involve a matrix multiplied by its transpose.',
    questions: [
      {
        prompt: 'If A is 3 x 4, then Aᵀ has shape...',
        options: ['3 x 4', '4 x 3', '3 x 3', '4 x 4'],
        answerIndex: 1,
        explanation: 'Transpose flips dimensions.',
      },
      {
        prompt: 'A symmetric matrix satisfies...',
        options: ['A = -A', 'A = Aᵀ', 'A = 0', 'A is diagonal'],
        answerIndex: 1,
        explanation: 'Symmetry means it equals its own transpose.',
      },
      {
        prompt: 'For column vectors v and w, vᵀ w is...',
        options: ['A matrix', 'Their dot product (a scalar)', 'A vector', 'Undefined'],
        answerIndex: 1,
        explanation: 'A 1×n times n×1 multiplies to a scalar.',
      },
    ],
    xpReward: 20,
    coinReward: 7,
    masteryThreshold: 0.8,
  },
  {
    id: 'B27',
    trackId: 'math',
    moduleId: 'B-matrices',
    order: 27,
    title: 'Matrix multiplication',
    subtitle: 'Composing two grids of numbers',
    estimatedMinutes: 6,
    difficulty: 'intermediate',
    prerequisites: ['B26'],
    explanation:
      'The product C = A B has entry Cᵢⱼ = Σₖ Aᵢₖ Bₖⱼ. It composes two linear transformations, applying B first and then A, and the inner dimensions must match.',
    notation: '(A B)ᵢⱼ = Σₖ Aᵢₖ Bₖⱼ',
    keyTerms: ['matrix product', 'composition', 'inner dimension'],
    example:
      'Stacking two linear network layers W₁ then W₂ with no non-linearity in between is the same as one linear layer W₂ W₁.',
    intuition: 'Multiplying matrices = piping one linear transformation through another.',
    whyItMatters:
      'Every deep linear computation, from circuits to neural networks, is repeated matrix multiplication.',
    questions: [
      {
        prompt: 'For matrix multiplication A B, the inner dimensions must...',
        options: ['Both be 1', 'Match', 'Both be square', 'Be different'],
        answerIndex: 1,
        explanation: 'A: m×k and B: k×n share the inner k.',
      },
      {
        prompt: 'In general, matrix multiplication is...',
        options: ['Commutative', 'Not commutative: A B ≠ B A in general', 'Always zero', 'Always symmetric'],
        answerIndex: 1,
        explanation: 'A B and B A are usually different (and may have different shapes).',
      },
      {
        prompt: 'Stacking two purely linear layers with no non-linearity is equivalent to...',
        options: ['Two non-linear layers', 'A single linear layer', 'A constant', 'A non-linear function'],
        answerIndex: 1,
        explanation: 'W₂ W₁ is itself one matrix.',
      },
    ],
    xpReward: 24,
    coinReward: 9,
    masteryThreshold: 0.8,
  },
  {
    id: 'B28',
    trackId: 'math',
    moduleId: 'B-matrices',
    order: 28,
    title: 'Identity, inverse, determinant',
    subtitle: 'Undoing a linear map',
    estimatedMinutes: 5,
    difficulty: 'intermediate',
    prerequisites: ['B27'],
    explanation:
      'The identity I leaves every vector unchanged: I v = v. The inverse A⁻¹ satisfies A A⁻¹ = I when it exists. The determinant det(A) is a single number; det(A) = 0 exactly when A has no inverse.',
    notation: 'A A⁻¹ = I,   det(A) = 0 ⇒ not invertible',
    keyTerms: ['identity', 'inverse', 'determinant', 'singular'],
    example:
      'Decoding a population requires inverting (or pseudo-inverting) a connectivity-like matrix; if it is singular, some patterns are unrecoverable.',
    intuition: 'Inverse undoes the matrix; determinant tells you if it is reversible at all.',
    whyItMatters:
      'Inversion underlies decoding, regression, and many fitting procedures.',
    questions: [
      {
        prompt: 'A matrix is invertible exactly when...',
        options: ['Its determinant is zero', 'Its determinant is non-zero', 'It has more rows than columns', 'It is the identity'],
        answerIndex: 1,
        explanation: 'Non-zero determinant ⇔ invertible.',
      },
      {
        prompt: 'I times any vector v gives...',
        options: ['0', 'A scaled v', 'v', 'v transposed'],
        answerIndex: 2,
        explanation: 'The identity matrix leaves vectors unchanged.',
      },
      {
        prompt: 'A singular matrix...',
        options: ['Has an inverse', 'Has determinant zero and no inverse', 'Is always the identity', 'Has determinant 1'],
        answerIndex: 1,
        explanation: 'Singular = not invertible.',
      },
    ],
    xpReward: 24,
    coinReward: 9,
    masteryThreshold: 0.8,
  },
  {
    id: 'B29',
    trackId: 'math',
    moduleId: 'B-eigen',
    order: 29,
    title: 'Eigenvalues and eigenvectors',
    subtitle: 'Directions a matrix only stretches',
    estimatedMinutes: 6,
    difficulty: 'intermediate',
    prerequisites: ['B28'],
    explanation:
      'A non-zero vector v is an eigenvector of A if A v = λ v for some scalar λ, the eigenvalue. The matrix only stretches v along its own direction. Eigenvalues control how this stretching grows or shrinks under repeated application.',
    notation: 'A v = λ v',
    keyTerms: ['eigenvalue', 'eigenvector', 'spectrum', 'stability'],
    example:
      'In a linear recurrent network, the eigenvalues of the connectivity matrix decide whether activity grows, oscillates, or decays.',
    intuition: 'Eigenvectors are the matrix’s natural axes; eigenvalues are how much it stretches along each.',
    whyItMatters:
      'Stability of dynamical systems, principal components, and Markov chains all hinge on eigenvalues.',
    questions: [
      {
        prompt: 'If A v = λ v with v ≠ 0, then v is...',
        options: ['Always zero', 'An eigenvector with eigenvalue λ', 'A determinant', 'The identity'],
        answerIndex: 1,
        explanation: 'That equation defines eigenvectors and eigenvalues.',
      },
      {
        prompt: 'For a linear recurrent network, activity blows up when the connectivity matrix has an eigenvalue with...',
        options: ['Real part > 1 (in discrete time) or > 0 (in continuous time)', 'Real part < 0', 'Imaginary part = 0', 'Magnitude 0'],
        answerIndex: 0,
        explanation: 'Positive growth rate or magnitude > 1 destabilises the system.',
      },
      {
        prompt: 'Eigenvectors of a symmetric matrix can always be chosen to be...',
        options: ['Linearly dependent', 'Mutually orthogonal', 'Equal', 'Random'],
        answerIndex: 1,
        explanation: 'Symmetric matrices have an orthonormal eigenbasis.',
      },
    ],
    xpReward: 26,
    coinReward: 10,
    masteryThreshold: 0.8,
  },
  {
    id: 'B30',
    trackId: 'math',
    moduleId: 'B-eigen',
    order: 30,
    title: 'Diagonalisation and SVD',
    subtitle: 'Reading a matrix in its natural basis',
    estimatedMinutes: 6,
    difficulty: 'intermediate',
    prerequisites: ['B29'],
    explanation:
      'A diagonalisable matrix can be written A = P Λ P⁻¹ where Λ is diagonal with the eigenvalues. The Singular Value Decomposition generalises this to any rectangular matrix: A = U Σ Vᵀ with non-negative singular values on the diagonal.',
    notation: 'A = U Σ Vᵀ',
    keyTerms: ['diagonalisation', 'SVD', 'singular value', 'low-rank approximation'],
    example:
      'PCA on neural population activity is essentially the SVD of the centred data matrix; the largest singular values pick out the dominant population modes.',
    intuition: 'SVD: every linear map is rotate, stretch along axes, rotate again.',
    whyItMatters:
      'Low-rank approximations, denoising, and population manifolds all rely on SVD/PCA.',
    questions: [
      {
        prompt: 'In A = U Σ Vᵀ, the entries of Σ are the...',
        options: ['Eigenvectors', 'Singular values', 'Determinants', 'Rotations'],
        answerIndex: 1,
        explanation: 'Singular values are non-negative diagonal entries.',
      },
      {
        prompt: 'A low-rank approximation keeps...',
        options: [
          'All singular values',
          'Only the largest few singular values and their vectors',
          'No singular values',
          'Only the smallest singular value',
        ],
        answerIndex: 1,
        explanation: 'Truncating small singular values gives the best low-rank fit.',
      },
      {
        prompt: 'PCA on centred data is essentially...',
        options: ['Random projection', 'The SVD of the data matrix', 'A determinant', 'Matrix inversion only'],
        answerIndex: 1,
        explanation: 'PCA components are right singular vectors; variances are squared singular values.',
      },
    ],
    xpReward: 28,
    coinReward: 11,
    masteryThreshold: 0.8,
  },
  {
    id: 'B31',
    trackId: 'math',
    moduleId: 'B-calculus',
    order: 31,
    title: 'Partial derivative',
    subtitle: 'Change in one direction at a time',
    estimatedMinutes: 5,
    difficulty: 'beginner',
    prerequisites: ['B14'],
    explanation:
      'For a function of several variables f(x, y, ...), the partial derivative ∂f/∂x is the rate of change of f as you vary x while holding the others fixed.',
    notation: '∂f/∂x = lim h→0 (f(x+h, y) - f(x, y)) / h',
    keyTerms: ['partial derivative', 'multivariable', 'sensitivity'],
    example:
      'A neuron’s output as a function of two synapses depends on each independently; partial derivatives measure each synapse’s sensitivity.',
    intuition: 'Treat all other variables as constants and take an ordinary derivative.',
    whyItMatters:
      'Partial derivatives are the building blocks of gradients, optimisation, and learning rules.',
    questions: [
      {
        prompt: 'For f(x, y) = x² + y, the partial derivative ∂f/∂x is...',
        options: ['1', '2x', '2x + 1', 'x²'],
        answerIndex: 1,
        explanation: 'Treating y as constant, d/dx (x² + y) = 2x.',
      },
      {
        prompt: 'A partial derivative measures change with respect to...',
        options: ['All variables at once', 'One variable, others fixed', 'A constant', 'Time only'],
        answerIndex: 1,
        explanation: 'Other variables are held constant by definition.',
      },
      {
        prompt: 'In ML, partials of the loss with respect to weights are called...',
        options: ['Hessians', 'Gradients (component-wise)', 'Activations', 'Losses'],
        answerIndex: 1,
        explanation: 'They form the gradient vector used by optimisers.',
      },
    ],
    xpReward: 22,
    coinReward: 8,
    masteryThreshold: 0.8,
  },
  {
    id: 'B32',
    trackId: 'math',
    moduleId: 'B-calculus',
    order: 32,
    title: 'Chain rule',
    subtitle: 'Differentiating compositions',
    estimatedMinutes: 5,
    difficulty: 'beginner',
    prerequisites: ['B31'],
    explanation:
      'The chain rule says the derivative of a composition is the product of derivatives: if y = f(g(x)) then dy/dx = f′(g(x)) g′(x). For multivariable functions, it generalises to a sum of products of partial derivatives.',
    notation: '(d/dx) f(g(x)) = f′(g(x)) g′(x)',
    keyTerms: ['chain rule', 'composition', 'backpropagation'],
    example:
      'Backpropagation in neural networks is the chain rule applied repeatedly through every layer of the network.',
    intuition: 'To differentiate nested functions, multiply the derivatives at each layer.',
    whyItMatters:
      'Without the chain rule there is no backprop and no modern deep learning.',
    questions: [
      {
        prompt: 'For y = (3x + 1)², dy/dx equals...',
        options: ['2(3x + 1)', '6(3x + 1)', '3(3x + 1)', '6'],
        answerIndex: 1,
        explanation: 'Outer derivative 2(3x+1) times inner derivative 3.',
      },
      {
        prompt: 'Backpropagation is fundamentally...',
        options: ['Random search', 'The chain rule applied through layers', 'A regulariser', 'A loss function'],
        answerIndex: 1,
        explanation: 'It chains derivatives backward through the computational graph.',
      },
      {
        prompt: 'The chain rule for composition implies the gradient of a deep network...',
        options: [
          'Is just the gradient of the last layer',
          'Is a product of per-layer derivatives, growing with depth',
          'Cannot be computed',
          'Is always one',
        ],
        answerIndex: 1,
        explanation: 'Hence vanishing/exploding gradients can occur in deep networks.',
      },
    ],
    xpReward: 24,
    coinReward: 9,
    masteryThreshold: 0.8,
  },
  {
    id: 'B33',
    trackId: 'math',
    moduleId: 'B-calculus',
    order: 33,
    title: 'Gradient',
    subtitle: 'The vector of all partial derivatives',
    estimatedMinutes: 5,
    difficulty: 'intermediate',
    prerequisites: ['B32'],
    explanation:
      'The gradient ∇f of a multivariable function is the vector of its partial derivatives. It points in the direction of steepest increase, and its magnitude is the rate of change in that direction.',
    notation: '∇f = (∂f/∂x₁, ..., ∂f/∂xₙ)',
    keyTerms: ['gradient', 'steepest descent', 'directional derivative'],
    example:
      'Gradient descent updates a weight vector w in the direction −∇L(w), the steepest decrease of the loss.',
    intuition: 'Climb a hill quickest by walking along the gradient; descend quickest by walking against it.',
    whyItMatters:
      'Every gradient-based optimiser - SGD, Adam, RMSProp - relies on this object.',
    questions: [
      {
        prompt: 'The gradient ∇f points in the direction of...',
        options: ['Slowest change', 'Steepest decrease', 'Steepest increase of f', 'Zero change'],
        answerIndex: 2,
        explanation: 'Gradient = steepest ascent direction.',
      },
      {
        prompt: 'Gradient descent updates parameters by...',
        options: ['Adding the gradient', 'Subtracting the gradient (scaled by a learning rate)', 'Multiplying by the gradient', 'Ignoring the gradient'],
        answerIndex: 1,
        explanation: 'w ← w − η ∇L moves opposite to the gradient.',
      },
      {
        prompt: 'A point where ∇f = 0 is called a...',
        options: ['Saddle only', 'Critical point', 'Maximum only', 'Minimum only'],
        answerIndex: 1,
        explanation: 'It can be a minimum, maximum, or saddle.',
      },
    ],
    xpReward: 24,
    coinReward: 9,
    masteryThreshold: 0.8,
  },
  {
    id: 'B34',
    trackId: 'math',
    moduleId: 'B-calculus',
    order: 34,
    title: 'Integral as accumulation',
    subtitle: 'Adding up tiny pieces',
    estimatedMinutes: 5,
    difficulty: 'beginner',
    prerequisites: ['B14'],
    explanation:
      'The integral of f over an interval is the limit of sums of f times small increments - the area under the curve. Integration is the inverse of differentiation: if F′ = f, then ∫ f dx = F + C.',
    notation: '∫ₐᵇ f(t) dt',
    keyTerms: ['integral', 'antiderivative', 'area', 'accumulation'],
    example:
      'Total charge accumulated by a neuron over a window of time is the integral of its input current over that window.',
    intuition: 'Differentiation slices into rates; integration glues rates back into totals.',
    whyItMatters:
      'Many physical and statistical quantities (charge, probability mass, expected value) are integrals.',
    questions: [
      {
        prompt: 'The integral of f from a to b geometrically represents...',
        options: ['The slope of f', 'The area under f between a and b', 'The maximum of f', 'The derivative of f'],
        answerIndex: 1,
        explanation: 'It is the signed area.',
      },
      {
        prompt: 'Integration is the inverse of...',
        options: ['Multiplication', 'Differentiation', 'Addition', 'Logarithm'],
        answerIndex: 1,
        explanation: 'Fundamental theorem of calculus.',
      },
      {
        prompt: 'Total charge from a current I(t) over [0, T] is...',
        options: ['I(T)', '∫₀ᵀ I(t) dt', 'dI/dt', '0'],
        answerIndex: 1,
        explanation: 'Integrating current over time gives charge.',
      },
    ],
    xpReward: 22,
    coinReward: 8,
    masteryThreshold: 0.8,
  },
  {
    id: 'B35',
    trackId: 'math',
    moduleId: 'B-dynamics',
    order: 35,
    title: 'Linear first-order ODE',
    subtitle: 'The classic exponential decay equation',
    estimatedMinutes: 6,
    difficulty: 'intermediate',
    prerequisites: ['B15'],
    explanation:
      'A linear first-order ODE has the form τ dx/dt = −(x − x_∞). Its solution is x(t) = x_∞ + (x(0) − x_∞) e^(−t/τ): the variable approaches the steady state x_∞ exponentially with time constant τ.',
    notation: 'x(t) = x_∞ + (x(0) − x_∞) e^(−t/τ)',
    keyTerms: ['ODE', 'time constant', 'exponential', 'steady state'],
    example:
      'A leaky neuron driven by a constant current relaxes to a steady-state voltage exponentially with its membrane time constant.',
    intuition: 'Exponential approach to a target, with τ setting the speed.',
    whyItMatters:
      'It is the canonical model for membrane voltage, synaptic conductance decay, and many low-pass filters.',
    questions: [
      {
        prompt: 'For τ dx/dt = −(x − x_∞) with x(0) = 0, after one time constant t = τ, x has reached approximately...',
        options: ['100% of x_∞', '63% of x_∞', '37% of x_∞', '0% of x_∞'],
        answerIndex: 1,
        explanation: '1 − e⁻¹ ≈ 0.63.',
      },
      {
        prompt: 'A larger τ corresponds to...',
        options: ['Faster relaxation', 'Slower relaxation', 'No relaxation', 'Random behaviour'],
        answerIndex: 1,
        explanation: 'Big time constant = slow approach.',
      },
      {
        prompt: 'The steady state x_∞ is found by...',
        options: ['Setting dx/dt = 0', 'Setting x = 0', 'Setting τ = 0', 'Setting t = 0'],
        answerIndex: 0,
        explanation: 'No more change ⇔ derivative is zero.',
      },
    ],
    xpReward: 26,
    coinReward: 10,
    masteryThreshold: 0.8,
  },
  {
    id: 'B36',
    trackId: 'math',
    moduleId: 'B-prob',
    order: 36,
    title: 'Conditional probability and Bayes’ rule',
    subtitle: 'Updating beliefs with evidence',
    estimatedMinutes: 6,
    difficulty: 'beginner',
    prerequisites: ['B18'],
    explanation:
      'P(A|B) is the probability of A given that B happened: P(A|B) = P(A and B) / P(B). Bayes’ rule rearranges this into P(A|B) = P(B|A) P(A) / P(B), letting us update beliefs about A from evidence B.',
    notation: 'P(A|B) = P(B|A) P(A) / P(B)',
    keyTerms: ['conditional probability', 'Bayes', 'prior', 'likelihood', 'posterior'],
    example:
      'Inferring a stimulus from neural activity uses Bayes: posterior over stimulus is proportional to likelihood (neural code) times prior (prior beliefs).',
    intuition: 'Bayes = a recipe to combine prior expectations with new evidence.',
    whyItMatters:
      'Bayesian inference underlies decoding, perceptual inference, and most statistical learning.',
    questions: [
      {
        prompt: 'Bayes’ rule writes the posterior P(A|B) as proportional to...',
        options: ['P(B|A) P(A)', 'P(A) only', 'P(B) only', 'Random'],
        answerIndex: 0,
        explanation: 'Posterior ∝ likelihood × prior.',
      },
      {
        prompt: 'In Bayesian decoding, the prior represents...',
        options: ['Neural noise', 'Beliefs about the stimulus before observing activity', 'A loss function', 'The likelihood itself'],
        answerIndex: 1,
        explanation: 'Prior = belief before evidence.',
      },
      {
        prompt: 'P(A|B) is well-defined only when...',
        options: ['P(B) > 0', 'P(A) > 0', 'A and B are independent', 'A = B'],
        answerIndex: 0,
        explanation: 'Conditioning requires the conditioning event to have positive probability.',
      },
    ],
    xpReward: 26,
    coinReward: 10,
    masteryThreshold: 0.8,
  },
  {
    id: 'B37',
    trackId: 'math',
    moduleId: 'B-prob',
    order: 37,
    title: 'Expectation and variance',
    subtitle: 'Mean and spread of a random variable',
    estimatedMinutes: 5,
    difficulty: 'beginner',
    prerequisites: ['B18'],
    explanation:
      'The expectation E[X] is the average value of a random variable X, weighted by probability. The variance Var[X] = E[(X − E[X])²] measures how spread its values are around the mean. Standard deviation is the square root of variance.',
    notation: 'E[X] = Σ x P(X = x);  Var[X] = E[X²] − (E[X])²',
    keyTerms: ['expectation', 'variance', 'standard deviation', 'spread'],
    example:
      'A neuron with mean firing rate 10 Hz and variance 10 spikes² has a Fano factor of 1, consistent with a Poisson process.',
    intuition: 'Expectation = where it sits on average. Variance = how much it wiggles.',
    whyItMatters:
      'These two numbers summarise most noisy quantities and are the basis of estimators and noise models.',
    questions: [
      {
        prompt: 'The expectation of a Bernoulli(p) random variable is...',
        options: ['p', '1 - p', 'p(1-p)', '1'],
        answerIndex: 0,
        explanation: 'E[X] = 0(1−p) + 1(p) = p.',
      },
      {
        prompt: 'Variance of a constant random variable is...',
        options: ['1', '0', 'The constant itself', 'Undefined'],
        answerIndex: 1,
        explanation: 'No spread ⇒ variance 0.',
      },
      {
        prompt: 'Standard deviation has the same units as...',
        options: ['Variance', 'The random variable itself', 'Probability', 'Time only'],
        answerIndex: 1,
        explanation: 'It is the square root of variance.',
      },
    ],
    xpReward: 22,
    coinReward: 8,
    masteryThreshold: 0.8,
  },
  {
    id: 'B38',
    trackId: 'math',
    moduleId: 'B-prob',
    order: 38,
    title: 'Gaussian distribution',
    subtitle: 'The bell curve and why it appears everywhere',
    estimatedMinutes: 6,
    difficulty: 'beginner',
    prerequisites: ['B37'],
    explanation:
      'A Gaussian (normal) random variable has density ∝ exp(−(x−μ)² / 2σ²). It is fully specified by its mean μ and variance σ². Sums of many small independent contributions tend toward a Gaussian, the central limit theorem.',
    notation: 'X ~ N(μ, σ²)',
    keyTerms: ['Gaussian', 'normal', 'CLT', 'mean and variance'],
    example:
      'Membrane voltage fluctuations driven by many small synaptic inputs are often well approximated by a Gaussian.',
    intuition: 'When many small noises add up, you almost always get a bell curve.',
    whyItMatters:
      'Gaussians are the default noise model and underlie linear regression, Kalman filtering, and most analytic neuroscience.',
    questions: [
      {
        prompt: 'A Gaussian distribution is fully specified by...',
        options: ['Its median only', 'Its mean and variance', 'Its skewness', 'No parameters'],
        answerIndex: 1,
        explanation: 'Two numbers determine a Gaussian.',
      },
      {
        prompt: 'The central limit theorem says that sums of many independent contributions tend toward a...',
        options: ['Uniform distribution', 'Poisson distribution', 'Gaussian distribution', 'Bernoulli distribution'],
        answerIndex: 2,
        explanation: 'CLT: many small effects ⇒ Gaussian.',
      },
      {
        prompt: 'About what fraction of a Gaussian falls within ±1σ of the mean?',
        options: ['About 50%', 'About 68%', 'About 95%', 'About 99.7%'],
        answerIndex: 1,
        explanation: '~68% within one standard deviation; ~95% within two.',
      },
    ],
    xpReward: 24,
    coinReward: 9,
    masteryThreshold: 0.8,
  },
  {
    id: 'B39',
    trackId: 'math',
    moduleId: 'B-stats',
    order: 39,
    title: 'Sample statistics and maximum likelihood',
    subtitle: 'Estimating parameters from data',
    estimatedMinutes: 6,
    difficulty: 'intermediate',
    prerequisites: ['B38'],
    explanation:
      'Given a sample x₁, ..., x_n, the sample mean and sample variance estimate the underlying mean and variance. Maximum likelihood estimation chooses parameters θ that make the observed data most probable: θ̂ = argmax_θ Π p(x_i | θ).',
    notation: 'θ̂ = argmax_θ Σᵢ log p(xᵢ | θ)',
    keyTerms: ['estimator', 'sample mean', 'maximum likelihood', 'log-likelihood'],
    example:
      'Fitting a Poisson firing rate from spike counts is MLE; the estimate is just the empirical mean count.',
    intuition: 'Pick parameters that make your data look least surprising.',
    whyItMatters:
      'MLE underlies most parameter fitting in statistics and machine learning.',
    questions: [
      {
        prompt: 'The sample mean of n values is...',
        options: ['Their product', 'Their sum divided by n', 'Their median', 'Their variance'],
        answerIndex: 1,
        explanation: 'Arithmetic mean of the sample.',
      },
      {
        prompt: 'Maximum likelihood estimation chooses parameters that...',
        options: [
          'Minimise the data',
          'Maximise the probability of the observed data under the model',
          'Are random',
          'Ignore the model',
        ],
        answerIndex: 1,
        explanation: 'It maximises the likelihood of the data.',
      },
      {
        prompt: 'For Gaussian data with known variance, the MLE of the mean is...',
        options: ['The maximum of the data', 'The sample mean', 'Always zero', 'The median only'],
        answerIndex: 1,
        explanation: 'MLE of μ under Gaussian noise is the sample mean.',
      },
    ],
    xpReward: 26,
    coinReward: 10,
    masteryThreshold: 0.8,
  },
  {
    id: 'B40',
    trackId: 'math',
    moduleId: 'B-info',
    order: 40,
    title: 'Entropy and mutual information',
    subtitle: 'Measuring information in random variables',
    estimatedMinutes: 6,
    difficulty: 'intermediate',
    prerequisites: ['B37'],
    explanation:
      'Entropy H(X) = −Σ p(x) log p(x) measures how uncertain a random variable is. Mutual information I(X; Y) = H(X) − H(X|Y) measures how much knowing Y reduces uncertainty about X.',
    notation: 'I(X; Y) = H(X) − H(X|Y)',
    keyTerms: ['entropy', 'mutual information', 'bits', 'channel'],
    example:
      'Mutual information between a stimulus and a neuron’s spike count quantifies how much that neuron’s response tells you about the stimulus.',
    intuition: 'Entropy = surprise. Mutual information = shared surprise reduced by observation.',
    whyItMatters:
      'Information-theoretic measures form a model-free way to quantify neural coding.',
    questions: [
      {
        prompt: 'Entropy of a fair coin (in bits) is...',
        options: ['0', '1', '2', '∞'],
        answerIndex: 1,
        explanation: 'H = −(0.5 log₂ 0.5 + 0.5 log₂ 0.5) = 1 bit.',
      },
      {
        prompt: 'If X and Y are independent, then I(X; Y) is...',
        options: ['Maximal', '0', 'Negative', 'Equal to H(X)'],
        answerIndex: 1,
        explanation: 'Independent variables share no information.',
      },
      {
        prompt: 'Mutual information is symmetric in its arguments, so I(X; Y) equals...',
        options: ['H(X)', 'I(Y; X)', 'H(Y)', '0'],
        answerIndex: 1,
        explanation: 'I(X; Y) = I(Y; X) by definition.',
      },
    ],
    xpReward: 28,
    coinReward: 11,
    masteryThreshold: 0.8,
  },
];
